OpenKore/openkore

src/AI/CoreLogic.pm

There are an handful of items that cannot be placed in the storage. Sometimes the user doesn't remember to set the proper flag for them on `items_control.txt` before setting the bot to auto-storage. This usually generates a loop. Openkore tries to store the item, but the item is pushed back on the inventory.

Changing the default  behavior of auto-storage

---

src/Settings.pm

This is a request to add 3 hooks to Settings::loadByHandle, the purpose
of this request is to make it possible for plugins to change the filepath
and parsing method of any file just before it's loading. Be aware that
hook names depend on the loading file.

New hooks in files loading

---

src/FileParsers.pm

This is a request to add 2 new hooks in FileParsers::updatePortalLUT2
and FileParsers::updatePortalLUT. The purpose is to add support for
plugin related custom portal file updating.

New hooks in FileParsers

---

openkore.pl
src/Git.pm
src/Settings.pm

- Re-build start.exe and wxstart.exe (unnecessary, because we're no longer adding any new module requirements)
Git version detection is actually pretty easy... but the hash isn't very informative by itself. Getting the commit date is much harder... but seems like a useful way of communicating whether the code is massively out of date.
This pull request generates a git revision which looks like SHA_YYYY-MM-DD. For example:
```
$ ./openkore.pl -v
*** OpenKore what-will-become-2.1 ( version 436478c_2016-02-29 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
```

fix #1 detect git revision

---

.gitignore
control/sys.txt
openkore.pl
plugins/profiles/profiles.pl
src/Settings.pm
src/functions.pl

Turn on the profiles plugin by default. This requires at least that we don't prompt if there are no profiles.
As a stretch goal, I want to be able to pass in a profile via a command line option.

Enable profiles plugin

---

src/Network/Send/idRO.pm

* Since `Send.pm::sendStoragePassword` looking for packet_lut, `storage_password 023B` need to be redefined.

Follow up 81406f44ff1eb4a69d00d2c2d76bdf0f1bfc49f5

---

control/config.txt
src/ChatQueue.pm

There should be a way to prevent in-game auth to Chat Commands by sending a message with adminPassword, in order to prevent people from abusing an easy adminPassword
http://openkorebrasil.org/index.php?/topic/499-aonde-posso-pegar-atualiza%C3%A7%C3%A3o-segura/
http://openkorebrasil.org/index.php?/topic/490-logout/

Chat Commands Auth

---

tables/iRO/items.txt

Disambiguate a few item names which were missed in the last sweep. This is why having them separate is so great: we don't need to wonder which names have been customized for openkore users!

disambiguate some more iRO item names

---

control/routeweights.txt
tables/portals.txt

Add support for prt_fild08a, and try to prevent `Task::MapRoute` from routing through it (unless we have to, like if somebody sets it as their `lockMap`).

add portals for iRO's custom prt_fild08a

---

src/Network/Receive/iRO.pm
src/Network/Send/iRO.pm

iRO now does the same thing fRO does: after talking to an NPC vendor, we must send a 09D4 packet before we can move.
This pull request solves the problem in a different way from the fRO solution, so that it will (hopefully) work in more use cases. Here we keep track of whether we started talking to an NPC vendor and send the packet along with the next move packet, regardless of whether we tried to buy or sell something.

let the server know that we're done buying/selling so we can move

---

src/AI/CoreLogic.pm

Add option to turn off the `attackAuto` logic entirely.
Without this, the bot will spend time thinking about attacking nearby monsters even if it ultimately chooses not to attack. And more importantly, if a monster attacks the bot, the bot will stop and try to attack back. This is often a bad idea, particularly for priests trying to run past aggressive monsters.
With `attackAuto -1`, priests (and other support characters) can easily run past aggressive monsters without stopping.

add attackAuto -1

---

src/FileParsers.pm
src/Utils/TextReader.pm
src/test/FileParsersTest.pm
src/test/Utils/TextReaderTest.pm
src/test/data/write_config.txt
src/test/data/write_config_a.txt

Making a config change inside kore auto-saves the config. Since the recent change to `Utils::TextReader`, that re-save would cause all included files to be inlined into the config, instead of being preserved as includes.
This pull request fixes that.

fix updating config.txt with !include

---

src/Settings.pm
src/functions.pl

Add `--command=...` command line option. Useful for completely automated processes like:
```
openkore.pl --command="macro do_something_and_quit"
```

add --command command line option

---

src/Network/Receive/kRO/Sakexe_0.pm

Hook calls and $char changes should be consistent across servertypes, in
ServerType0 $char is changed before the hook call, in Sakexe_0 it should
also be done this way.

Character zeny change moved to before hook call

---

src/Commands.pm

Add wildcard searching to conf command, to make it easier to find the config option the user is trying to change.
For example, to find all "sit" related options, do: `conf sit*`
Some patterns produce a lot of results. For example, `conf skill*`. The conf options are sorted to hopefully make these easier to browse.
Multiple wildcards are allowed. For example, `conf tele*lock` finds all options which include "tele" followed by "lock". Which for me finds three options: teleportAuto_maxDmgInLock, teleportAuto_minAggressivesInLock, and teleportAuto_totalDmgInLock.

add wildcard search to conf command, eg "conf sit*"

---

src/Network/Receive/idRO.pm

* Now force to use this RegEX: `/^micc.{23}\x00([0-9A-Fa-f]{6})(.*)/`
* Fixes #90

Fixed idRO `system_chat`

---

src/AI/CoreLogic.pm

When kore puts an item into storage but keeps some of it in inventory we
receive the error message "Unable to store", but the item was stored,
this is due to an error in the error message verification. this change
should fix it.
Image of error:
https://i.gyazo.com/f694972338c497f6b7dc9cef21b83432.png
After change: 
https://i.gyazo.com/2dd1c91d968cf410139edc35a3612313.png

fix for autostorage bug

---

src/Network/Send/ServerType0.pm
src/Network/Send/kRO/Sakexe_0.pm

Adds support for 02F1 (PACKET_CZ_PROGRESS), packet which notifies the server that the progress bar has been completed.
Reference (pt-br): http://bit.ly/2dmpUhg

Support for 02F1

---

src/Poseidon/RagnarokServer.pm
src/Poseidon/servertypes.txt

Adds missing charblocksizes to poseidon server
Adds bRO_2016-10-11a as a poseidon servertype
Adds '09D0' as a gameguard sync packet

Poseidon compatibility with bRO

---

tables/bRO/skillnametable.txt

Updates bRO's skillnametable from its decompiled skillinfolist.lub (path in data.grf: data\luafiles514\lua files\skillinfoz\skillinfolist.lub).
All skills are present, although many were shifted around due to the differences between the sequences in the new lub file and the old text file.
This solves the missing skills problem, mainly after the latest episode patches.

bRO's skillnametable.txt from skillinfolist.lua

---

src/Network/Send/ServerType0.pm

These packets are sent to the server by the client.
00A7 -> CZ_USE_ITEM
00BB -> CZ_STATUS_CHANGE
Reference: http://openkorebrasil.org/index.php?/topic/1633-packet-parser-unknown-switch-00a7/ (pt-br)

Adds 00A7 and 00BB

---

src/Commands.pm

***Fixed two issues outlined in Ticket #271:***
**Issue A** - Text for the NPC talk response choices were cut off if they
were longer than 36 characters.
**Issue B** - Numeric response codes for the choices need to be right
justified because up to two digit codes (i.e. more than 0-9 choices)
are possible.
Fixed by referencing: http://perldoc.perl.org/perlform.html
ticket:   #271
branch:   talk_response
modified: src/Commands.pm

Fix formatting for NPC talk response choices #271

---

tables/bRO/portals.txt

Just got fooled by divine pride database this is the correct location of Gonryun Eden Officer NPC at bRO.

Correction of Gonryun Eden Officer NPC location

---

src/AI/CoreLogic.pm

With this we can hook something to all AI states and even execute stuff when AI is off or in manual, and only when we are connected and $timeout{ai} is off.
I think this is an awesome hook and may be way better than 'mainLoop_pre' in many situations.

Add hook 'AI_start'

---

src/Commands.pm

For some reason typing 'ai off' and 'ai' on auto mode creates different results.
I think it should set $AI to AI::OFF when setting it off.

Fix wrong AI setting in 'ai' command

---

src/Network/DirectConnection.pm
src/Network/Receive.pm

Message with server info should be displayed only if specified server exists in the list.

Fix crash when server config option is invalid

---

SConstruct
src/Utils/Benchmark.pm
src/auto/XSTools/SConscript
src/auto/XSTools/darwin/include/perl.h

Can't get Benchmark module to build correctly, so disabled that on OS X for now.
Run `make clean all` first.

Fix building on OS X

---

Makefile

It's common convention to run tests with just `make test`. I'm not sure what the current `test` target is used for.

Run tests with `make test` instead of launching openkore

---

src/Poseidon/poseidon.pl

Right now, poseidon.pl cannot reach the precompiled dll for Windows (XSTools.dll) in the trunk folder, therefore the user has to move it to src/, src/Poseidon or src/deps/.
Retrieve address from object. Useful when setting the port to zero in poseidon.txt

poseidon.pl small changes

---

plugins/needs-review/leaveMeAlone/trunk/leaveMeAlone.pl
src/ErrorHandler.pm
src/Interface/Console/Curses.pm
src/Settings.pm

We were not including the git sha (if available) in `errors.txt`. This pull fixes that.
In addition, as the git sha isn't always available (many users use "Download ZIP" instead of a git client to get the code), this pull adds the creation date of `Settings.pm` to the version string. Github sets the creation date of all files in downloaded zipfiles to (near?) the date of the last commit.
Before: `SVN revision: unknown`
After: `Revision: git:9ddeda4_2017-02-19 ctime:2017_02_19`

reformat revision to include both git and file creation date

---

src/Network/Receive/ServerType0.pm

Show a notice when the bot loses a skill. This usually happens when unequipping something which confers a skill (eg, unequipping a Vitata Card removes the Heal skill).

notify users when they lose skills (typically due to equipment changes)

---

src/Network/Receive/ServerType0.pm
src/functions.pl

There are two types of map changes in RO: teleport/portal change on the current map server, and map server changes. If we don't change map servers, the client is expected to keep the character's cart info (if any). If we do change map servers, the client is given new cart info, so we can discard the old one.
The code was set up opposite to the way it was supposed to be. We kept the cart when changing map servers (which is pretty harmless), and we threw away the cart when not changing map servers (which made the cart disappear after a teleport).
This pull request puts it back the way it's supposed to be.

fix #443 cart should only be removed for map server changes

---

src/functions.pl

This pull request undoes more of the timing changes introduced by the InventoryList refactor. The cart inventory is supposed to be cleared when we log in (this pull request), and cart existence is supposed to be set when we get a `map_changed` packet (a different pull request, already merged).
Without this code, the cart can get into a bad state, with phantom items in the cart which can cause disconnects when the user tries to do something with them. And relogging won't fix it.

fix cart inventory; should clear when logging in

---

src/AI/CoreLogic.pm

This change makes it so that equipAuto won't activate (change equips) on slots that are currently being used by an ongoing skill (with the equip_slot configuration).

Add skill equip check in equipAuto

---

control/config.txt
src/AI/CoreLogic.pm
src/Task/TalkNPC.pm
tables/bRO/control-br/config.txt

With these changes openkore won't send unecessary packets to the server during autobuy ( #671  ) if it cannot talk to the npc and also won't check for a sell list if it isn't already talking to a npc.
Also `e` at the end of sellauto and buyauto are not necessary since Task::TalkNPC will clear itself if no more steps are given after a buy or sell interaction.

add npc checks in autobuy and autosell sequence

---

src/Commands.pm

Useful for talking with NPCs whose sequence consists of only `c` (Next) items.

Allow using talknpc command with empty conversation sequence

---

plugins/breakTime/breakTime.pl

now works like
```
autoBreakTime wed tue {
startTime 01:00
stopTime 02:00
}
```
wed or tue

[breakTime.pl] multi days with same time support

---

plugins/macro/macro.pl

Example:
`macro farm -overrideAI -exclusive -- sleep`
$.param1 was **verrideAI** now **sleep**

Minor "macro" command bug fix.

---

src/Task/TalkNPC.pm

When npc could not be found 'x' would be added many times to the queue, this fixes that.

Minor bugfix in Task::TalkNPC

---

src/AI.pm
src/AI/CoreLogic.pm
src/Actor/You.pm
src/Commands.pm
src/Interface/Wx/ItemList.pm
src/InventoryList.pm
src/Match.pm
src/Misc.pm
src/Network/Receive.pm
src/Utils/ObjectList.pm
src/test/ObjectListTest.pm

`@$playersList` is much shorter than `@{$playersList->getItems}` and IMO doesn't hurt readability.
Also, if `$list` is undefined, `@$list` would successfully evaluate to empty array, so in some situations it's not even needed to check if `$list` is defined.

Overload array dereferencing for ObjectList

---

src/Utils/TextReader.pm

Before: `Unable to load the file .`
After: `Unable to load the file profiles/abc/included.txt.`

provide filename so !include errors in config.txt will report it

---

control/sys.txt
plugins/map/map.pl

Map plugin output with the `Console::Curses` interface (this is automatic and refreshes periodically):
```
############$           $    $          ####
############$    $  $    p              ####
##############                 $    $     ####
##############                            ####
##############$    $                      ####
############$    $          $         ######
############        p           $       ####
#######            p$                  ####
#######               $   $          ######
######### n         @                  ####
#######             p    $p            ####
#######       p    p   $   p   $       ####
#########     ##           $   $  ##   ####
#######$   $  ##p      $          ##   ####
$   p    p  $   $ p    $         #
$$   p      p      $ …
```

enable map plugin by default

---

tables/iRO/Restart/official/portals.txt

Accidentally omitted this config during the duplicate check.
Please add this as well.

Morocc portals fix: 1 missing config

---

src/Network/Receive/RMS.pm
src/Network/Send/RMS.pm
tables/servers.txt

RMS now requires encryption to login (cryptKeys).
We could change it directly in kRO_RagexeRE_2014_10_22b, but that might break other servers using this ServerType

Give RMS its own ServerType

---

src/Task/TalkNPC.pm

This is already done this way for $config{npcTimeResponse} to prevent configuration errors, and seeing the great number of people forgeting to update their timeouts.txt I guess this is a good idea.

add default timeouts to Task::TalkNPC

---

src/AI/CoreLogic.pm

This is useful because it is where 'new' monsters are chosen to be attacked when kore is not already attacking or being attacked. I am using it to avoid attacking monsters which can be assisted by others of its own nameID (namely Wolves), to do so I am using my plugin avoidAssisters (https://github.com/Henrybk/Plugins/blob/master/avoidAssisters/avoidAssisters.pl)

add hook on processAutoAttack cleanMonsters

---

src/Log.pm
src/Misc.pm
src/Settings.pm
src/functions.pl

* Make console log location configurable via command line.
* Fix command line configuration for chat log and storage log, which was ignored before.
* Support `logAppendUsername` and `logAppendServer` for the console log. The console log is active before config files are loaded, so some data is still written to `console.txt`, even when `logAppendUsername` and/or `logAppendServer` are used.
* Update log filenames when config changes happen (initial load and inside `configModify`). This was previously done on map change, which doesn't happen as quickly after a config change. To catch stealth config changes, we also continue to update log filenames on map change.

better log file name handling

---

control/sys.txt
control/timeouts.txt
plugins/reconnect/reconnect.pl

Progressively back off connect times, to reduce load on servers. Some servers have logic which blocks repeated reconnect attempts if they happen too fast. And the default 30 seconds is too fast, at least on iRO Restart.
The backoff list given here is `30,60,120,180,300,600,600,900,900,1800`, which equates to nine connection attempts in the first hour, followed by two connection attempts every hour.
Based on https://github.com/Henrybk/Plugins/blob/master/Reconnect/Reconnect.pl.
Here's an example of the plugin in action:
```
Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
Timeout on Account Server, reconnecting. Wait 45 seconds...
Disconnecting (128.241.92.133:6800)...disconnected
Connecting to Account Server...
[reconnect] Login retry number 2, setting …
```

add reconnect plugin

---

plugins/reconnect/reconnect.pl

It turns out that `Network::connectTo` triggers for all server connect attempts, so a connection failure on the map server counts as three failures (login, character, and map server).
This pull request limits the backoff to only apply on login server connect attempts.

only trigger reconnect backoff for the login server

---

tables/iRO/Restart/resnametable.txt

This uses the iRO official `resnametable.txt` file, for now, until iRO Restart gets its own version.

fix izlude in iRO Restart

---

control/timeouts.txt
src/AI.pm
src/AI/CoreLogic.pm
src/Commands.pm
src/InventoryList.pm
src/Misc.pm

Previously supported (and currently supported):
* `storage add Empty Bottle`
* `storage add 5`
* `storage add Empty Bottle 1`
* `storage add 5 1`
Newly supported:
* `storage add "Empty Bottle"`
* `storage add "Empty Bottle,Jellopy"`
* `storage add 1-5,9`
* `storage add "Empty Bottle" 1`
* `storage add "Empty Bottle,Jellopy" 1`
* `storage add 1-5,9 1`
The same treatment was given to `storage get`, `storage addfromcart`, `storage addtocart`, `cart get`, and `cart add`.
Multiple items are added via an AI sequence which only runs on auto AI (not manual), which I'm not sure I like. I believe it can only be triggered by a manual command on the console, which means it should run under manual AI. Thoughts?
A new `ai_transfer_items` timeout controls the delay between each item when transferring …

allow "storage add" to store multiple items at once

---

src/Task/CalcMapRoute.pm

While since my last change in CalcMapRoute made tele tickets work there was still a problem, openkore would not count the number of tickets used to a certain point nor the amount of zeny it saved by doing so, with this change both of these things are now fixed.
Example of situation that where kore found not work well before:
Number of tickets: 1
Zeny: 0
Route: 
Payon > Prontera (by Kafra)
Prontera > Al De Baran (by Kafra)
CalcMapRoute would think you could do this route because you had a ticked when actually you needed 2 tickets or 1 ticket + 3,000z.

Fix free kafra ticked for teleportation

---

control/config.txt
control/timeouts.txt
src/AI/CoreLogic.pm
src/FileParsers.pm
src/Globals.pm
src/Task/MapRoute.pm
src/functions.pl
tables/portals.txt

This pull request is being made to create a discussion regarding the possible solutions for this old known problem.
Ilustration of the problem: https://i.gyazo.com/e157f69c4dda6146016db01d71c1eba6.jpg
Definition: Openkore now has no way of dealing with a missing portal and will just stay on top of the portal location in portals.txt sending loads of move packets to the server and never moving a muscle.
I showed 2 possible solutions for the problem in the files changed, first is to just delete the portal and re-route, as we do with missing npcs, and second is to try to search for near portals and route to them hoping they are the portal we actually want to reach.

Beta change to make kore notice missing portals

---

src/Commands.pm

When adding items to a deal in a batch, the number of items dealt would be the minimum of the stack size of the items so far, instead of the whole stack.
So if the following items were in inventory:
```
Jellopy x 7
Red Herb x 10
Green Herb x 5
Blue Herb x 15
```
... then the following item amounts would be dealt:
```
Jellopy x 7
Red Herb x 7
Green Herb x 5
Blue Herb x 5
```
This change causes the entire stack to be dealt instead.

use the size of each stack for "deal 0-99"

---

control/sys.txt
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm
plugins/macro/Macro/Parser.pm
plugins/needs-review/mercdb/tags/start/mercdb.pl
plugins/needs-review/mercdb/trunk/mercdb.pl
src/Commands.pm
src/Globals.pm
src/InventoryList.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/iRO.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Task/TalkNPC.pm
src/functions.pl

- Code Review
* Enable eventMacro plugin.
* Fix `&cart()`, `&inventory()`, `&storage()`, `&venderitem()`.
One can do this (painfully) with `&eval()`, like so:
```
$list = a,b,c,d
@array = ()
&push(@array, &eval( (split(',', '$list'))[0] ))
&push(@array, &eval( (split(',', '$list'))[1] ))
&push(@array, &eval( (split(',', '$list'))[2] ))
&push(@array, &eval( (split(',', '$list'))[3] ))
```
This pull request adds the ability do this in a simpler way:
```
$list = a,b,c,d
@array = split(',', $list)
```
Previously, there were two parameters to `call`: the macro name and a "repeat" parameter, which said how many times to call the macro. Most people probably didn't know the feature existed, and I don't think I've ever seen code using it.
This pull request changes the meaning of extra parameters …

enable eventMacro, fix &inventory and friends, pass params to called macros

---

src/Commands.pm

Allow console commands to force set an option, even if it doesn't already exist in `config.txt`.
This allows macros to use config.txt as permanent storage for their data. For example, it can be used to abort access quests if they have already been run:
```
macro quest_juice {
if (@config(quest_juice) == complete) stop
call quest_talk prontera '64 125' 'b b0,1 e'
call quest_talk prt_in '47 173' 'r1 r1 e'
call quest_talk prt_in '49 172' 'e'
log Juice quest complete!
do conf -f quest_juice complete
}
```

add -f option to conf command

---

control/timeouts.txt
src/AI/CoreLogic.pm
src/Commands.pm
src/Network/Receive/ServerType0.pm

Fixed party setting spam.
**Reference**: #870 
**Currently:**
Kore don't have timeout or control to party share settings, he send party settings everytime when receive the following packets:
'00FB' => ['party_users_info']
'01E9' => ['party_join']
**After Changes:**
- Moved party share settings to AI
- Added `ai_partyShareCheck` in timeouts.txt to check every x seconds if party settings are right
- Openkore will not try to change back the settings if we send the command `party share 0|1`
- Added arg `shareauto` in party command. (this command allow AI check party settings again after we send  `party share 0|1`)
- Openkore warning us if we are spamming party share settings

party share enhacement

---

plugins/eventMacro/eventMacro.pl
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/FileParser.pm

Previously, an `eventMacros.txt` file which contained an unclosed block would return `undef` from the `eventMacro::Core` constructor, which would result in a crash when somebody tried to call an eventMacro. In addition, no error message was displayed, so the user didn't know that their file failed to parse.
This pull request provides a message when there is an unclosed block in the file. It also attempts to return a minimally functional value for `$eventMacro`, so that if parsing fails, calling an eventMacro will simply fail rather than crash.

fix crash on unclosed block in eventMacros.txt

---

plugins/eventMacro/eventMacro/Core.pm

Similar to $.status, but with HANDLEs.
Does not support "dead" or "muted" statuses (after all, they aren't really statuses and therefore don't have handles)
Useful for cross-server eventMacros compatibility

[eventMacro] add $.statushandle

---

plugins/eventMacro/eventMacro/Data.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

Add some new eventMacro functions:
* `&questStatus(7123)` returns the status of quest 7123 as a string (see below for possible strings and meanings)
* `&questInactiveCount(7123,7124,7126,7127)` returns the number of given quests which have status "inactive"
* `&questIncompleteCount(7123,7124,7126,7127)` returns the number of given quests which have status "incomplete"
* `&questCompleteCount(7123,7124,7126,7127)` returns the number of given quests which have status "complete"
There are three possible quest statuses:
* `inactive` means that the quest doesn't exist or has been marked as inactive
* `incomplete` means that there is an incomplete timer or incomplete kill count
* `complete` means that the quest is complete and can be turned in
There are equivalent automacro conditions which are …

eventMacro: add questStatus questInactiveCount questIncompleteCount, etc

---

src/Network/Send.pm
tables/servers.txt

iRO Restart doesn't work with just this, but at least `cryptKeys` should be an option in `servers.txt`.

add servers.txt option for cryptKeys

---

src/Network/Receive/ServerType0.pm
src/Network/Send/ServerType0.pm

Symptom, after a few relogs:
```
> reload shuffle.txt
Loading tables/iRO/Restart/shuffle.txt...
Loading tables/iRO/Restart/shuffle.txt...
Loading tables/iRO/Restart/shuffle.txt...
Loading tables/iRO/Restart/shuffle.txt...
Loading tables/iRO/Restart/shuffle.txt...
[more of the same...]
```
Note that due to the way this is implemented, and how and when the network objects are instantiated:
* `reload shuffle.txt` and `reload sync.txt` didn't (and don't) do anything useful
* `shuffle.txt` and `sync.txt` get reloaded every time we relog, which can be dangerous for devs testing old feature branches on a server which requires these files

fix memory leak with shuffle.txt and sync.txt upon relog

---

plugins/eventMacro/eventMacro/Automacro.pm
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/FileParser.pm
plugins/eventMacro/eventMacro/Runner.pm

Before, the only way to make call accept params is the call from inside a macro.
So you had to do something like this to get what you want:
```
automacro goSave {
ConfigKeyNot saveMap prontera 
call {
call saveIn "prontera" "100 100"
}
}
```
but with this update, the call of an automacro accepts directly the params, like this:
```
automacro goSave {
ConfigKeyNot saveMap prontera 
call saveIn "prontera" "100 100"
}
```
Obs: **macros cannot have spaces in name!!!!**
there shouldn't be even possible to add space in name, but its a feature not implemented yet.
i would like to thank **@Henrybk** for giving me tips to do this  and **@allanon** for made the call on macros to accept params in the first place, that piece of code was very useful to me.
Tested with this macro and working great:
``` …
```

make call on an automacro accept params

---

plugins/eventMacro/eventMacro/Automacro.pm
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/FileParser.pm
plugins/eventMacro/eventMacro/Runner.pm

when i've last implemented the parameters on an automacro call, a very serious bug appeared making every automacro that has a submacro that call another, to be ignored...
```
BaseLevel > 0
run-once 1
exclusive 1
call {
call anotherMacro
}
}
```
this automacro above do not run, it points out the error "parameter call duplicate"
this pull request fix this error 
move from $paramN to an array, which is much more natural
now instead of using:
`$.param1` or `$.param2`
you use `$.param[0]` or `$.param[1]`

fix call bug, moved $.param to array

---

plugins/item_weight_recorder/item_weight_recorder.pl

Spamming two types of pots would change the weight of the second one to the weight of the first one, because the inventory and weight packets come in reverse order. This pull request ignores the second inventory change, which prevents the weight from changing.

item_weight_recorder: avoid false positive on item use

---

plugins/eventMacro/eventMacro/Condition/SimpleHookEvent.pm

Now we get all variables from hook in SimpleEventHook which basically supports all non implemented hooks in one go.
Tested like:
```
automacro test{
SimpleHookEvent zeny_change
call test
}
macro test{
[
log $.SimpleHookEventLast
log $.SimpleHookEventLastChange
log $.SimpleHookEventLastZeny
]
}
```
got 
> [Sep 12 10:04:45 2017.86] You lost 50 zeny.
> [Sep 12 10:04:45 2017.86] [eventMacro] Event of type 'hook', and of name 'zeny_change' activated automacro 'test', calling macro 'test '
> [Sep 12 10:04:45 2017.86] Item added to inventory: Rod [3] (20) x 1 - Weapon
> [Sep 12 10:04:45 2017.86] Buy completed.
> [Sep 12 10:04:45 2017.86] [eventmacro log] SimpleHookEvent
> [Sep 12 10:04:46 2017.87] [eventmacro log] -50
> [Sep 12 10:04:47 2017.88] [eventmacro log] 59235

[eventMacro.pl] SimpleHookEvent get Hook Variables

---

plugins/eventMacro/eventMacro/Runner.pm

before this PR, when you type something like:
`$hash{value}++` or `$hash{value}--`
`@array[0]++` or `@array[0]--`
the value was not corretly updated, but with scalar variables works fine.
this PR fix the bug.

eventMacro fix bug on sub statment in Runner.pm

---

plugins/macro/Macro/Utilities.pm

I have found a problem with the latest "lastMatch$idx" variable not being updated if a macro triggers with an empty match, really tricky!, here are repro steps:
1) create anautomacro:
```
automacro bug {
party /^bug(\d+)?$/i
call {
$var = "foo"
if ($.lastMatch1 != "") {
$var = "bar"
}
log $var
}
}
```
2) trigger the automacro
2.1) chat (by party in this case) "bug"
2.2) chat (by party in this case) "bug1"
2.3) chat (by party in this case) "bug"
3) check console
**RESULT:**
```
[Party] DummyPlayerName : bug
[macro] automacro bug triggered.
[macro log] "foo"
[Narty] DummyPlayername : bug1
[macro] automacro bug triggered.
[macro log] "bar"
[Narty] DummyPlayername : bug
[macro] automacro bug triggered.
[macro log] "bar"
```
**EXPECTED**
```
[Party] DummyPlayername : bug
[macro] automacro bug …
```

fix for unmatched lastmatchs

---

src/Network/Send/kRO/RagexeRE_2016_01_06a.pm
src/Network/Send/kRO/RagexeRE_2016_02_03a.pm
src/Network/Send/kRO/RagexeRE_2016_12_28a.pm

fix storage_item_remove and storage_item_add
` 'v V' >   'a2 V'
`
i'm sry 
@alisonrag

fix storage_item_add and storage_item_remove   for sT 2016+

---

src/Network/Receive/bRO.pm
src/Network/XKore2.pm

XKore 2 clientAlive should only be true if DirectConnection is connected to map server
Fixes getting stuck on char selection if kore disconnects from map server (and xkore 2 doesn't) without spamming sync_received_characters

[XKore 2] clientAlive

---

src/AI/CoreLogic.pm

Introduced by #1154 
Before
```
Auto-skill on self: Envenenar Arma (lvl 6)
UseSkill - Created preparation subtask.
Skill Use on Location: 138, (, )  <<<<<<<<<<<<<<<-- Trying to use support skill on null location
UseSkill - Preparation subtask completed with success, waiting for cast to start...
Skill Use on Location: 138, (, ) <<<<<<<<<<<<<<<-- Trying to use support skill on null location
UseSkill - Timeout, recasting skill.
Skill Use on Location: 138, (, ) <<<<<<<<<<<<<<<-- Trying to use support skill on null location
UseSkill - Timeout, recasting skill.
UseSkill - Timeout, maximum tries reached.
Não foi possível usar a habilidade Envenenar Arma em 3 tentativas.
Received packet: 0110 Handler: skill_use_failed
Habilidade Envenenar Arma falhou: Pré-Requisito (erro 10)
Received packet: 0110 …
```

Fix bug in support skill use

---

src/Poseidon/Config.pm
src/Poseidon/poseidon.pl

Valid arguments:
```
--file
--ragnarokserver_ip
--ragnarokserver_port
--queryserver_ip
--queryserver_port
--server_type
--debug
```
* Command line arguments have priority over poseidon.txt.
* If any valid command line argument is passed (other than --file), the correspondent key in poseidon.txt will be skipped.
* If all valid command line arguments are passed (with or without --file), poseidon.txt (or the file passed) won't be loaded. In other words, a configuration file (poseidon.txt) is not mandatory

Add command line arguments support to Poseidon

---

src/Misc.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

Support skill_used_no_damage long VAX null amount
Avoids showing "Lv: 4294967295" on skills (i.e. Hiding)

skill_used_no_damage null amount

---

src/Commands.pm

Using storage get for item 0 without quantity yields an error
As reported by daviddorj

Fix storage get 0

---

plugins/eventMacro/eventMacro/Utilities.pm

these keywords now accept id of item and name, instead of just name:
```
&inventory()
&invamount()
&storage()
&storamount()
&cart()
&cartamount()
&InventoryType()
&shopamount()
```

eventMacro keywords change

---

src/Network/Receive/kRO/RagexeRE_2013_08_07a.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send/kRO/RagexeRE_2017_04_26d.pm

Client  Dec 23 2013
Issues #1394
You can use kRO_RagexeRE_2013_08_07a, but recvpacket must be Dec 23 2013.
```
[server?]
ip 45.77.45.251
port 6907
private 1
version 46
master_version 14
addTableFolders **you tables**
serverType kRO_RagexeRE_2013_08_07a
serverEncoding Western
charBlockSize 144
```

[Pserver]Fix recv for client 201311+

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

Sometimes we receive (or process?) party_users_info before party_join when logging in. This doesn't happen always, but when it does, it breaks Slave bots. This was noticed in bRO Thor
This is to prevent clearing info already in $char->{party}

Prevent party info loss

---

plugins/needs-review/xconf/trunk/xconf.pl

while it is decided if xconf will be merged to `Commands.pm` or not
fix this little bug, that when you use iconf or mconf  or pconf, and the `key` had utf8 characters, it crashes the openkore
by the way, this plugin needs update, it is not prepared to work with IDs on items_control.txt 
(in #1376 i've already updated)

xconf plugin bugfix

---

control/config.txt
tables/bRO/control-br/config.txt

Changes teleportAuto_useSkill default configuration to 1
teleportAuto_useSkill 3 (or 2, for that matter) is an exploit, mostly patched -- and detectable

[Default config] Stop using exploits to teleport

---

src/FileParsers.pm

Avoids parsing " # Green Potion" in `506 0 1 0 # Green Potion`, for instance, as an argument
Might be related to #1371 and [pt-br] http://openkorebrasil.org/index.php?/topic/4288-config-da-kafra
Or it might not

Skip comments in args in items_control.txt

---

openkore.pl
src/Translation.pm

Translation::initDefault(podir, locale) -> Translation::initDefault(locale)
$_translation is now a Translation object
Translation::initDefault no longer leaves a filehandle hanging when kore terminates (DESTROY is called)
Add translatef, for plugin usage, similar to TF

Translation module changes

---

control/config.txt
control/timeouts.txt
src/AI/CoreLogic.pm
tables/bRO/control-br/config.txt
tables/bRO/control-br/timeouts.txt

Allows opening storage with a consumable item, like [Kafra Card](http://ratemyserver.net/index.php?page=item_db&item_id=12211)
Usage:
```
storageAuto_useItem 1
storageAuto_useItem_item Kafra Card
```
* If you run out of Kafra Cards and storageAuto_npc is set, kore will do execute the normal storageAuto sequence. If storageAuto_npc is not set, storageAuto will be disabled.
* storageAuto_useChatCommand has priority over storageAuto_useItem.

Add storageAuto_useItem

---

src/Commands.pm
src/Globals.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/RagexeRE_2016_12_07e.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send.pm
src/Network/Send/ServerType0.pm
src/Network/Send/kRO/RagexeRE_2016_12_07e.pm
src/Network/Send/kRO/Sakexe_0.pm
src/functions.pl

* **Related Issue:** #1349 
* **Descriptions:**
* Added command `refineui select [item_index]`
* Added command `refineui refine [item_index] [material_id] [catalyst_toggle]`
* References:
* https://github.com/rathena/rathena/pull/2494
* https://github.com/cydh/rathena/pull/9 (I use this for testing)
* Tested using rAthena's PACKETVER 20161207
PS:
* Allow edits from maintainers is checked.
* Suggestions for improvement are welcome, but don't expect I reply it quickly.
* or, devs can **merge** this to main repo and maintain it themselves (do not copy-paste, it's different!)

Added support for Refine UI

---

src/InventoryList.pm

buyAuto is case insensitive, but if we try to buy, for instance, 'Yellow potion' and the store sells 'Yellow Potion' (mind the uppercase and lowercase 'P'), the item is bought -- but we enter a loop, because we still don't have enough of 'Yellow potion', even though we have enough of 'Yellow Potion'. This commit fixes that behaviour.
Also fixes #1587 
Expected behaviour (with this commit applied):
What happens without this commit. Notice we don't actually buy the stuff, but we keep trying.

Fix loop on buyAuto

---

src/Actor/Item.pm

Using <slot> [NONE] in equipAuto now unequips that slot.
For example:
```
equipAuto {
midHead [NONE]
onAction sitAuto
}
```
Unequips whatever is equipped in midHead when sitAuto.

Add [NONE] to equipAuto

---

plugins/eventMacro/eventMacro/FileParser.pm
plugins/macro/Macro/Automacro.pm
plugins/macro/Macro/Parser.pm

The encoding pragma was deprecated in perl 5.18 and is no longer allowed in perl 5.26
Fixes #1388 and #855
Won't cause the same problem as #856, described in #863 -- this is implemented with perlIO layer, instead of the open pragma

 Remove encoding pragma in plugins loaded by default

---

src/Task/CalcMapRoute.pm

Caused by #896
Behavior uknown for multiple targets, not fatal unless position zero is undef or not a hash, which shouldn't happen
Before:
After:
1. Without coords
2. With coords

CANNOT_CALCULATE_ROUTE message for single target

---

src/Misc.pm

whenPartyMembersNear : range of party members nearby necessary to trigger this block
whenPartyMembersNearDist : range of distance those party members have to be to trigger this block. If unset, defaults to less than removeActorWithDistance or clientSight or 15 (in this order)
Both are self coditions, therefore can be used in partySkill, useSelfSkill, useSelf_item, buyAuto, etc.
Allows users to do things like this:
Use Clementia if there's more than two party members nearby
Use Blessing otherwise
```
partySkill Clementia {
target_whenStatusInactive Blessing
whenPartyMembersNear > 2
whenPartyMembersNearDist <= 7
}
partySkill Blessing {
target_whenStatusInactive Blessing
whenPartyMembersNear 2
}
```

Add whenPartyMembersNear and whenPartyMembersNearDist

---

plugins/eventMacro/eventMacro/Utilities.pm

getQuestStatus reported complete on newly added quests.
Since there's no goal property in a newly added quest, getQuestStatus subroutine always returns complete on such quests until relogging. This patch addresses this bug.

plugin: eventMacro: fix issue in getQuestStatus

---

plugins/xConf/xConf.pl

getControlFilename returns `'\'` as a path separator on Windows, parseReload uses regex to reload files. Passing an unescaped `'\'` is very bad and causes control files not to reload on Windows systems.

[xConf] Fix file reloading by regex in Windows systems

---

control/config.txt
src/AI/CoreLogic.pm
tables/bRO/control-br/config.txt

This PR do:
* if the target is cart or inventory, will check weight of each item (and only if has information about weight)
* calc how much of the current item the bot can get, if the amount is bigger that he can carry, will get just enough to stay with 99% weight (or 100%)
```
-- Não utilizável --
13   Sangue de Lobo x 45
14   Gelo x 3507 #this is the item will get
16   Pedra x 1
17   Ombreira x 2
Capacidade: 27/600
--------------------------------------------------
storage get 14 #command to get the item
Amount of item Gelo (14) is more that you can carry, getting the maximum possible (2099)
Item adicionado ao inventário: Gelo (23) x 2099 - Event
Você está agora: Owg 90%
Item retirado do armazém: Gelo (14) x 2099
```

checking weight when get item via console commands

---

plugins/eventMacro/eventMacro/Runner.pm

this closes #1695 
```perl
[eventMacro] Conditions met for automacro 'test', calling macro 'tempMacro3'
[eventmacro log] $i is 0, then @group should be a:b:c
[eventmacro log] $group[0] is a
[eventmacro log] $group[1] is b
[eventmacro log] $group[2] is c
[eventmacro log] $i is 1, then @group should be 1:2:3
[eventmacro log] $group[0] is 1
[eventmacro log] $group[1] is 2
[eventmacro log] $group[2] is 3
[eventmacro log] $i is 2, then @group should be ma:me:mi:mo
[eventmacro log] $group[0] is ma
[eventmacro log] $group[1] is me
[eventmacro log] $group[2] is mi
[eventmacro log] $group[3] is mo
[eventmacro log] $i is 3, then @group should be sim:griim:fin
[eventmacro log] $group[0] is sim
[eventmacro log] $group[1] is griim
[eventmacro log] $group[2] is fin
[eventmacro log] done loop
eventMacro …
```

[eventMacro] &split fix (support accessed array and hash)

---

src/Network/Receive.pm

Entity save type to check when send to client in xkore 2
```
if ($char->{spirits}) {
my $switch = "01D0";
if($char->{spiritsType} eq "coin") { $switch = "01E1"; }
if($char->{spiritsType} eq "amulet") { $switch = "08CF"; }
my $type = 0;
if(exists $char->{amuletType}) { $type = $char->{amuletType}; }
$data = $self->{recvPacketParser}->reconstruct({
switch => $switch,
sourceID => $char->{ID},
entity => $char->{spirits},
type => $type,
}) ;
$client->send($data);
}
```

Entity save type

---

src/Network/Receive.pm
src/Network/Receive/Zero.pm
src/Network/Receive/cRO.pm
src/Network/Receive/kRO/Sakexe_0.pm

Update in Account server info parse to support new packets (kRO Zero, cRO, Privates 201703+)
bRO 0069 packet:
cRO 0AC9 packet:
kRO Zero 0AC5 packet:

Account server info parse update

---

src/Commands.pm

Unless provided, the target coordinates used will be our standing position
Valid examples (with Storm Gust - ID 89):
* Using max lvl available on our current position (behaves like `ss 89`)
`sl 89`
* Using lvl 3 on our current position (behaves like `ss 89 3`)
`sl 89 3`
* Using max lvl available on coords 30 75
`sl 89 30 75`
* Using lvl 6 on coords 30 75
`sl 89 30 75 6`

Make coords optional in sl command

---

plugins/eventMacro/eventMacro/Core.pm

Reported by Kotsu
```
automacro crash {
BaseLevel > 0
call {
if ($var == 0) {
log I won't close this if
}
}
```
Run openkore and use command ```reload eventMacros.txt```

Fix eventmacro crash on reload with unclosed blocks

---

src/AI/CoreLogic.pm
src/Network/Receive.pm

I dont know why, but previouly openkore was comparing name get from actor :
code:
`next if (($char->{party}{users}{$ID} ne $playersList->getByID($ID)) && !$config{"partySkill_$i"."_notPartyOnly"});`
the following code:
```
$char->{party}{users}{$ID} :
```
Result:  Party sctnightcore 
and
```
$playersList->getByID($ID)):
```
Result:  Player sctnightcore (0)
this pull fix this:
thi fixes #1896

fix bug in party skill caused in #1884

---

plugins/eventMacro/eventMacro/Condition/Zeny.pm

i just made a deal right now, and when the deal was over, eventMacro didnt checked the zeny, and the automacro did not acttivated because of that

[eventMacro] add one more hook to Zeny condition

---

src/Network/Send.pm
src/Network/Send/ServerType0.pm
src/Network/Send/kRO/Sakexe_0.pm

```
'00AB' => ['send_unequip_item', 'v', [qw(Index)]],
'00BB' => ['send_add_status_point', 'v2', [qw(statusID Amount)]],
'0112' => ['send_add_skill_point', 'v', [qw(skillID)]],
'0130' => ['send_entering_vending', 'V', [qw(accountID)]],
'02BA' => ['send_shortcut_key_change', 'v c V v', [qw(index isSkill ID count)]],
```
tested in iRO and bRO

packets send update

---

plugins/vendingLog/vendingLog.pl

vendingLog_dateFormat 0 -> `y-m-d`
vendingLog_dateFormat 1 -> `h:m:s`
vendingLog_dateFormat 2 -> `Mon d h:m:s y`
Functionality stays unchanged.

[vendingLog] Fix date-format key meaning

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

```
+/// Notifies the client of a position change to coordinates on given map, which is on another map-server.
+/// 0092 <map name>.16B <x>.W <y>.W <ip>.L <port>.W (ZC_NPCACK_SERVERMOVE)
+/// 0ac7 <map name>.16B <x>.W <y>.W <ip>.L <port>.W <unknown>.128B (ZC_NPCACK_SERVERMOVE2)
```

ZC_NPCACK_SERVERMOVE2

---

plugins/raiseStat/raiseStat.pl

curretly, the plugin only parses the value if it is on this format
`10 str, 60 int`
(first the value, after the stat which will be leveled)
this PR proposes that user are free to use
`str 10, int 60` if he want (or if he didn't noticed he placed wrong)
this will not affect the function of plugin, will not make anything slower at all

make raiseStat parse stats correctly even if is on inverse position

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm

After last update client now is sending 0447 - blocking_play_cancel
checked with xKore 3

[cRO] Request unfreeze

---

plugins/eventMacro/eventMacro/Runner.pm

Also, there is a part that inserts quotation marks where is needed, and remove the quotation where they are not  needed
and is still retrocompatible
macro to test it:
```perl
exclusive 1
run-once 1
BaseLevel > 0
priority -5555
macro_delay .5
call {
log calling sub printHash
%hashNumbers = (one => 1, two => 2, three => 3)
printHash(%hashNumbers)
log calling sub printArray
@arrNumbers = (1,2,3,4,5)
printArray(@arrNumbers)
$foo = bar
log calling sub printMixedArr
printMixedArr ($foo, "$hashNumbers{three}", "$arrNumbers[0]","@arrNumbers")
log calling sub printMixedHash
printMixedHash("$foo", "$hashNumbers{three}", "$arrNumbers[0]",%hashNumbers)
}
}
sub printHash {
my (%hash) = @_;
foreach (keys %hash) {
warning "key: $_, value: $hash{$_}\n";
}
}
sub printArray {
my (@array) = …
```

[eventMacro] support passing as argument for a sub a entire array/hash

---

plugins/eventMacro/eventMacro/Runner.pm

@Henrybk said to me:
you are using eval 3 times ( you could do once and copy ) and you create two variables `@testArray ` and `%testHash` but only uses one.
Additionally, added support to when a person return a reference to a scalar variable (difficult but possible)

[eventMacro] Changes requested by henry bk

---

plugins/eventMacro/eventMacro/Condition/IsInCoordinate.pm

MultipleValidatorState and MultipleValidatorEvent are a horrible mess, we should get rid of them.
This is (initially) a rewrite of the condition IsInCoordinate so it won't use MultipleValidatorState anymore.
It now uses instead the base eventMacro::Condition, this is much safer and cleaner.
This condition now also supports variables.
Requires further testing.

Rewrite eventmacro multivalidator conditions

---

plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

Unfortunaly i have found a serius bug on this Pull Request
The problem is the `&config()` return an empty string if it's false
so, if the statment is something like `&config(skillsAddAuto) != 1` and the config is false, then the code will accuse of a non-existence of first argument
so i must first solve this...

Revert "[eventMacro]improve statments of eventMacro"

---

plugins/eventMacro/eventMacro.pl
plugins/eventMacro/eventMacro/Core.pm

This fixes the crash that would occur when using condition BaseActorNearDist and reloading while it was on 'true' state.
Before:
[Error](https://i.gyazo.com/70d307fb7309f82061178e3861357058.png)
After:
[Working](https://i.gyazo.com/d40daa6284ddcbcbc3342005b56ca03b.png)
Tested using this macro:
`automacro dist {
exclusive 1
timeout 5
NpcNearDist /kafra/i <= 4
call {
log Heeeey, it works, text
}
}`

[eventMacro] Fix crash on reload

---

plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/FileParser.pm

This make things easier to notice possible erros, specially when using very big macros with a lot of subs, that end up mixing macro errors with loadings
as you can see, is much more easy to notice error

[eventMacro] change from warning to error on fileParsing time

---

src/Task/TalkNPC.pm

Under some game circustances you won't initialize a conversation to a NPC after clicking to talk to it, like on the KVM NPCs (where it randomly closes your quest log and you need to click on it again to start the talk).
In these cenarios Openkore fails to handle the situation and start an infinite loop; since it wont receive a response from the NPC neither a chat box, the conversation will reaches the timeout and openkore will call $self->cancelTalk, but $ai_v{'npc_talk'}{'talk'} turns to be empty and the sub cancelTalk can't deal with empty values on it.
This extra elsif will deal with empty values for $ai_v{'npc_talk'}{'talk'}, fixing this issue.

Fix for unsucessful initialized talks to NPCs

---

src/AI/CoreLogic.pm
src/Actor.pm

This bug was caused by randomWalk not being unstacked from queue when we stack an attack to the queue.

Fix issue #841: After kill kore move away from another monsters

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
tables/servers.txt

Flags a server that uses the player blocking system.
As more and more servers start to use this system, adding them to the grep list will become unpractical and the search for a match quite slow

Add servers.txt option blockingPlayerCancel

---

plugins/eventMacro/eventMacro/Runner.pm

switch blocks was not working as expected, and they were not working because of this
this solves the problem
```perl
macro test {                           #macro begin
log begin                          #line index 00
$i = 1                             #line index 01
if (5 > 7) {                       #line index 02
log "hey!"                     #line index 03
} elsif ( 1 = 1) {                 #line index 04
log "men..."                   #line index 05
} else {                           #line index 06
log "woman..."                 #line index 07
}                                  #line index 08
switch ($i) {                      #line index 09
case (= 1) {                   #line index 10
log "case 1"               #line index 11
}                              #line index 12
case (= …
```

[eventMacro] fix switch block

---

src/Network/Send.pm
src/Network/Send/ServerType0.pm
src/Network/Send/kRO/RagexeRE_2008_08_27a.pm
src/Network/Send/kRO/RagexeRE_2010_11_24a.pm
src/Network/Send/kRO/RagexeRE_2011_10_05a.pm
src/Network/Send/kRO/RagexeRE_2012_03_07f.pm
src/Network/Send/kRO/RagexeRE_2012_05_15a.pm
src/Network/Send/kRO/RagexeRE_2012_06_18a.pm
src/Network/Send/kRO/RagexeRE_2013_05_15a.pm
src/Network/Send/kRO/Sakexe_0.pm
src/Network/Send/kRO/Sakexe_2004_07_05a.pm
src/Network/Send/kRO/Sakexe_2004_07_13a.pm
src/Network/Send/kRO/Sakexe_2004_07_26a.pm
src/Network/Send/kRO/Sakexe_2004_08_09a.pm
src/Network/Send/kRO/Sakexe_2004_09_06a.pm
src/Network/Send/kRO/Sakexe_2004_09_20a.pm
src/Network/Send/kRO/Sakexe_2004_10_05a.pm
src/Network/Send/kRO/Sakexe_2004_10_25a.pm
src/Network/Send/kRO/Sakexe_2004_11_29a.pm
src/Network/Send/kRO/Sakexe_2005_01_10b.pm
src/Network/Send/kRO/Sakexe_2005_05_09a.pm
src/Network/Send/kRO/Sakexe_2005_06_28a.pm
src/Network/Send/kRO/Sakexe_2005_07_18a.pm
src/Network/Send/kRO/Sakexe_2005_07_19b.pm
src/Network/Send/kRO/Sakexe_2006_03_27a.pm
src/Network/Send/kRO/Sakexe_2007_01_08a.pm
src/Network/Send/kRO/Sakexe_2007_02_12a.pm

Add 0190 and 0367 as skill_use_location_text
Cleanup skill_use_location_text shuffles in kRO servertypes
sendSkillUseLocInfo merged into Network::Send
sendSkillUseLocInfo now uses Network::PacketParser::reconstruct

Cleanup CZ_USE_SKILL_TOGROUND_WITHTALKBOX and CZ_USE_SKILL_TOGROUND_WITHTALKBOX2

---

src/Network/Receive/ServerType0.pm

removing "x2" from sage_autospell packet

---

src/Network/Receive.pm

Workaround some npcs that have items appearing more than once in their store list, for example the Trader at `moc_ruins 90 149` sells only bananas, but 6 times
Usually, `$Actor::Item->{ID}` is equal to `$Actor::Item->{nameID}` - that WILL crash kore in the event described above (as seen in #2345)
This workaround causes `$Actor::Item->{ID}` to be equal to `$Actor::Item->{binID}` and, therefore, never overlap

Fix assertion fail in some NPC stores

---

plugins/eventMacro/eventMacro/Condition/IsNotInMapAndCoordinate.pm

Resuming, this is basiclly the code from IsInMapAndCoordinate,with the inverse result on the end
and you can't put more than one coordinate/map
`IsNotInMapAndCoordinate prontera 150 150, payon, geffen 130 121` is wrong
can have only 1 member , like `IsNotInMapAndCoordinate prontera 150 150`

[eventMacro] New condition: IsNotInMapAndCoordinate

---

plugins/eventMacro/eventMacro/Condition/ConfigKeyNotExist.pm

for now i have only managed to completly edit and test this condition.
`ConfigKey` and `ConfigKeyNot` is on test yet
now this condition support labels.
automacro used to test it:
```perl
automacro createNewBlock_buyAuto {
ConfigKeyNotExist buyPot.block
exclusive 1
timeout 5
call {
createNewBlock_buyAuto()
}
}
sub createNewBlock_buyAuto {
open (my $fh, '>>:encoding(UTF-8)', Settings::getControlFilename('config.txt'));
print $fh "\n";
print $fh "buyAuto {\n";
print $fh "	maxAmount\n";
print $fh "	zeny\n";
print $fh "	npc\n";
print $fh "	disabled\n";
print $fh "	label buyPot\n";
print $fh "}\n";
close($fh);
Commands::run("reload config");
}
```
@Henrybk give your veredict

[eventMacro] ConfigKeyNotExist label support

---

src/Commands.pm
src/Network/Send.pm

* Since $item->{index} was removed, this part wasn't changed = fail on usage
* Tested this on idRO Renewal

Change material fixes

---

plugins/eventMacro/eventMacro/Runner.pm

Before, if you want to show a log with red colors you would have to do this:
```perl
do eval Log::error "This is an error message\n"
```
now you can simply do this
`error This is an error message`
automacro that it can be used to test:
```
BaseLevel > 0
exclusive 1
run-once 1
call {
log this is a normal log message
warning this is a warning message
error this is a error message
}
}
```
Output:

add warning log and error log to eventMacro

---

tables/bRO/portals.txt

before:
bot try endlessly to walk on the exact same cell of the npc, and never leave the town
now:
working :+1:

fix teleport from brasilis to alberta

---

plugins/eventMacro/eventMacro/Condition/SystemMsg.pm

In some cases, npcs send broadcasts on the map, like on quests or challenges
Some times it is used the local_broadcast, but sometimes are used the system broadcast (yelllow sentence on top of game)
This condition is to when system broadcast is used
[](url)
Tested on [izlude Arena](https://browiki.org/wiki/Arena_de_Batalha)

[eventMacro] new condition: SystemMsg

---

plugins/eventMacro/eventMacro/Condition/IsInCoordinate.pm
plugins/eventMacro/eventMacro/Condition/IsNotInCoordinate.pm
plugins/eventMacro/eventMacro/Condition/IsNotInMapAndCoordinate.pm
plugins/eventMacro/eventMacro/Condition/NotInMap.pm
plugins/eventMacro/eventMacro/Conditiontypes/ListConditionState.pm
plugins/eventMacro/eventMacro/Validator/ListMemberCheck.pm

**IsInCoordinate** and **IsNotInMapAndCoordinate** now are childs of **IsInMapAndCoordinate**
**IsInCoordinate** now have only the `sub parse_syntax` , the change is to accept only coordinates
**IsNotInMapAndCoordinate** now have only the `sub check_location` the change is to be true only if you not in any of the specified maps/coodinates. So, if the condition is like this: `IsNotInMapAndCoordinate prontera, morocc, geffen, aldebaran, yuno` , the condition will only be true if you not in any of these maps
(but i wonder if it is correct to keep it like this)
**NotInMap** Same of last condition

[eventMacro]Improve reuse of code

---

plugins/eventMacro/eventMacro/Runner.pm

for some random reason you were forced to put a space or else it would give this error:
```perl
[eventMacro] Script of the line 'if(&invamount(Strawberry) >=1){' 
[eventMacro] Error message 'Unrecognized --> if <-- Sub-Routine'
```

[eventMacro] space between if and "(" not required anymore

---

tables/iRO/official/portals.txt

Prontera kafra lady is not at 29 207 anymore.
Her location is 35 208, check the following error log.
```
Location: Prontera City, Capitol of Rune-Midgarts (prontera) : (baseName: prontera) : 40, 196
NPC Exists: Kafra Employee (35, 208) (ID 51166) - (0)
Player Merchance (5) uses effect: Magiccircle
Portal Exists: Unknown #50844 (25, 203) - (0)
NPC Exists: Eden Teleport Officer#3 (38, 212) (ID 51823) - (2)
Failed to teleport using NPC at prontera (29,207).
NPC error: Could not find an NPC at location (29,207)..
Retrying for the 1 time...
Failed to teleport using NPC at prontera (29,207).
NPC error: Could not find an NPC at location (29,207)..
Retrying for the 2 time...
Failed to teleport using NPC at prontera (29,207).
NPC error: Could not find an NPC at location (29,207)..
Retrying for the …
```

iRO: Update prontera Kafra warp position

---

src/Network/Send/idRO.pm

Fixed cannot delete character on idRO, it's using `098F` packet handle for `char_delete2_accept`
---
it was like that since #97

Cerroected char_delete2_accept packet

---

plugins/eventMacro/eventMacro/Condition/VarValue.pm

Very useful to several purposes
Tested and working properly
```
automacro testCondition {
VarValue $keyvar1{$var} a, $keyvar2 b, $keyvar1 c, $keyvar1 d
run-once 1
call {
log condition VarValue working
log Var is '$.VarValueLastVar'
log Value is '$.VarValueLastValue'
log Index is '$.VarValueLastMemberIndex'
}
}
automacro defineVar {
BaseLevel > 0
run-once 1
exclusive 1
call {
$var = a
$keyvar1{$var} = a
log Var defined
}
}
```

[eventMacro] new condition: VarValue

---

tables/bRO/portals.txt
tables/portals.txt

Added:
Updated:
Known bugs:
- For some reason openkore unable to calculate route between `verus04` & `ver_tunn`

Portals Update - New World / Verus

---

src/AI/CoreLogic.pm
src/Commands.pm

* i think that variable `$target_item` have a very bad name (i've didn't think too much) and i'm looking for some tip to give a better name.
that variable store the item object on the target inventory
* Also, if i use `$row->{item}`, shows the name of item along with it's index. If i use `$row->{item}->name` the name show without the index of it
Which one you guys think is better?
I removed a little bit of repetitive code on Commands.pm
**Thanks to @lututui for provided me a better sentence to use on error message**

Make a check for when have more than 30000 of same item

---

src/FileParsers.pm

Fixes incorrect parsing in most control files (as described by #2518)
| File | Stripped |
|---|---|
| arrowcraft.txt | Yes |
| avoid.txt | No |
| buyer_shop.txt | Yes* |
| chat_resp.txt | No |
| config.txt | No** |
| consolecolors.txt | No |
| items_control.txt | Yes |
| mon_control.txt | Yes |
| overallAuth.txt | No |
| pickupitems.txt | Yes |
| poseidon.txt | No |
| priority.txt | Yes |
| responses.txt | No |
| routeweights.txt | Yes |
| shop.txt | Yes* |
| sys.txt | No |
| timeouts.txt | Yes |
*Except for shop titles
**User warned, not strippable due to player names

Strip mid-line comments in most control files

---

control/config.txt

in my opinion, if poseidon is a built-in tool on openkore, then we should let the config built-in on config.txt too
but since only 1 server (that i know) will use this config, make disabled by default

add gameGuard 0 line in config.txt

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

* Update on vender_items_list to avoid manual byte skip.
* Merge vender_items_list.
tested in iRO and local server (rAthena based)

[ Receive ] Update and Merge vender_items_list

---

src/Network/Receive.pm

last time i updated the vender function, i doesn't checked where venderID is used, so i removed. 
now i'm giving back so some functions will work again
as reported here:
http://openkorebrasil.org/index.php?/topic/5289-n%C3%A3o-estou-conseguindo-comprar-itens-de-mercadores-comando-vender/
and here:
http://openkorebrasil.org/index.php?/topic/5285-atualização-08-01-2019/?p=41392

[Receive] fix missing venderID

---

src/Misc.pm

inParty triggers whenever we're in a party
notInParty triggers whenever we're not in a party
Test blocks:
Results:

Add inParty and notInParty self conditions

---

src/Commands.pm
src/Network/Receive.pm

1. We should not send a package 'party_leader' if we are already party leader
2. In the 'party_leader' function, we must designate the party leader at the end of the function. Otherwise, an error occurs when the party leader re-designates himself as the leader.

fix party leader

---

src/Commands.pm

now the command will not work if ai_canOpenStorage not checked (Very low level of basic skills or not enough zeny)

fix cmdAutoStorage

---

control/config.txt
src/Network/Receive.pm

* Added `/s` for system chat regex so can be match with newline character. In some cases, the padded chars can be newline and will ignores all regex in ifs
* Uncommented `logLocalBroadcast` config in `sub local_broadcast`

System Chat & Local Broadcast

---

plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

it turns out that `if ($keyword ne qw(nick push unshift pop shift delete exists defined split keys values)) {` doesn't work, bad syntax 
so instead, now it uses grep, much more clean than old one

[eventMacro]Fix syntax

---

src/Commands.pm

Right now, the help command cannot retrieve scalar info from commands registered through Commands::register, such as plugin commands

Fix help for commands added through Commands::register

---

src/Network/Receive.pm

hook "search_store" was called everytime with same content
before:
after:

[Receive.pm] fix missing lenght in search_store_result

---

src/Network/Receive.pm

in some cases server send to us close conversation packet after the buy/sell list.
current openkore is destroying the task and is not possible to buy/sell
before:
after this pull:
this pull fixes #2759 
this pull fixes #1682

[talknpc] fix buy item after npc close conversation

---

src/Task/TalkNPC.pm

When a burrowed npc auto starts a conversation with a player, and the server requires a npc_talk_cancel, openkore twill not be able to send it because Task::TalkNPC::findTarget won't find the npc because it is burrowed. This fixes it.

Fix for burrowed npc autotalk

---

control/config.txt
src/AI/CoreLogic.pm

Problem:
If getAuto is set to get a non-stackable item and the diference between the minAmount and maxAmount is greater than 1 openkore will try to get more than 1 of the item at the same time. This is not possible. In some servers it will just not work, on others it will disconnect the char, in some it may even get you banned.
Proof:
config:
result:
Solution:
I added batchSize logic from buyAuto to getAuto, it should now work if properly set up.
Proof:
config:
result:
Tested on RMS renewall test server.

Add batchSize to getAuto logic

---

plugins/eventMacro/eventMacro/FileParser.pm

This changes the usual name of an automacro call block from
`tempMacro0`
to
`automacro_{automacro name}_call_block`

Change automacro call block name

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

This pull request solves #2822 request:
- add 08B3 'show_script' in Sakexe
- move 'show_script' in Receive.pm
- add new Hook 'show_script'
**Before this PR:**
> Packet Parser: Unknown switch: 08B3
**After:**

Update packet 08B3

---

plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/Runner.pm

if i use this automacro, then the OpeKore does not swear on syntax `orphan`:
```
disabled 0
JobID 0
run-once 1
orphan terminateZZZ
call {
log test
}
}
```
After this patch we get an error:
`[eventMacro] Ignoring automacro 'test' (orphan parameter should be 'terminate', 'terminate_last_call', 'reregister' or 'reregister_safe'. Given value: 'terminateZZZ')`
Maybe we should do it with other options too?

fix eventMacro 'orphan' parameter

---

src/Misc.pm

Sometimes the server sends the item_removed packet after teleport, but after teleport openkore has already cleared the list of items.
this currently causes an openkore error causing the user to close and reopen the software.
this fixes #2458

[FIX] avoid crash when no item

---

src/Commands.pm

cmdMove lets the user start Task::MapRoute on an obviously impossible trajectory, either because the destination is not walkable or because it is off the map. These checks fix that.

Add sanity check on cmdmove

---

src/Commands.pm

On #2877 I added a bug where you tried to move to a map without specifying coordinates then isOffMap and isWalkable would be called with empty values. This fixes that.

Only check coordinates if x and y are defined in cmdMove

---

src/Misc.pm
src/Network/Receive.pm
src/Network/Receive/bRO.pm
src/Network/Send.pm
src/Network/Send/bRO.pm

since kRO 2018-08-29, bRO 2019-08-20 and tRO 20-06-2019 those servers use 4 bytes in itemID
missing add in servertype kRO_2018_08_29 (this servertype doesn't exist yet)

Changes in item id lenght

---

src/Misc.pm

The idea here is:
- show message on console `Trying to set up shop...` before the `sendOpenShop()`, since it didn't happen yet;
- define $shopstarted to 1 BEFORE calling hook, because since it was defining after, any plugin that was hooking on it was getting the old value instead of the updated value
the rest keep the same

reorder a few lines from sub openShop

---

src/Network/Receive.pm

if you use xKore 1 and select chars in highests slots, openkore is not able to define the correct char data.
this pull fixes this

[xKore 1] workaround to recognize the right char data

---

src/Task/Move.pm

Sometimes openkore will receive a character_moves packet during a Task::Move which is from a previous Task::Move, this causes the current Task to be ended. This check ensures the Task only ends when it receives the move packet of the same coordinates it sent.
Exemple:
In this picture we receive a movement packet to the cell 204 188, but the current Task::Move and the last move packet sent by it have has the destination 208 188.
In this exemple already with this PR changes Task::Move didn't end after the first character_moves packet because it didn't have the right destination coordinates, which would would happened without this change.

added destination check to Task::Move

---

control/timeouts.txt
src/AI/CoreLogic.pm

sometimes openkore try to get or add item to storage faster then server send the item list to openkore, so sometimes server disconnect us
this pull fixe this

[CoreLogic] autostorage wait before action

---

src/Network/Receive.pm

As the title states once you change maps in RMS restart the homunculus actor won't be destroyed because a reference to it will be kept in `$char->{homunculus}`, but `$char->{slaves}` is always cleared in map changes, which causes the homunculus to be added again in `AI::SlaveManager` via `AI::SlaveManager::addSlave`.
The problem happens when in `AI::SlaveManager::addSlave` the class of the homunculus is changed from `Actor::Slave::Homunculus` to `AI::Slave::Homunculus`. If the actor is then added again without being deleted first its class will actually be `Actor::Slave::Homunculus`, preventing it from being identified as a homunculus, and being added as a `AI::Slave`.

Fix homunculus map change in RMS server

---

control/timeouts.txt
src/AI/Slave.pm
src/AI/SlaveManager.pm

At the moment `AI::Slave` uses a single timeout key for all slaves attacks, this makes it so that if you have a homunculus and a mercenary at the same time they won't be able to attack at the same time. This PR fixes that and also adds the missing timeouts.

Fixed homunculus and mercenary timeouts

---

src/Interface/Wx.pm

Menu "Info" -> "Experience Report" and "View" -> "Experience Report" do the same thing
Menu "Info" -> "Experience Report" should print text to the console

[WX] fix menu "Experience Report"

---

control/config.txt
control/timeouts.txt
src/AI.pm
src/AI/Slave.pm
src/AI/SlaveManager.pm
src/Actor.pm
src/Commands.pm
src/Network/Receive.pm
src/Network/Send.pm
src/Network/Send/ServerType21.pm
src/Network/Send/ServerType8.pm

This PR:
1 - adds a few timeouts for the slaves.
2 - changes most (I believe all) of the wrong messages in the slave AI referring slaves as homunculus.
3 - adds a new sub for selecting the slave target based on the one used for the player.
4 - changed a few sub names to better reflect what they do.
5 - added a "teleport to master" logic to recall the slave when it gets lost.
6 - Fixes the merc and homun command, which did not work because of wrong class check
7 - Fixes the "move near homun if idle" logic which also did not work because of wrong class check

Slave AI cleaning

---

plugins/eventMacro/eventMacro.pl
plugins/eventMacro/eventMacro/Automacro.pm
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/Data.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/test/RunnerParseCommandTest.pm
plugins/eventMacro/test/RunnerStatementTest.pm

This new parameter defines if the macro should be interruptible by the automacro that called it.
exclusive 1: Cannot be interrupted by any automacro, self_interruptible does not matter.
exclusive 0 & self_interruptible 0: Cannot be interrupted by itself, can be interrupted by any other automacro.
exclusive 0 & self_interruptible 1: Can be interrupted by itself and by any other automacro.
Current master default behaviour: exclusive 0 & self_interruptible 1
New default behaviour with these changes: exclusive 0 & self_interruptible 0

Add self_interruptible automacro parameter

---

control/config.txt
src/AI/Attack.pm
src/AI/Slave.pm
src/Misc.pm

This PR is a rework of the runFromTarget logic, it also adds support for mercenary runFromTarget.
Most of the code is commented but the basic idea is that while the current code works, it does not specify the amount of distance you would like to keep from the target while also not being that smart.
This new code uses trigonometry to find the best cells to move.
Video of the current master code in action:
https://www.youtube.com/watch?v=f4wZ2xlpAgI
Video of the reworked logic in action:
https://www.youtube.com/watch?v=1oiesxS5EaM
Video of the reworked logic running in a mercenary:
https://www.youtube.com/watch?v=Ee99aKdcdsQ
```
runFromTarget_dist: The minimum distance to keep from target
runFromTarget_minStep: The minimum distance to try to move away from target
runFromTarget_maxStep: The …
```

Rework runFromTarget

---

src/Misc.pm

every time the `avoidList_talk` function is run, the name of the new player is added to the% avoid hash
Example:
```perl
#!/usr/bin/env perl
%avoid = ();
$avoid{Players}{"[GM]Example"}{disconnect_on_chat} = 0;
$avoid{ID}{"000001"}{disconnect_on_chat} = 3;
use Data::Dumper; print Dumper(%avoid);
print "====================\n";
$user = "zzzzzzzzzzzzzzzzzzzzzzzzzz";
if ($avoid{Players}{lc($user)}{disconnect_on_chat}) {
print "if true $user\n";
}
use Data::Dumper; print Dumper(%avoid);
```
this PR corrects this behavior

small fix avoid hash

---

control/avoid.txt
control/config.txt
src/Misc.pm

1. Added new mode for `avoidGM_near`
2. Changed reaction to avoidList, like avoidGM
Mode 1: `test3	1 1 0`
```
Disconnecting (69.197.167.236:5121)...disconnected
Player test3 (2000742) is nearby, teleport & disconnect for 10 seconds
```
Mode 2: `test3	1 0 0`
```
Disconnecting (69.197.167.236:5121)...disconnected
Player test3 (2000742) is nearby, disconnect for 10 seconds
```
Mode 3: `test3	0 1 0`
```
Player test3 (2000742) is nearby, teleporting
You are casting Teleport on yourself (Delay: 0ms)
You use Teleport on yourself (Lv: 1)
```
Mode 4: `test3	0 2 0`
```
Player test3 (2000742) is nearby, respawning
You are casting Teleport on yourself (Delay: 0ms)
You use Teleport on yourself (Lv: 2)
```
Mode 5: `test3	1 2 0`
```
Sending Teleport using Level 2
Disconnecting …
```

Change avoid gm and avoid list

---

src/Commands.pm

1) small fix for `plugin reload` command
warning output was added if you are trying to reload a non-existing plugin by its number
before:
```
plugin reload 666
...
<Nothing happens>
```
after:
```
plugin reload 666
Error in function 'plugin reload' (Reload Plugin)
The specified plugin do not exist.
```
----
2) small fix for `plugin unload` command
2.1) every time when a non-existent plugin is unloaded by its number, a false plugin was registered in the system
2.2) warning output was added if you are trying to unload a non-existing plugin by its name
before:
```
plugin
-------------------------- Currently loaded plugins ---------------------------
0   macro                allows usage of macros
-------------------------------------------------------------------------------
plugin unload …
```

Cmd plugin fix

---

src/Interface/Wx.pm
src/Interface/Wx/MapViewer.pm
tables/portals.txt

this patch fixes: #2429 and #2965:
- now function `parsePortals` uses global hash `%portals_lut`
- Warp NPCs are now cyan
Thanks @c4c1n6kr3m1

Wx npc portal

---

control/timeouts.txt
src/Network/ClientReceive.pm
src/Network/Receive.pm
src/Network/Receive/Sakray.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/ServerType15.pm
src/Network/Receive/ServerType19.pm
src/Network/Receive/ServerType20.pm
src/Network/Receive/Zero.pm
src/Network/Receive/kRO/Sakexe_0.pm

Using xKore 1 or 3 and depending on the type of device the OpenKore is running on, map load may take longer or less time.
So let the user choose the waiting time by himself

[AI] move cliendSuspend to timeouts

---

src/Network/Receive/Sakray.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/ServerType15.pm
src/Network/Receive/ServerType19.pm
src/Network/Receive/ServerType20.pm
src/Network/Receive/Zero.pm
src/Network/Receive/kRO/Sakexe_0.pm

1 - The in_game hook is used by many plugins, but it was not called when xKore mode was in use.
2 - initMapChangeVars was planned to be used in map_change and map_changed, was only called in map_change and in xKore 1 mode (map_loaded) 
https://github.com/OpenKore/openkore/blob/1fa428f249e5ce8caef2255eaa7ecb87a9fb6cfd/src/functions.pl#L612-L613

[Fix] move in_game hook and initMapChangeVars to where is needed

---

src/Misc.pm
src/Network/Receive.pm

Before openkore was stuck trying to request actor info from same clone, now dont query for clone infos and is working fine

[FIX] Avoid Info Request when Actor is Clone

---

src/FileParsers.pm
src/test/FileParsersTest.pm
src/test/items_control.txt

Hi.
FileParses failed to parse name in items_control.txt like "Unknown #502" because the "#" was regarded comment

fix: Parse item including '#'

---

src/AI/CoreLogic.pm

if u set the following condition or other auto teleport related conditions, openkore will be stuck in infinity looping when u are talking with NPC, or if u already have a teleport in AI queue
teleportAuto_allPlayers 1
this pull fix the infinity  looping

[FIX] Avoid looping while try to teleport

---

src/Network/Receive.pm

euRO seems to have stopped sending 'homunculus_property' after a map change, this makes it so now  openkore has to keep the information itself. This change makes it so homunculus_info won't delete the homunculus object after a map change if it still holds the same ID.
This introduces another problem, AI::SlaveManager::addSlave requires the actor type to be Actor::Slave::Homunculus, but after a map change it will have been changed to AI::Slave::Homunculus, so I also added a check to change it back to Actor::Slave::Homunculus.
Previous fix: #2907

Fix homunculus not getting stats after map change

---

src/Commands.pm
src/Network/Receive.pm

In these 2 places there was a typo in the jobID key. Fixed them.

Fix typo in Homunculus jobID

---

src/Network/Receive.pm

After the fix on #3112 another bug was introduced, the homunculus object is never really deleted, but kept in $char->{homunculus}, but on every mapchange $char->{slaves} is deleted and also $slavesList is cleared, this makes it so when the homunculus actor connects after the map change it is not found by actor_display (in Receive.pm) in either $slavesList or $char->{slaves}, so a new actor is created and added to $slavesList, but when homunculus_info is received the object in $char->{homunculus} is copied to $char->{slaves}. So in the end 2 incomplete copies of the homunculus object are kept separate, one in both $char->{slaves} and $char->{homunculus} and another in $slavesList.
This fix just adds a third check in actor_display to also check for the actor ID in $char->{homunculus}, …

Fix homunculus map change again

---

src/Commands.pm

1. The command `friend request name` - does not work and always returns an error:
```
friend request 4epT
Requesting 4epT to be your friend
Argument "\x{7a}\x{78}..." isn't numeric in array element at src/Commands.pm line 2565.
```
2. The user could have mistakenly written the following command: `friend pm 1 4epT` or `friend remove 4epT`. Then an error appears
```
friend pm 1 4epT
Argument "\x{31}\x{20}..." isn't numeric in numeric lt (<) at src/Commands.pm line 2597.```
This PR corrects the indicated errors.

fix "friend request name" command

---

src/Misc.pm
src/Task/TalkNPC.pm

As reported in IRC:
Openkore was trying to talk with a hidden NPC when 2 NPCs was in the same coordinates
log:
https://uploads.kiwiirc.com/files/af0676ff2209a306e88f5190df007602/pasted.txt
with this pull, the openkore avoid and dont talk with hidden NPC anymore

Avoid talk and query hidden Actors

---

src/FileParsers.pm

this fix comment parse in items_control (https://github.com/OpenKore/openkore/pull/3064#issuecomment-624922830)
before:
after:
tested with:
```
all 0 1 0 1 1 # test
505 0 1 0 # Blue Potion
506 0 1 0 1 1
```

[Fix] items_control parser

---

src/Network/Receive.pm

fixed no transition to the next line after the body of the letter and not showing Item count and Zeny, as reported here:
https://github.com/OpenKore/openkore/pull/3072#issuecomment-626248702
added content type as suggested here:
https://github.com/OpenKore/openkore/pull/3072#issuecomment-626323067
also updated openkore to show job name instead of job id after receive target info in rodex.
thanks @ya4ept for the report and @c4c1n6kr3m1 for the suggestion

[Fix] Rodex Content, Target Job and Type

---

src/AI/Slave.pm
src/Misc.pm

attackAuto_party does not work on the slaves AI because the damage tables (dmgToParty, dmgFromParty, etc) consider slaves as party members, this PR fixes that by checking for both the master and the other slaves in the damage tables and ignoring the party ones.

Fix slave attackauto party

---

control/timeouts.txt
src/AI/CoreLogic.pm
src/Actor.pm

add checkmonster to ai queue give attackauto time to find other monster beforeback to route again, this avoid openkore to lost main route and walk away from monsters then back to kill

[FIX] check for monster before try to back to route

---

src/Commands.pm

`drop 5-7` command triggers a warning:
```
drop 5-7
Argument "\x{35}\x{2d}..." isn't numeric in numeric lt (<) at src/Commands.pm line 2334
```
I changed the regex

fix drop command

---

src/AI/CoreLogic.pm
src/Commands.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send.pm
src/Network/Send/ServerType0.pm
src/Network/Send/kRO/Sakexe_0.pm

Console command `repair` - does not work:
1) after using skill "Weapon Repair" - item numbers are not displayed correctly:
```
ss 108
You are casting Repair Weapon on yourself (Delay: 0ms)
--------Repair List--------
☺  Dagger
---------------------------
```
2) when using the `repair 1` command, nothing happens:
```
repair 1
Item with index: 1 does either not exist in the 'Repair List' or the list is empty.
```
3) `repairAuto` config parameter works, but the message displays an incorrect item name
```
You use Repair Weapon on yourself (Lv: 1)
Inventory Item Removed: Iron (3) x 1
Successfully repaired Unknown #3.
```
This PR corrects the indicated errors.
I also added two new commands:
`repair` - show list of items available for repair
`repair cancel` - cancel repair item

fix `repair` command

---

control/config.txt
src/Misc.pm
src/Task/TalkNPC.pm

this fixes #3137
log:
```
[Jun 17 20:24:37 2020.54] AI set to manual mode
[Jun 17 20:24:47 2020.49] NPC Exists: Milestone#1-3 (264, 191) (ID 110010770) - (0)
[Jun 17 20:24:54 2020.40] Milestone#1-3: - There is writing on a big rock. -
[Jun 17 20:24:54 2020.61] NPC Milestone#1-3 (0): Type 'talk cont' to continue talking
[Jun 17 20:24:55 2020.58] Milestone#1-3: - Those who advance may get hurt but are brave of heart and those who move back will remain safe.
[Jun 17 20:24:55 2020.60] Milestone#1-3: If you are brave, then take a step forward. Otherwise, step back. -
[Jun 17 20:24:55 2020.62] NPC Milestone#1-3 (0): Type 'talk cont' to continue talking
[Jun 17 20:24:57 2020.15] ------ Responses (Milestone#1-3) -------
0  Step forward.
1  Stay.
2  Cancel Chat …
```

[fix] Add config key to avoid hidden actors

---

src/Network/Receive.pm

before all monster was displayed as UNKNOW until openkore send get info request, it was delaying some openkore actions
this pull fixes this
OBS: openkore still request for monster info

[Update] Use monster name given from server until get the monster info

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

removed "body_style" from packages 09DB (actor_moved), 09DC (actor_connected) and 09DD (actor_exists)
09DD dont have body_state
is used in kRO from 20131223 to 20150513
body_state implemented at >=20150513

fix 09DB, 09DC and 09DD packets

---

src/AI.pm

today when user insert the command `ai clear` a lot of variables are left in ai_v, openkore don't know what to do with these variabless, so clear these variables together with ai_queue is the better to avoid undesirable behavior

add ai_v to ai::clear

---

src/Network/Receive.pm

if user use sit command will trigger sitAuto_forcedBySitCommand, but if for some reason bot stand up (ai clear, monster attack, etc) this key will remain in the ai_v, this affect storage, sell, buy and route logic.
with this pull if bot stand up for some reason openkore delete this key.
this pull fixes #3188

fix sitAuto_forcedBySitCommand

---

src/AI/CoreLogic.pm

If user use openkore with a low teleport send time, sometimes openkore will send the command and the server will ignore, causing a stuck at teleport window in openkore.
this pull fix this.

fix teleport window stuck

---

control/config.txt

remove the skill level from the config so that the bot can use the maximum level available (see #3199)

[fix] skill lvl in config

---

src/Misc.pm
src/Network/Receive.pm

openkore was not waiting the all character list and sending 0066 packet to map-server, this can cause bot detections
before:
after:

[fix] wait receive all character pages to select char

---

plugins/eventMacro/eventMacro/Core.pm

```
macro unshift {
&unshift(@monsters, Porint)
&unshift(@monsters, Volf)
&unshift(@monsters, Maya)
log The array \@monsters has size @monsters and its members are $monsters[0], $monsters[1] and $monsters[2]
}
```
if the array is empty then OpenKore gets a fatal error:
this patch fixes a bug:

fixed the unshift function

---

plugins/eventMacro/eventMacro/Data.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

the keyword `&listlength` did not work due to a typo in the code.
Example:
```
macro listlength {
log listlength: &listlength(a, b, c)
}
```

Fix event macros listlength

---

plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

new syntax: `&venderamount (<item|ID>)`
this PR solves the problem: #3252
```
macro venderamount  {
do c \@go 1
do vender 0
[
log venderitem Alcohol: &venderitem(970),		amount: &venderamount(Alcohol)
log venderItem "Knife [3]": &venderItem(Knife [3]),	amount: &venderamount(Knife [3])
log venderItem 1201: &venderItem(1201),	amount: &venderamount(1201)
log venderItem Knife: &venderItem(Knife),		amount: &venderamount(Knife)
log venderItem 1201: &venderItem(1202),		amount: &venderamount(1202)
]
}
```
Console:
```
----------------------------- Vender: merchhh (0) -----------------------------
0   Knife [3]                                 Weapon           1           100z
1   Alcohol                                   Event           10            50z
2   Knife [3] …
```

[eventMacros] fix venderamount

---

src/Commands.pm

the questID field is now 6 digits
see: https://github.com/OpenKore/openkore/commit/f5441d2a695ae8331f425124d65474e9cde8633b#commitcomment-42449551:
> Can you fix the quest list command that only show quest ID only 5 digit, because the official server i play the quest id have 6 digit
before:
```
quest list
--------------------------------- Quest List ----------------------------------
0 7124  Battle Basics                   active
- Lunatic                         5
1 7126  Selling items                   active
2 7123  Battle Basics                   active
- Picky                           0
3 7127  Battle Basics                   active
- Willow                          0
-------------------------------------------------------------------------------
```
after:
```
quest list …
```

fix "quest list" command

---

plugins/eventMacro/eventMacro/Core.pm

- fixed regular expressions for stricter validation of incoming data
this is a bad example of a macro that shouldn't work
```
automacro MyAuto3 {
InMap morocc
delay test5
call myMacro
}
```
this fix will now get the error:

fixed parameters of automacros

---

plugins/eventMacro/eventMacro/Data.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm

this PR fixes: #3254 
additionally cleared the code
```perl
sub getWord {
my ($message, $wordno) = $_[0] =~ /^"(.*?)"\s*,\s?(\d+|\$[a-zA-Z][a-zA-Z\d]*)$/s;
my @words = split(/[ ,.:;\"\'!?\r\n]/, $message);
my $no = 1;
if ($wordno =~ /^\$/) {
my ($val) = $wordno =~ /^\$([a-zA-Z][a-zA-Z\d]*)\s*$/;
return "" unless defined $val;
if ($eventMacro->get_scalar_var($val) =~ /^[1-9][0-9]*$/) {$wordno = $eventMacro->get_scalar_var($val)}
else {return ""}
}
foreach (@words) {
next if /^$/;
return $_ if $no == $wordno;
$no++
}
return ""
}
```
It looks like this piece of code is never used:
```perl
if ($wordno =~ /^\$/) {
my ($val) = $wordno =~ /^\$([a-zA-Z][a-zA-Z\d]*)\s*$/;
return "" unless defined $val;
if ($eventMacro->get_scalar_var($val) =~ /^[1-9][0-9]*$/) {$wordno = …
```

Del &listitem keyword

---

src/Misc.pm

- combined two conditions into one template
- added a new symbol `-`
tested on rRO Prima
1. one item:
```lua
Sell<ITEML>0000y1kk&0g)00)00)00)00+05,00-01+0B,00-0m</ITEML>500k
```
2. multiple items:
```lua
S><ITEML>0000y1nC&05)00)00+0h,00-0C+0F,00-0h</ITEML><ITEML>000021jM&01)00)00+0h,00-0N+0B,00-0g</ITEML><ITEML>000021jM&01)00)00+0f,00-02+0B,00-0e</ITEML>
```
i think we can use one expression:
```lua
<ITEML>([a-zA-Z0-9%&(),+\-*]*)<\/ITEML>
```
see: https://regex101.com/r/0lel32/1
see: #3224

fix itemLink

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm

- added support for items that are 4 bytes long
if 'c' = 2, then using the old method 'c/v'
else using the new method 'c/V'
PS: tested on rRO Prime (c/V) and euRO (c/v)

fix package "special_item_obtain"

---

src/FileParsers.pm

This block does not work correctly
```
useSelf_item              Berserk Potion,     Awakening Potion,      Concentration Potion {
whenStatusInactive Berserk Potion, Awakening Potion, Concentration Potion
}
```
openkore count as the first element: "              Berserk Potion" instead of "Berserk Potion"
because of this, berserk will never work!

fix block parameters

---

src/AI.pm

follow up to: #3199
before:
after:

[FIX] auto select the skill lvl when lvl in config is higher than the character have

---

src/Commands.pm

before
```
c test1;;pause 5;;test2
Unknown command 'pause'. Please read the documentation for a list of commands.
http://openkore.com/index.php/Category:Console_Command
Unknown command 'test2'. Please read the documentation for a list of commands.
http://openkore.com/index.php/Category:Console_Command
zzzzzzzzzzzzzzzzzzzzzzz : test1
```
afther
```
c test1;;pause 5;;c test2
zzzzzzzzzzzzzzzzzzzzzzz : test1
zzzzzzzzzzzzzzzzzzzzzzz : test2
```
now the command is working again

fixed the pause command

---

.github/workflows/test.yml
src/Commands.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send.pm

- added description to 'cash' and 'cashbuy' commands
- now the 'cash list' command does not require running the 'cash open' command. After all, we receive this information immediately after loading the map
- fixed the 'cash buy <item_name>' command
- added clearing of the variable '$ cashShop {points}' after the store was closed, otherwise the 'cash open' command did not work after the store was closed
- updated the 'cash_shop_list' function. Added support for items 4 bytes ($ self -> {cash_shop_list_pack})
- updated the 'cash_shop_buy_result' function
- update wiki:
https://openkore.com/wiki/Cash
https://openkore.com/wiki/Cashbuy
https://openkore.com/wiki/WhenInGame_requestCashPoints
before:
after:

fixed cash shop

---

control/config.txt
plugins/needs-review/autowarp/trunk/autowarpn.pl
plugins/needs-review/freeCast/trunk/freeCast.pl
src/AI.pm
src/AI/Attack.pm
src/AI/CoreLogic.pm
src/AI/Slave.pm
src/Actor.pm
src/Field.pm
src/Misc.pm
src/Network/Receive.pm
src/Task/FollowActor.pm
src/Utils.pm

Right now even when openkore is following another player it will activate sitAuto Idle, that is not correct based on our wiki.
This pull fixes that and also fixes some wrong distance checks and walkable line checks (canMove was based on rathena/hercules checks)

Exchange checkLineWalkable for canMove and fix follow sitAuto Idle

---

plugins/alertSound/README.txt
plugins/alertSound/alertSound.pl

Fixed a bug in alertSound in which the conditions "eventList item name1, item name2" did not work.
```
eventList  item Red Potion, item cards, item *Card*, item *cotton*, item *potion*
```
the `item *cotton*` condition does not work, since parsed incorrectly:
```
foreach (split /\,/, $eventList) {
```

[alertSound] fixed eventList item

---

control/config.txt
src/AI/Attack.pm
src/AI/Slave.pm
src/Misc.pm

1 - Fixed wall avoiding in runFromTarget that was broken since the A* pathfinding update.
2 - Added runFromTarget_inAdvance, which makes it so you start avoiding/kiting the mob as soon as you attack, using the same idea as the dancing logic, which sends attack and move commands at the same time.
3 - Used the path prediction algorithmn used in meetingPosition in runFromTarget to better predict the target path and avoid it.
4 - Reworked the dancing algorithmn by testing the best combination of attack/move packets sent using this plugin I created 
https://github.com/Henrybk/openkore/blob/a0e07c73c11ca9397bb315f8c8e68d9b5c2cce10/plugins/testAttackDelay/testAttackDelay.pl
Reducing the delay between attack from 0.52s to 0.37s (From 1.05s not dancing), tested with a lvl 97 Amistr.

Improved runFromTarget and slave dancing

---

.github/workflows/build_XSTools.yml

fixed this error:
```
Reading package lists...
Building dependency tree...
Reading state information...
libreadline-dev is already the newest version (8.0-4).
libreadline-dev set to manually installed.
Suggested packages:
libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
The following NEW packages will be installed:
libcurl4-openssl-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 320 kB of archives.
After this operation, 1538 kB of additional disk space will be used.
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.4
Err:1 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.4
404  Not Found [IP: 52.252.75.106 80]
E: …
```

fixed github actions on ubuntu

---

src/Network/Receive.pm

In the packages "actor_display" and "actor_info" there is a space in the name of the monster at the end of the word.
This is typical for Russian monsters.
Because of this openkore stores the monster name as "Дикая кошка " instead of "Дикая кошка" (Wild Rose)
Thus, if you write the name of the monster instead of its ID in the mon_control.txt file, then these settings do not work.
Also, NPC names contain a space in the name.
Now in the file mon_control.txt you can specify Russian names of monsters. This error could be with other non-English languages.
PS: i don't understand this code
```perl
if ($args->{switch} eq "0086") {
$actor->{name} = $args->{name};
} else {
$actor->{name} = bytesToString($args->{name}) if exists $args->{name};
}
```
"0086" package does not contain the actor name: …

bug fix for mon_control

---

src/Network/Receive/ServerType0.pm

rRO Prime uses a new package for "sage_autospell"
```
[2021.04.23 19:23:04.61] Received packet: 0438 Handler: skill_use
[2021.04.23 19:23:04.64] Received packet: 07FB Handler: skill_cast
[2021.04.23 19:23:04.65] Вы кастуете умение Автозаклинание на себя (задержка: 3000 мс)
[2021.04.23 19:23:04.65] Received packet: 00B0 Handler: stat_info
[2021.04.23 19:23:04.66] Stat: 53 => 200
[2021.04.23 19:23:04.66] Received packet: 00B0 Handler: stat_info
[2021.04.23 19:23:04.67] Stat: 0 => 187
[2021.04.23 19:23:07.63] Received packet: 00B0 Handler: stat_info
[2021.04.23 19:23:07.64] Stat: 53 => 200
[2021.04.23 19:23:07.68] Received packet: 00B0 Handler: stat_info
[2021.04.23 19:23:07.68] Stat: 0 => 112
[2021.04.23 19:23:07.69] =========================================================================== …
```

adding a new package 0AFB

---

control/config.txt
control/timeouts.txt
src/Network/Receive.pm

- now the behavior of "pauseCharLogin" is similar to "pauseCharServer" and "pauseMapServer"
- now the "char_login_pause" timeout is configured in one place - in the config
I have not tested this change, but it seems to me that it is now easier to configure.

fix pauseCharLogin

---

plugins/alertSound/README.txt
plugins/alertSound/alertSound.pl
src/Network/Receive.pm

* added a new callHook "friend_request"
* plugin changes alertSound:
- added audio response to friendship request
- now the plugin works only on OS Windows
Example:
config.tx:
```
alertSound {
eventList friend
notInTown 1
inLockOnly 0
play plugins\alertSound\sounds\fuzz.wav
}
```
```
[2021.04.30 01:25:32.68] ya4ept wants to be your friend
[2021.04.30 01:25:32.68] Type 'friend accept' to be friend with ssdsdf, otherwise type 'friend reject'
[2021.04.30 01:25:32.69] Sound alert: friend
```

added a new callHook "friend_request"

---

control/config.txt
src/AI/CoreLogic.pm
src/Network/Receive.pm

now we can ignore objects on the ground only in the city
```
itemsGatherAuto_notInTown <boolean>
If this option is set, disables item gathering when in a city.
```

added new option "itemsGatherAuto_notInTown"

---

src/Commands.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send.pm
src/functions.pl

`Mail commands: ms, mi, mo, md, mw, mr, ma`
It's all very confusing.
let's do it by analogy with rodex: `mail open`, `mail read`, etc.
can be tested on RMS

Mail commands

---

plugins/alertSound/README.txt
plugins/alertSound/alertSound.pl

- replaced the old "player" hook with new ones  (player_exist, player_connected)
- added a new hook "player_moved", now alertSound will trigger more often on the "player" condition (don't forget to use a timeout)
- fixed a bug when, under the condition "notParty 1", the hash "$char->{party}{users}" was filled with unnecessary values:
1) hash composition before meeting new player (the party consists of 2 players)
2) hash composition after player meeting (some third player appeared):

alertSound fix

---

src/AI/CoreLogic.pm
src/Actor.pm
src/Misc.pm

The "onlyWhenSafe" condition did not work correctly.
Fixed a defect when the bot considered all the people around it to be members of its party (like #3449)
Steps to reproduce the problem:
1. Use config:
```lua
doCommand pl;;eval Log::warning "I'm safe \n" {
timeout 3
onlyWhenSafe 1
}
partySkill 142 {
isSelfSkill 1
dist 3
timeout 5
disabled 0
notPartyOnly 1
}
```
2. find several other players
https://user-images.githubusercontent.com/7117363/123915275-00142800-d989-11eb-9724-96185e13bb44.mp4

party_bug_autovivification

---

plugins/!deps/URI/Escape.pm
tables/vRO/maps.txt

Minor:
- encoded UTF8 for vRO/maps.txt

fixed "\C no longer supported in regex" for vRO_auth plugins when run openkore from perl 5.26+

---

src/Commands.pm
src/Network/Receive.pm

removed the extra hash element: `$guild{member}[$i]{title}`
instead one should use: `$guild{positions}[ $guild{member}[$i]{position} ]{title}`
> we shouldn't store the guildtitle of a guildmember both in $guild{positions} and $guild{member}, instead we should just store the rank index of the guildmember and get the title from the $guild{positions}
`eval Log::warning Data::Dumper::Dumper \%guild` before:
```
$VAR1 = {
'name' => 'koreopen',
...
'positions' => [
{
'gstorage' => 1,
'title' => 'Master',
'invite' => 1,
'feeEXP' => 0,
'punish' => 1
},
...
],
'member' => [
{
...
'position' => 0,
'title' => 'Master',
...
},
```
`eval Log::warning Data::Dumper::Dumper \%guild` after:
```
$VAR1 = {
'name' => 'koreopen',
...
'positions' => [
{
'gstorage' => 1,
'title' => 'Master',
'invite' => 1, …
```

code cleanup

---

src/AI/CoreLogic.pm

Now if "partyAuto 2" is configured in the config, then when requesting a party, the bot sends two packets to the server:
```perl
} elsif ($config{partyAuto} == 2) {
message T("Auto-accepting party request\n");
1>>>           $messageSender->sendPartyJoin($incomingParty{'ID'}, 1);
if ($incomingParty{ACK} eq '02C7') {
2>>>            $messageSender->sendPartyJoinRequestByNameReply($incomingParty{ID}, 1);
} else {
$messageSender->sendPartyJoin($incomingParty{ID}, 1);
}
}
```
In some cases, two different packets are sent to the server:
```css
<< Received packet:      02C6 - Party Invite by Name [30 bytes]   2021.07.20 01:59:31
0>  C6 02 B1 3C 00 00 7A 61    73 64 61 73 64 00 00 00    ...<..zasdasd...
16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00          ..............
Incoming Request to …
```

fixed partyAuto

---

src/Utils/TextReader.pm

Fix git warning for unclosed file handler

Fix not closed file handler

---

src/Commands.pm
src/Network/Receive.pm

rodex fixes

---

.github/workflows/build_XSTools.yml
SConstruct

our artifacts are getting messed up for building windows + perl 5.22
this is a temporary solution

fixed build for windows + perl 5.32

---

src/Network/Send.pm
src/Network/Send/cRO.pm
src/Network/Send/iRO.pm
src/Network/Send/kRO/RagexeRE_2012_03_07f.pm
src/Network/Send/kRO/Sakexe_0.pm
tables/servers.txt

We now have one function for all packages: `0067`, `0970` and `0A39`
Tested on jRO, cRO
Not tested on iRO, kRO:Zero, RagexeRE_2012_03_07f and higher
We need to make these changes in #3430

Moved all "sendCharCreate" to send.pm

---

src/auto/XSTools/utils/perl/Benchmark.xs

Debugging using Visual Studio 2019 bring me to this line when exiting Openkore.

Fix memory write violation in Benchmark.xs

---

src/Network/Send.pm

Added lowercase characters to the verification template.
Encryption keys in the [Hercules source](https://github.com/HerculesWS/Hercules/blob/stable/src/map/packets_keys_main.h) are low case, but OpenKore only supports upper case.
This PR fixes this behavior.

sendCryptKeys fix

---

src/Misc.pm

Defaul value:  `attackRouteMaxPathDistance 13`
If we take the old config, which does not have the `attackRouteMaxPathDistance` parameter, then we get an error:
> Unable to calculate a meetingPosition to target, dropping target
You are now attacking Monster Fabre (0)
Unable to calculate a meetingPosition to target, dropping target
You are now attacking Monster Lunatic (1)
Unable to calculate a meetingPosition to target, dropping target

added defaul value for attackRouteMaxPathDistance

---

src/AI/Attack.pm

If openkore fails to attack a mob when all his skills are on timeout after 6s it will drop the target, however this timeout won't reset after another skill is cast.
This fixes that.

Reset ai_attack_failed_give_up on attack success

---

control/config.txt
src/AI.pm

Currently if the bot has damaged a monster but the monster has not yet attacked the bot it won't be considered as aggresive.
This new config key when set to 1 makes openkore consider all monster in the screen who have been damaged by the bot as aggresives
Also deleted the duplicate timeout attack_failed -> ai_attack_unfail check

add attackAuto_considerDamagedAggressive

---

plugins/fixKafraTeleport/fixKafraTeleport.pl
src/Task/MapRoute.pm

Video showing usage: https://www.youtube.com/watch?v=57qEmQIVuBw
When trying to teleport using an NPC which accepts free teleportation tickets (Kafras) and the NPC cannot be found at the defined coordinates this plugin will try to find any NPC named "Kafra Employee" in the vicinity, if it finds, try to use it to teleport.
This PR does not add the plugin to sys.txt
TODO: make the NPC name configurable

add plugin fixKafraTeleport

---

control/config.txt
src/AI/Attack.pm
src/AI/Slave.pm
src/Misc.pm

Removes get_kite_position, uses meetingPosition instead.
Also changes another attacking behavior for the situation that a ranged character has already damaged its target but curently is out range 
Right now openkore will use meetingposition to get closer at attackMaxDist range
But if we already damaged the mob that means it is coming at us
So more often than not we will get closer to the mob while it is getting closer to us
This adds a config key that if '1' will make the bot wait for the target instad of going to it.
Video showcasing the branch: https://www.youtube.com/watch?v=ig9J9NiGgp8

Move run from target to meeting position

---

src/Network/Receive.pm

- added support for non-english names
before:
`êàðàì1 joined your party 'bg1'`
after:
`карам1 joined your party 'bg1'`

fixed party user

---

src/AI/CoreLogic.pm

Only recompile portals if one was recorded, last pull recompiled after every portal.

Fix recompile portals after record

---

src/Task/Route.pm

Add a hook call to the pathfinding object creation on Task::getRoute and also adds a new parameter to getRoute to determine if it was called from inside the module itself or not.
To be used with plugins such as: https://github.com/Henrybk/Plugins/tree/master/Drunk
https://www.youtube.com/watch?v=sLRZoqQKMeQ

Add callhook to Task::getRoute, also add self_call to it

---

src/Task/MapRoute.pm

Currently for some reason (I made it so blame myself I guess) route_tryToGuessMissingPortalByDistance will try to guess the closes portal to the player instead of the closest to the original portal, also it tests Route->getRoute in another loop and if it fails it guesses a new portal in even another loop.
This makes it so it guesses the closest to the original destination portal and does the Route->getRoute check at the same time.
Also now only use route_tryToGuessMissingPortalByDistance when there isn't another near known portal to the same destination

Clean route_tryToGuessMissingPortalByDistance

---

src/AI/CoreLogic.pm
src/Commands.pm
src/Network/Receive.pm

Hooks added for npc_chat, storage, buyauto and sellauto start/queue and buy_result.
I personally use these hooks to:
1: Clean AI queue of unwanted stuff when storage starts.
2: Block storageauto and buyauto from starting when eventMacro in in queue
3: Hook a few server-side messages that use npc_chat
4: Log items bought from buy_result

Add a few hooks

---

src/AI/Attack.pm

for some reason sometimes this fails:
`(AI::action("route") || AI::action("move"))`
while this seems to always work:
`(AI::is("move", "route"))`
So I just exchanged it

Fixed AI dequeue in AI Attack

---

control/config.txt
src/Network/Receive.pm

Currently openkore removes (actully just never adds) actors that are sent by the server with a distance greater than clientSight, however this comparison is made using {pos_to} and not actual position which can sometimes be greater than clientSight even when close.
This change actually calculates the position of both actors and compares them.
The second issue is that calcPosition is not perfect and usually gets 1 cell wrong, accounting for both actors the distance could be 2 greater of lower than the real one, so I added a config key to account for that.
Now only removes actors that are at least clientSight_removeBeyond beyong the clientSight limit.

add clientSight_removeBeyond

---

src/AI.pm

For some strange reason sometimes AI::clear leaves @ai_seq and @ai_seq with different sizes with causes a critical error, very hard to reproduce however we never really should use delete on arrays, this is still unfinished.

Rework AI clear

---

src/Network/Receive.pm

Second check for https://github.com/HerculesWS/Hercules/issues/3154
Sometimes the pos_to coordinate might not be 0 0 but can be very far.
Like:
`Monster Moved: Spore (1) - (297, 302) -> (32, 91)`
I believe seeting the max move distance for mobs to the same clientSight + clientSight_removeBeyond used for removing actors should be safe.
Also removed a +2 I left in clientSight check by mistake.

Fix bugged actor moved packet again

---

src/AI/CoreLogic.pm

this fixes #3625 
@aggressives wasn't populated due to incorrect predicate use. It makes no sense to check attackAuto value while populating @aggressives
"Perl has no boolean data type.
A scalar in an if statement evaluates to boolean "false" if and only if it is one of the following:
undef
number 0
string ""
string "0"
"

Fix attckAuto 0 and improve teleportAuto_search check fix #3625

---

plugins/eventMacro/eventMacro/Condition/SimpleHookEvent.pm
plugins/eventMacro/eventMacro/Data.pm

Hook arguments (arrays and hashes) are now passed to eventMacro as arrays and hashes.
this fix also applies to #1261
For example, we have a hook:
```
my %hash = (
key1 => "vol-1",
key2 => "vol-2"
);
my @arr = ('arr1', 'arr2');
Plugins::callHook($hook, {switch => $switch, hash => \%hash, arr => \@arr});
```
Before fix:
After fix:

fix SimpleHookEvent in eventMacro

---

.github/workflows/build_XSTools.yml

updated versions of actions to fix bugs:
1. Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
2. The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
3. The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-sa …

fix github actions warnings

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

struct:
```
#if PACKETVER_MAIN_NUM >= 20131204 || PACKETVER_RE_NUM >= 20131120 || defined(PACKETVER_ZERO)
struct PACKET_ZC_WHISPER {
int16 PacketType;
int16 PacketLength;
uint32 senderGID;
char sender[NAME_LENGTH];
uint8 isAdmin;
char message[];
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_WHISPER, 0x09de)
```

fix: update 0x09de unpack string

---

src/Commands.pm
src/Network/Receive.pm

removed extra `variable $rodexWrite->{name}`, we can use `$rodexWrite->{target}{name}` instead
BEFORE:
```
$VAR1 = {
'target' => {
'name' => 'kaya',
'base_level' => 1,
'class' => 0,
'char_id' => 100042
},
'name' => 'kaya',
'title' => 'TITLE',
};
```
AFTER:
$VAR1 = {
'target' => {
'name' => 'kaya',
'base_level' => 1,
'class' => 0,
'char_id' => 100042
},
'title' => 'TITLE',
};

rodex code cleanup

---

control/config.txt
src/Misc.pm
src/Network/Receive.pm
src/Settings.pm

Now openkore can log all users that are nearby (just not in the city).
Report example:
```
[2023.04.14 02:01:42] player test1 is near (new_1-4, lvl=4, job=Novice)
[2023.04.14 02:11:25] player test3 is near (new_1-4, lvl=4, job=Novice)
[2023.04.14 02:11:26] player test3 is near (new_1-4, lvl=4, job=Novice)
[2023.04.15 02:43:22] player SILEE is near (lasa_fild01, lvl=5, job=High Thief)
```

new log added: playerLog

---

control/config.txt
src/Misc.pm

implement monstersCount in checkSelfCondition
config.txt:
```
attackSkillSlot Judex {
lvl 10
dist 1
maxDist 5
sp > 10
stopWhenHit 0
inLockOnly 0
notInTown 0
timeout 0
disabled 0
monstersCount > 2
monstersCountDist < 10
maxAttempts 0
maxUses 0
isSelfSkill 0
isStartSkill 0
manualAI 0
}
```
result:
as can be seen in image when more then 2 monster in range openkore use judex, if not it attack using weapon
this closes #3693

feat: implement monstercountdist in checkselfcondition

---

src/Actor/You.pm

Closes https://github.com/OpenKore/openkore/issues/3773
`Actor::Item::bulkEquip()` requires a list of `<slot> => <itemName|itemId>` (leftHand => 'Katar', rightHand => 10)
AutoSwitch is sadly providing a list of `<slot> => <inventoryId>`.
This results in bulkEquip not finding InventoryId 9 in its itemlist.
Forcing AutoSwitch to always pass the ItemName to BulkEquip should fix this issue without breaking any equipment functionality

Allow the AutoSwitch mod to correctly switch weapons/shields

---

control/config.txt
src/AI/Attack.pm
src/AI/CoreLogic.pm

this pull make openkore avoid hidden monsters.
if  `avoidHiddenMonsters` is set openkore will not choose hidden monster to attack and will drop the target if after the attack start the monster uses Hide
new config keys:
```
avoidHiddenMonsters 
teleportAuto_dropTargetHidden 
```
screenshots:
dropping and attacking other monster
dropping and using teleport:
fixes #3695

feat: add key to avoid hidden monsters

---

control/timeouts.txt

openkore was waiting 10 seconds after map load to do some action, thisp pull request reduce this value to 1 second

chore: update clientsuspend timeout

---

src/AI/CoreLogic.pm
src/Misc.pm
src/Network/Receive.pm

- avoid recognize actor as npc when it is out of clientSight
- avoid interact with actors out of clientSight
before:
after:

fix: update actor_display to correct recognize actor

---

src/AI/SlaveAttack.pm

fixed syntax error:
```
syntax error at src/AI/SlaveAttack.pm line 435, near "'attackRouteMaxPathDistance')"
Missing right curly or square bracket at src/AI/SlaveAttack.pm line 560, at end of line
Compilation failed in require at src/AI/Slave.pm line 12.
BEGIN failed--compilation aborted at src/AI/Slave.pm line 12.
Compilation failed in require at src/AI/SlaveManager.pm line 13.
BEGIN failed--compilation aborted at src/AI/SlaveManager.pm line 13.
Compilation failed in require at src/AI/CoreLogic.pm line 33.
BEGIN failed--compilation aborted at src/AI/CoreLogic.pm line 33.
Compilation failed in require at openkore.pl line 64.
BEGIN failed--compilation aborted at openkore.pl line 64.
Press ENTER to exit.
```

fix PR#3780

---

control/timeouts.txt
src/Task/TalkNPC.pm

This change removes artificial delay controlled by `ai_npc_talk_wait_to_answer`. Every NPC message 00B4 sets `$ai_v{npc_talk}{talk} = 'initiated';`, and a NPC dialog menu 00B7 sets `$ai_v{'npc_talk'}{'talk'} = 'select';`. By returning early on `intiated`, we can make talking to NPC really fast and makes the bot more enjoyable to use. I have been using this change locally for couple months now and it's working flawlessly, and it doesn't change the behavior of when an NPC sends no response.

Send response to npc as quickly as possible

---

SConstruct

On certain gcc distribuitions, if TEMP/TMP are unset, it defaults to writing to the root Windows OS directory (C:/Windows)
https://github.com/msys2/MSYS2-packages/issues/235

Prevent GCC from writing to Windows install directory

---

plugins/eventMacro/eventMacro/Condition/QuestActive.pm

Setting is_on_stand_by = 0 after a map change was the reason that an active quest doesn't trigger QuestActive condition. Every map change ends up calling validate_condition with a new value of 0 which sets is_validated to false.

Fix map change invalidate QuestActive

---

src/AI/Attack.pm

item take in actor_died_or_disappeared is only for itemsTakeAuto_party
This revert https://github.com/OpenKore/openkore/pull/3802/commits/92cbad75fd8a85e088c53fd07223722a2053ce39

Add back item take logic in finishAttacking

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

The bug:
I tested locally that the refs are now different and everything works great.

Fix the bug where both moving from and to coordinates are the same when moving between differnt cells.

---

src/deps/Carp/Assert.pm

this pull fixes the warning:
> test ubuntu-22.04 (perl latest) x64: src/deps/Carp/Assert.pm#L385
> Old package separator "'" deprecated
I updated the package to version 0.22
but i didn't test openkore work!

updated the Carp::Assert package

---

.github/workflows/build_XSTools.yml

This query removes the following warnings:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

fix_GitHub_Actions

---

src/AI.pm
src/Network/Receive.pm

Openkore sets $ai_v{temp}{clear_aiQueue} =1 when doing any form of auto teleporting. This flag in turn clears the entire ai on map change, among which %ai_v. %ai_v contains timeouts for any item, skill or command block from config.txt. If these get cleared, Openkore uses every item or skill that only has a timeout after every auto teleport. This fix still clears the ai, but keeps any timeouts in %ai_v so Openkore doesn't spam skills or items after every auto teleport.

Fix clearing timeouts after auto teleport

---

src/Commands.pm

The console command "verbose" is no longer supported. Use "conf verbose #" instead.

remove verbose command

---

src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

This should fix it: https://github.com/OpenKore/openkore/issues/3818
```
struct PACKET_ZC_UPDATE_GDID {
int16 PacketType;
uint32 guildId;
int emblemVersion;
uint32 mode;
uint8 isMaster;
int32 interSid;
char guildName[NAME_LENGTH];
uint32 masterGID;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_UPDATE_GDID, 0x02f7)
```
I haven't tested this.

Added support for 02F7 package (guild_name)

---

src/Network/Receive.pm

We don't know what type 7 and 13 are. Type 7 looks like body palette or body color. Type 13 looks like body2
fix https://github.com/OpenKore/openkore/issues/3905
https://github.com/HerculesWS/Hercules/blob/stable/src/map/map.h#L784
```
enum look {
LOOK_BASE,
LOOK_HAIR,
LOOK_WEAPON,
LOOK_HEAD_BOTTOM,
LOOK_HEAD_TOP,
LOOK_HEAD_MID,
LOOK_HAIR_COLOR,
LOOK_CLOTHES_COLOR,
LOOK_SHIELD,
LOOK_SHOES,
LOOK_BODY,
LOOK_FLOOR,
LOOK_ROBE,
LOOK_BODY2,
#ifndef LOOK_MAX
LOOK_MAX
#endif
};
```

suppress the output of the sprite_change message

---

src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm

This query solves the problem: https://github.com/OpenKore/openkore/issues/3907
```
<< Received packet:      0A15 [12 bytes]   2024.12.17 09:12:57
0>  15 0A 01 01 35 00 00 00    AF 00 00 00                ....5.......
[2024.12.17 09:12:57.41] Packet Parser: Unknown switch: 0A15
#if PACKETVER >= 20140611
struct PACKET_ZC_GOLDPCCAFE_POINT {
// Note: 2014-04-30 has 1 byte less, but those packets are only functional after 2014-06-11Ragexe
uint16 PacketType;
int8 isActive; //< 1 = yes, 0 = no
int8 mode;
int32 point;
int32 playedTime;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_GOLDPCCAFE_POINT , 0x0a15);
#endif // PACKETVER >= 20140611
```
If you get the error "Received unknown packet", just add a new packet to therecvpackets.txt file:
```
0A15 12
```
I haven't tested this …

Minimum package support 0A15 (PACKET_ZC_GOLDPCCAFE_POINT)

---

src/AI.pm
src/AI/CoreLogic.pm
src/AI/Slave.pm
src/AI/SlaveManager.pm
src/Actor/You.pm
src/Commands.pm
src/Misc.pm
src/Network/Receive.pm

Fixes #3913 
Each actor now holds their own skill list.
Possible problem is that I don't know actually how skills are handled in the server, if they are coded as a character skill then their use must remain in AI::Corelogic, if however slaves are their own separate entity with cooldowns of their own then it would probably be wise to move their skill usage to their AI.
EDIT:
It does seem char and slave are completely independent, I'll move the skill use logic to their AI
EDIT2:
Done, just gotta test it
Edit 3:
Video showing it working:
[Youtube](https://youtu.be/PK9ckS35uNg)

Fix slave skills

---

control/config.txt
src/AI/CoreLogic.pm
src/AI/Slave.pm
src/AI/Slave/Homunculus.pm
src/AI/SlaveManager.pm
src/Actor/You.pm
src/Commands.pm
src/Interface/Wx/StatView/Homunculus.pm
src/Misc.pm
src/Network/Receive.pm

This fixes issue 2 of #3919
Issue 1 must still be fixed.
I think a good solution would be to add 2 new checks for checkSelfCondition:
`_homunculus_noinfo_dead: is only positive when $char->{homunculus_info}{dead} is undefined`
`_homunculus_noinfo_resting: is only positive when $char->{homunculus_info}{vaporized} is undefined`
So we could make some useSelfSkills cleverly to fix the issue like:
useSelf_skill Resurrect Homunculus {
homunculus 0
homunculus_noinfo_dead 1
}
If it works, great, homun is alive, if it fails we now know $char->{homunculus_info}{dead} is 0. Then we can use:
useSelf_skill Call Homunculus {
homunculus 0
homunculus_noinfo_resting 1
}
If it works, great, homun is alive, if it fails we now know $char->{homunculus_info}{vaporized} is 0.

Fix homunculus state crashes

---

src/AI/CoreLogic.pm
src/Network/XKore2.pm

fix: correct calcposition call at party logic

---

.github/workflows/build_XSTools.yml

Now we automatically search for the path to python3 for windows 2019
Fix:

Fixed a bug in GitHub Actions

---

src/Network/XKoreProxy.pm

Now if "loginPinCode" is specified in the config, OpenKore will automatically enter it.
Testing on idRO
Inspired by #3529, thanks @royalgarter

Added loginPinCode support in XKore3 mode

---

src/AI/Attack.pm
src/AI/SlaveAttack.pm

With these new attack and pathfinding changes the distinction between melee and ranged does not exist anymore so it is better to just remove the related messages and checks

Removed melee-ranged unnecessary message and check

---

plugins/eventMacro/eventMacro/Condition/Base/ActorNotNear.pm
plugins/eventMacro/eventMacro/Condition/CharCurrentWeight.pm
plugins/eventMacro/eventMacro/Condition/CharMaxWeight.pm
plugins/eventMacro/eventMacro/Condition/InCity.pm
plugins/eventMacro/eventMacro/Condition/InMap.pm
plugins/eventMacro/eventMacro/Condition/InMapRegex.pm
plugins/eventMacro/eventMacro/Condition/InSaveMap.pm
plugins/eventMacro/eventMacro/Condition/IsInMapAndCoordinate.pm
plugins/eventMacro/eventMacro/Condition/JobID.pm
plugins/eventMacro/eventMacro/Condition/JobIDNot.pm
plugins/eventMacro/eventMacro/Condition/NotInMap.pm
src/Network/Receive.pm

Title.
Weight did not wait for inventory.
Job didn't hook sprite_job_change.
Map was not wrong but did not have a check on $field definition, also added a few hooks for safety.

Fix job, weight and map conditions of eventMacro

---

src/AI/Attack.pm
src/AI/CoreLogic.pm
src/Task/MapRoute.pm
src/Task/Route.pm
src/Task/TalkNPC.pm

Currently Task Route sends multiple packets of character move to the same cell in a repeated manner, some servers really don't like that like idRO.
This change prevents the Task from sending a new move packet if it's destination is the same as the current character movement.
Also when this happens and you are in a meeting route to a targer, give back control to AI::Attack.

Prevent repeated move packets

---

src/Task/Route.pm

Fix route bug implemented in last PR

---

src/Commands.pm
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Receive/kRO/Sakexe_0.pm
src/Network/Send.pm
src/Network/Send/ServerType0.pm
src/Network/Send/kRO/Sakexe_0.pm

Fix: https://github.com/OpenKore/openkore/issues/3951
0A16 - CZ_DYNAMICNPC_CREATE_REQUEST
0A17 - PACKET_ZC_DYNAMICNPC_CREATE_RESULT
Added new command:
```
nc - NPC Create (default name is GOLDPCCAFE)
nc <name> - Create NPC by <name>
```
Examlpe:
```
help nc
==================================================== Help for 'nc' ====================================================
NPC Create.
nc           Create NPC by default name 'GOLDPCCAFE'
nc <name>    Create NPC by <name>
=======================================================================================================================
```
```
nc
================================================
>> Sent packet: 0A16  [NPC Dynamic Create Request] [26 bytes]   2025.01.16 01:49:53
0>  16 0A 00 00 00 00 00 00    00 00 00 00 00 00 00 00 …
```

Minimum package support 0A16 and 0A17

---

src/AI/Attack.pm
src/AI/SlaveAttack.pm

attackSkillSlot maxattempts is being counted when setting the attack method instead of when being actually sent so the route to target is being counted as a $i++. This fixes that.

Fix attackSkillSlot maxattempts

---

src/Misc.pm

Currently getBestTarget prioritizes monsters in LOS, but when there are no monsters in LOS and at least 1 monster without LOS it chooses to attack it, without first checking if it is routable, leaving it to be done in Attack.pm.
Since we will do it in Attack.pm anyway why not do it in getBestTarget and prevent the SetTarget > NoLOS > Drop > SetTarget > etc loop?

add Pathfinding to getBestTarget

---

src/Actor.pm
src/Task/MapRoute.pm
src/Task/Route.pm

This has 2 changes.
First one is that when distFromGoal is 1 and closestWalkableSpot result is more than 1 cell away trimsteps would be negative and that would crash the task.
Second one is that I added the option to set a flag that tells the task route that your destination spot is an NPC, so that it can stop moving when the npc is visible on screen.

Fix route trimsteps

---

.github/workflows/build_XSTools.yml

Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
- updated ubuntu-20.04 to ubuntu-22.04
- updated ubuntu-22.04 to ubuntu-latest (24.04)

updating ubuntu versions for github actions

---

src/Task/TalkNPC.pm
src/Utils.pm

When a portal like this exists:
prontera 282 200 gef_fild10 52 326 1700 1 c r~/(warp|telepor)/i c r~/orc dungeon/i
It was failing like this:
[2025.05.01 10:04:11.42] [test addSteps] step 1 'c r~/(warp|telepor)/i c r~/orc dungeon/i'
[2025.05.01 10:04:11.42] [test addSteps] new_steps 2 dump $VAR1 = [
'c',
'r~/(warp|telepor)/i',
'c',
'r~/orc',
'dungeon/i'
];
This change fixes that.

Fix parsenpc steps in portals

---

plugins/NewAStarAvoid/NewAStarAvoid.pl
plugins/eventMacro/eventMacro.pl
plugins/eventMacro/eventMacro/Condition/FreeSkillPoints.pm
plugins/eventMacro/eventMacro/Core.pm
plugins/eventMacro/eventMacro/Data.pm
plugins/eventMacro/eventMacro/FileParser.pm
plugins/eventMacro/eventMacro/Runner.pm
plugins/eventMacro/eventMacro/Utilities.pm
src/AI/Attack.pm
src/AI/CoreLogic.pm
src/Field.pm
src/Misc.pm
src/Network/DirectConnection.pm
src/Network/Receive.pm
src/Task/MapRoute.pm
src/Task/Route.pm

This are a few small changes I made in my personal branches over the last few months and have not yet sent to the master branch.
Updates:
Adds a hook to attack process for custom traget dropping (AI::Attack::process)
Adds hooks to both processDeal and processDealAuto for custom deal manipulation
Adds a check so autostorage will only start when ai_canOpenStorage() is true
Adds a return to processFollow so it will only move forward when AI is follow or similiar
Addds a hook to nameToBaseName in field creation to use in custom map instances (eg. izlude_a)
Addes hooks after configmodify and bulkconfigmodify (post_configModify)
Makes bulkConfigModify create missing keys
Adds a checkSelfCondition key '_inInventoryID' which checks for inventory items by ID
Adds a hook to checkConnection for …

Collection of small changes

---

src/Misc.pm
src/Network/Receive.pm
src/Task/TalkNPC.pm
tables/iRO/portals.txt

Solution for rachel airport portal.
Rough code needs testing and cleaning.
If you stand beside the npc and do 'talknpc 294 200 k c r0' it works.
The problem is that when routing the AI is usually 'route' with a TalkNPC subtask, then this fails, needs fixing for that specific situation.

add 'k' sequence to approach npcs and portals to auto trigger talk

---

src/AI/CoreLogic.pm
src/Network/Receive.pm
src/Task/MapRoute.pm
src/Task/TalkNPC.pm

Should fix #3733 and #4014 
When Task TalkNPC was started it did not check wheter we were already talking to an NPC or if that was true if the NPC was the correct one.
In some cases, like the mapRoute, it just adds the task if we are close to the NPC, and in the case of 2 close npcs one Task might use the %talk created by the other, causing the errors in #3733 
Also Buyauto should not trigger during storage so I also added that check, same for sellauto

Fix talknpc

---

src/AI/Attack.pm
src/AI/CoreLogic.pm
src/Network/Receive.pm

Sometimes the server won't send the packet that informs that a monster has died and the client will keep thinking forever that the monster is there (this happens in the normal client also), this adds a routine that once a second removes actors that are twice the distance of clientSight from the character, also moves the avoid to corelogic and adds the removal of avoided actors who are now close.
This also fixes the bug where 'attack' would be added multiple times in the AI queue as seen below.

Remove bugged actors

---

control/config.txt
control/sys.txt
plugins/otp/otp.pl
src/Network/Receive.pm
src/Network/Receive/ServerType0.pm
src/Network/Send.pm
src/Network/Send/ServerType0.pm

Add a new request_otp_login hook to OpenKore’s received_login_token flow, enabling plugins to generate and supply a Time‑based One‑Time Password (TOTP) without altering core logic.
Existing plugins must patch core code or rely on brittle workarounds to intercept and halt the default sendTokenToServer call for OTP flows. By exposing a dedicated hook with a pass‑by‑reference OTP slot, we allow clean, maintainable 2FA/TOTP integrations.
- On login types 400/1000, call Plugins::callHook('request_otp_login', { otp => \$otp, seed => $config{otpSeed} }) before sending OTP.
- Add sendOtpToServer($otp) wrapper for packet 0C23.
- Register packet parser entry '0C23' => ['send_otp_login', 'a6 C', [qw(otp padding)]].
- Pure‑Perl implementation of Base32‑decode, HMAC‑SHA1, and TOTP in a standalone …

feat(otp): Introduce request_otp_login hook for TOTP generation

---

plugins/eventMacro/eventMacro/Condition/Eval.pm
plugins/eventMacro/eventMacro/Condition/EvalHook.pm
plugins/eventMacro/eventMacro/FileParser.pm

example:
```
sub CallbackHook {
my ($name, $args) = @_;
use Globals;
return if !defined $char;
(my $user = $config{username}) =~ s/\@.*//;
$args->{return} =~ s/$char->{name}/$user/g;
$::consoleCounter = 0 if (!defined $::consoleCounter);
$args->{return} = "($::consoleCounter) $args->{return}";
1;
}
automacro TestHuh {
EvalHook mainLoop::setTitle : main::CallbackHook($callback_name, $args);
timeout 1
call {
do eval $::consoleCounter += 1;
}
}
```
example 2:
```
automacro TestHuh {
EvalHook mainLoop::setTitle : {
use Globals;
return if !defined $char;
(my $user = $config{username}) =~ s/\@.*//;
$args->{return} =~ s/$char->{name}/$user/g;
$::consoleCounter = 0 if (!defined $::consoleCounter);
$args->{return} = "($::consoleCounter) $args->{return}";
1;
}
timeout 1
call {
do eval …
```

feat: adds eval condition in eventmacro

---

control/config.txt
src/Field.pm

- Replace hardcoded value 17 with configurable maxWalkPathDistance
- Add maxWalkPathDistance config option with default value 17
- Corresponds to server's max_walk_path setting (hercules/rathena)
- Maintains backward compatibility with default behavior
Resolves TODO in Field.pm line 423

Make maxWalkPath configurable in Field.pm

---

src/Network/DirectConnection.pm

This program has encountered an unexpected problem. This is probably because of a recent server update, a bug in this program, or in one of the plugins. We apologize for this problem. You may get support from IRC or the forums. 
A detailed error report has been saved to errors.txt. Before posting a bug report, please try out the latest release GIT version first. If you are already using the latest release GIT version, search the forums first to see if your problem had already been solved, or has already been reported. If you truly believe you have encountered a bug in the program, please include the contents of the errors.txt in your bug report (https://github.com/openkore/openkore/issues), or we may not be able to help you! 
The error message is: 
send: Cannot determine peer address at …

xKore0 serverSend check peer
