- .gitignore
Another debug log generated by Openkore.
> Ignoring benchmark-results.txt file

- tables/cities.txt
> add a few missing cities so kore will know when it's notInTown

- .gitignore
Ignore backup files and patch file output.
> add backup files to gitignore

- src/Network/Receive/ServerType0.pm
> fix #14 support 1b vends

- tables/iRO/official/items.txt
- tables/iRO/official/itemsdescriptions.txt
> update iRO files

- src/Commands.pm
Since we are now using .fld.gz files we should change these commands
also.
> Commands support for .fld.gz

- src/Network/Receive/fRO.pm
> fix fRO autobuy

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/idRO.pm
- src/Network/Send/idRO.pm
- tables/servers.txt
* Revert `serverType` for [Indonesia - idRO: Midgard] to idRO.
* Updated idRO.pm files, simply copy of iRO.
* Added 'idRO' servertype check `sub received_characters`
> Follow up 75b0e3cfa03fae4314d4c7134fada7cf0b0e7a95

- src/Settings.pm
Add a `--ai=[on|off|manual]` command line option. For example: `openkore.pl --ai=manual`
> add ai=s command line option

- tables/idRO/msgstringtable.txt
> Added idRO's msgstringtable.txt

- src/Plugins.pm
- src/test/PluginsHookTest.pm
This pull request has unit tests, which are probably sufficient for testing.
> fix #124 - allow hook callbacks which remove themselves

- tables/servers.txt
An updated ```clientinfo.xml``` file was provided by a user on IRC.
> Fix issue #131 update fRO server.txt

- src/Network/Receive/ServerType0.pm
- src/Network/Send/iRO.pm
Support the new 097C (request top10) and 097D (receive top10) packets.
> fix top10 command on iRO

- src/FileParsers.pm
- src/functions.pl
* Passed `hide_comments` as an option for TextReader
* Fixed #144
> Fixed 'empty' msgstringtable.txt was bypassed by TextReader

- src/Network/Receive/ServerType0.pm
> support packet 097e (rank_points)

- control/pickupitems.txt
- control/shop.txt
- tables/bRO/control-br/config.txt
- tables/bRO/control-br/consolecolors.txt
- tables/bRO/control-br/items_control.txt
- tables/bRO/control-br/mon_control.txt
- tables/bRO/control-br/pickupitems.txt
- tables/bRO/control-br/poseidon.txt
- tables/bRO/control-br/priority.txt
- tables/bRO/control-br/responses.txt
- tables/bRO/control-br/routeweights.txt
- tables/bRO/control-br/shop.txt
- tables/bRO/control-br/sys.txt
- tables/bRO/control-br/timeouts.txt
* Syncs control-br folder with main control folder
* Removes duplicate explanation in pickupitems.txt and shop.txt
> Control-br update

- tables/bRO/portals.txt
Disabled old gef_fild and updated all Eden Officers NPC locations.
> changes at bRO portals.txt

- src/Network/Receive/ServerType0.pm
iRO uses this packet when a skill given by equipment (eg, Heal given by a Vitata Card) is removed.
> support packet 0441 (skill_delete)

- src/Commands.pm
Check if cart exists before send item straight from storage to cart !
> storage_gettocart changes

- src/Network/XKore.pm
- src/Network/XKore2.pm
- src/Network/XKoreProxy.pm
- src/po/de.po
- src/po/id.po
- src/po/ko.po
- src/po/openkore.pot
- src/po/pt.po
- src/po/ru.po
- src/po/th.po
- src/po/tl.po
- src/po/zh.po
- src/po/zh_CN.po
> fix #269 - add more useful error when XKore2 has a port conflict

- src/Settings.pm
Now only files that match the regex will be hooked
> Fix in function loadByRegexp and add loadFiles

- src/Network/Receive.pm
Fixes #290, a network cleaning issue
> Fixes #290

- plugins/breakTime/breakTime.pl
Adds the description for the breakTime plugin (plugin help command)
> Description for breakTime plugin

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Receive/kRO/Sakexe_2005_05_30a.pm
Caused by network cleaning
Tested on RMS Renewal
> Fixes #305

- control/poseidon.txt
- src/Poseidon/servertypes.txt
- tables/bRO/control-br/poseidon.txt
added bRO_2016-11-08a
removed bRO_2016-10-25a
> [2016-08-11] Poseidon servertype for bRO

- tables/bRO/portals.txt
added the correct route from airport to einbroch at portals.txt
> Add Route from Airport to Einbroch at bRO

- src/Network/Receive.pm
Sorry for the 3 commits I made this on my phone and was the greatest pain ever.
This is probably what @emjustin wanted in #338
> New move hooks

- src/Interface/Vx.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
This is really long unused option which plagues the network code.
> Remove support for deprecated encrypt config option

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2013_03_20.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Just adding these two useful hooks, I am already using them with no problems at all, as you can see the code I made for them in eventMacro here: https://github.com/Henrybk/eventMacro/commit/09b2b25499ea7935d1f0920062512a6aaf418057
> Add 'equipped_item' and 'unequipped_item' hooks

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
How to test: prt_fild08 338 217, for example.
> Add basic implementation for npc_chat

- src/Network/Receive/ServerType0.pm
- tables/servers.txt
The number of packet changes seems to be quite small this time. If anybody sees any other missing packets, please report them in IRC and/or as a comment here.
> iRO doram update packet changes

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- tables/servers.txt
> Iro doram packets

- src/Network/Receive.pm
> fix #470 storage duplication bug

- plugins/needs-review/xconf/trunk/xconf.pl
I have been using this change for a long time now, thought I should push it.
The only thing it does is add the slot to the end of the item based on $itemSlotCount_lut
> Add slot check to xConf item ID change

- src/FileParsers.pm
- src/Task/CalcMapRoute.pm
For as long as I can remember kore can't handle properly Free Ticket for Kafra Transportation, these days are over because after days I finally found the bug that made it not work.
> Fix allow ticket

- tables/idRO/maps.txt
- tables/idRO/msgstringtable.txt
> Fix utf-8 error for idRO tables

- tables/iRO/spells.txt
- tables/spells.txt
> add Poison Mist to spells.txt so it can be used with whenNotGround

- src/AI/CoreLogic.pm
Summoner having different basic skill than novice/super novice.
> Fix summoner unable to sit.

- plugins/profiles/profiles.pl
Add initial support for profile changing during runtime.
> Add profile changing support

- src/Network/Receive.pm
I think this change is good because we already have a hook for players but not for any other actor type. This also helps development of my project eventMacro :P
> Added 4 new hooks for pet, mob, npc and slave info

- src/Network/Send/twRO.pm
> sendCharCreate update

- plugins/needs-review/xconf/trunk/xconf.pl
clearall removes all lines except #lines, empty lines and all parameter.
setall setting all keys to selected.
Using this features for some maybe they needed here :/
> [xconf.pl] Added clearall and setall feature.

- src/InventoryList.pm
I believe this little change makes the code faster and has no drawbacks.
> Small change in inventoryList::remove

- plugins/teleToDest/readme.txt
- plugins/teleToDest/teleToDest.pl
Description in readme file.
Needs more testing.
> Plugin teleToDest (route_teleport on target coordinates)

- src/Task/TalkNPC.pm
> Make Task::TalkNPC ignore excessive use of talk cont 

- tables/servers.txt
> RO:RESTART- NEWIP

- src/Misc.pm
> Fix open shop bug added in #375

- src/Network/XKoreProxy.pm
this allows kore running inside a natted environment to expose the correct public ip instead of the currently associated ip (this is the same behavior in XKore 2 ported over to XKore proxy)
also, my editor auto removes spaces at the end of the line :D
> use the public ip if set

- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
> Fix dealauto bug

- src/Commands.pm
Support talk-by-name, for example: `talk "Edgar"`.
> talk by name

- tables/iRO/Restart/official/portals.txt
- tables/servers.txt
thanks @xTriumph for confirming :)
this closes #752 with input from @xTriumph
original code by @Onihen
> closes #752

- tables/servers.txt
Just a tiny detail to get portals.txt working.
> Correct folder direction for iRO Restart

- tables/iRO/Restart/portals.txt
Now that the portals.txt is in the right folder we can make this change.
> Link Christmas NPC update

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
Update to support all know show_eq packets
> Update in function and packets of ZC_EQUIPWIN_MICROSCOPE (show_eq)

- src/Network/Send/bRO.pm
As reported by @guilhermeferreira1
By the way, does any official server still use the old top10 packets in serverType0?
> [bRO] top10 ranks

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> Add hooks to autotalk

- plugins/macro/Macro/Parser.pm
Reverts OpenKore/openkore#856
Reverting due to #863
> Revert "Update Parser.pm"

- plugins/eventMacro/eventMacro/Condition/InSaveMap.pm
- plugins/eventMacro/eventMacro/Condition/StorageOpened.pm
Added conditions InSaveMap and StorageOpened, fixed InLockMap to work with files realoading.
> Added 2 conditions to eventMacro , fixed another one.

- tables/iRO/Restart/portals.txt
* remove non-existent kafra warps from prontera
* add comodo warp from morocc (didn't bother adding pharos lighthouse, sorry)
* moc_fild20 doesn't exist yet (but not all references were fixed, sorry)
* add an assassin job change portal
> iRO Restart portal updates

- tables/iRO/Restart/portals.txt
Added orc dungeon portals, removed moc_para portal
> update restart portals 2

- tables/bRO/portals.txt
> [bRO] Patch Eden HQ NPC coords at Izlude

- plugins/eventMacro/eventMacro/Condition/BusMsg.pm
> Add BusMsg eventMacro condition

- tables/bRO/portals.txt
Made with portalRecord
None of these require the Ring of the Ancient Wise King
> [bRO] Some new world portals

- src/Task/CalcMapRoute.pm
There are many situations in which several destinations are equivalent. For example:
* Go to the nearest store which sells White Potions.
* Go to the nearest Kafra.
This pull request modifies `Task::CalcMapRoute` to take a `targets` array of possible targets. It then routes to the nearest target, and returns that route.
There is no code currently in OpenKore which uses this feature, but it's very useful for plugins/macros. For example, the following set of eventMacros routes to the nearest Kafra to save and/or open storage:
```
macro storage_open {
[
$open = &eval( $::char->storage->isReady ? 1 : 0 )
if ($open == 1) stop
call find_kafra
if ($kafraidx == -1) stop
]
do move $kafrapos $kaframap $kafradist
do talknpc $kafrapos $kafrastor
[
$openi = 0
while ($openi < 12) as open_loop
$open = …
```
> support multiple targets in CalcMapRoute

- src/Commands.pm
> cart add
> cart get
> cart desc
**Reference**: #913 
Test:
> command cart fix

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Task/TalkNPC.pm
This makes openkore able to correctly end a conversation with an npc that auto closes the conversation, like in the knight job change quest.
> talknpc improvements

- plugins/needs-review/busCommands/trunk/busCommands.pl
- plugins/needs-review/busCommands/trunk/doc/README.txt
- plugins/needs-review/busFollow/trunk/busFollow.pl
- plugins/needs-review/busFollow/trunk/doc/README.txt
- plugins/needs-review/busParty/trunk/busParty.pl
- plugins/needs-review/busParty/trunk/doc/README.txt
- plugins/needs-review/wait4party/trunk/doc/README.txt
- plugins/needs-review/wait4party/trunk/wait4party.pl
Now busCommands have a README file (a very good one)
small update in this plugin, to show the content of message sent on openkore
improved indentation, for better readability. (i didn't rewrite completly the file, just changed indentation)
Inserted busParty, busFollow and wait4party with its README's.
In my opinion, those are very important plugins, specially for master and slave configurations, and should be inside the folder.
It also helps to have a better version control of the plugins
None of those plugins were made by me, the credits are inside the plugin file.
Sorry if your find gramatical errors or typos, english it's not my main language and i have a lot to learn.
> busCommands update, busfollow, busparty and wait4party on needs-review folder

- plugins/needs-review/webMonitor/trunk/WWW/_sidebar.html.template
Preview: https://yadi.sk/i/WjiWckwF3KRqdf
> [plugin/webMonitor] Show current player on sidebar's map

- plugins/profiles/profiles.pl
Folders that begins with # not visible now.
Last option is always standard control folder.
Did it as simple as possible. Need some testing for command.
> [profiles.pl] Can hide folder. Standart folder choise.

- control/config.txt
Change the default configuration to make Kore more friendly.
* turn on more logs, so people can find out what happened to their bots and make better reports
> turn on more logs

- tables/iRO/Restart/portals.txt
Just lost 500k on this little bug.
> fix restart portal Xth time

- control/timeouts.txt
- src/Globals.pm
- src/Misc.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/functions.pl
- tables/servers.txt
Should fix http://forums.openkore.com/viewtopic.php?f=16&t=212255 but not in an elegant manner.
Proof:
> beta fix for restart premium character slots

- plugins/eventMacro/eventMacro/Core.pm
The variables are:
`$.dayofweek = returns the current day of the week. `
The possible values are: Monday Tuesday Wednesday Thursday Friday Saturday Sunday
`$.dayofmonth = returns the current day of the month. `
The possible values  are numbers between 1 and the last day of month. (28,29,30 or 31)
`$.weightpercent = returns the percent of the current weight.`
`$.cartweightpercent = returns the percent of the current cart weight.`
Note that those last 2 variables, it DOES NOT come with the "%" along with the value.
> add four new read-only variables to eventMacro

- src/Network/Send/fRO.pm
> fix-missing-import-fRO.pm

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/bRO.pm
also patches skill_used_no_damage packstring for bRO serverType
> Move monster_hp_info_tiny (0A36) to serverType0

- src/AI/CoreLogic.pm
> remove unconstructive code

- control/config.txt
- src/Commands.pm
- tables/bRO/control-br/config.txt
stat_add kept for backwards-compatibility
fix statsAdd_over_99
default statsAdd_over_99 to true
> Make st cmd consistent with skills cmd (stat_add moved to st add)

- plugins/profiles/profiles.pl
We don't need to ask which profile to use if none but the control folder are available
> Chose control folder automatically if no other profile is found

- src/Commands.pm
https://github.com/OpenKore/openkore/issues/1027
> Fix due to #1027

- perltidyrc
- src/Commands.pm
Add a suggested perltidyrc which will format correctly.
> fix whitespace, add suggested perltidyrc

- src/Misc.pm
- src/Network/Receive/ServerType0.pm
- repair sex for iRO renewal & odin ( different sex on same account fixed )
- add sex & map on charSelectScreen
http://forums.openkore.com/viewtopic.php?f=36&t=212126
> repair sex for iRO renewal & odin; add sex & mapname on charSelectScreen

- src/Network/Receive/ServerType0.pm
show negative exp when die and show exp gained when level up
> negative exp

- src/Network/Send/ServerType0.pm
small remake to sendIdentify
reference:
#1050 
credits:
@c4c1n6kr3m1
> small-remake-sendIdentify

- plugins/eventMacro/eventMacro.pl
ref: https://github.com/OpenKore/openkore/pull/1071
> Using arr for console param in eventMacro plugin

- plugins/item_weight_recorder/item_weight_recorder.pl
Getting arrows from storage while they are equipped triggers an inventory and weight change in the opposite order, then another weight packet for the same weight, which resulted in the arrows being assumed to be zero weight. This pull request ignores changes to equipped items (which should only affect arrows).
In addition, map changes would sometimes change an item to zero weight for unknown (to me) reasons. This pull request adds a timeout between inventory changes and weight changes to hopefully eliminate that issue.
> prevent some item_weight_recorder false positives

- plugins/eventMacro/eventMacro/Runner.pm
Support nested blocks in eventMacro. This pull request does not attempt to clean up `if` handling (and maybe `switch` handling too?), but it seems likely that some of if/elsif/else logic could be handled in a similar way.
This was tested with the following macros, which work correctly:
```
macro test_wi {
$i = 0
while ($i < 3) {
log $i
$j = 0
if ($j < 3) {
log $i.$j +
}
if ($j > 3) {
log $i.$j -
}
$i++
pause 0.1
}
}
macro test_ww {
$i = 0
while ($i < 3) {
log $i
$j = 0
while ($j < 3) {
log $i.$j
$j++
pause 0.1
}
$i++
pause 0.1
}
}
```
> eventmacro: handle nested blocks

- src/Network/Receive.pm
> deal hooks

- src/Network/Receive.pm
added deal cancelled and complete deal hooks.. sorry i forgot
> update deal hooks.

- src/Network/Receive/ServerType0.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/bRO.pm
> [bRO] Fix pet capture

- plugins/eventMacro/eventMacro/Condition/MobNearDist.pm
- plugins/eventMacro/eventMacro/Condition/NpcNearDist.pm
- plugins/eventMacro/eventMacro/Condition/PlayerNearDist.pm
Just a small fix on eventMacros conditions
> Fix player near dist condition

- src/Settings.pm
How to reproduce: use command line --tables for any server using addTableFolders in servers.txt
> fix --tables for servers with addTableFolders

- control/items_control.txt
done this change using this little amateur script: https://gist.github.com/Nipodemos/483a8f57e491a7ba59c668b855c0c890
(which gave me a lot more difficult to make than i though :roll_eyes: )
unfortunaly, it doesn't get all the ids, some i know the reason, others i dont
and i do not want to change manually the last two hundred items
> Items control.txt Substitue name for ID

- src/Network/Receive/fRO.pm
- src/Network/Send/fRO.pm
fRO !  bot work ! 
I'm wrong
```
Edit : Make everything smaller. For lazy people like me
FIX : npc talk on xkore3 
```
`my discord : sctnightcore#1063 `
xKORE 3 WORK!
> fix network fRO !

- tables/servers.txt
> fix fRO new ip !

- src/Misc.pm
This will allow plugins to modify prices of selling items.
> Add vending hook

- src/AI/CoreLogic.pm
implemented Task::SkillUse in processSkillUse
> taskSkillUse in processSkillUse

- src/AI/CoreLogic.pm
Reverts OpenKore/openkore#1154
Should fix #1275 for now, until we figure out what else went wrong (aside from #1272)
> Revert "taskSkillUse in processSkillUse"

- src/Base/Ragnarok/CharServer.pm
- src/Network/Receive/iRO.pm
Fix for male char and unknow map in iRO/bRO
Character Server:
Map Server:
> xkore 2 fix male character in iRO

- src/AI/CoreLogic.pm
after a few minutes wasted just to update my fork, i finnaly was able to make a Pull Request 😅 
this fix a bug when this hook is called by eventMacro, whitout this fix, macro get on a loop, of getting orphaned, trying again to trigger and getting orphaned again
this fix #1325
> AI_buy_auto_done fix

- tables/bRO/control-br/items_control.txt
update items_control.txt of control_BR folder
> items_control_BR

- tables/bRO/portals.txt
As reported by RafaelO
There's like ~50 bots stuck in moc_fild20 it's really funny
> [bRO] Fix getting stuck in moc_fild20

- tables/fRO/quests.txt
> update tables for fRO

- src/Commands.pm
New features:
* party kick by name
* party leader by name
* party share, shareitem and sharediv with no arguments show what's the current setting
* party info is a new alias for party with no arguments
* party info now shows info about sharing
Bug fixes:
* all-numerical char names are properly supported, just use "quotations"
* party share, sharediv and shareitem keep previous changes made
Enhancements:
* If we find out we're the party leader, exit the lookup loop
> cmdParty review

- src/Misc.pm
- src/Network/Send/bRO.pm
fix character delete accept in bRO
> bRO char delete accept fix

- src/Network/Send/iRO.pm
update in iRO handler to #1374 work
> update in iRO handler

- src/AI/CoreLogic.pm
- src/Actor.pm
- src/Actor/You.pm
- src/Commands.pm
- src/Interface/Wx.pm
- src/Misc.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/XKore2/MapServer.pm
- src/functions.pl
> Prevent $char->{party} autovivification when checking whether we're in a party

- plugins/needs-review/iff/trunk/iff.pl
I don't know of anyone that uses this plugin, but we should keep it consistent
> Follow up to #1409

- src/Network/Send.pm
- src/Network/Send/bRO.pm
- src/Network/Send/iRO.pm
Correct key is charID, not CharID
> Hash typo in reconstruct_char_delete2_accept

- src/Network/Receive/kRO/RagexeRE_2015_11_18a.pm
- src/Network/Receive/kRO/RagexeRE_2015_11_25d.pm
- src/Network/Receive/kRO/RagexeRE_2015_12_02.pm
- src/Network/Send/kRO/RagexeRE_2015_11_25d.pm
- src/Network/Send/kRO/RagexeRE_2015_12_02.pm
```
1. miss sTrecv 20151118a miss
2. update new sT 2015-11-25dRagexe
```
> [Pserver]Fix,update new sT

- tables/servers.txt
Fixed sendCryptKeys incorrect sequence (key1,key3,key2)
> Fixed sendCryptKeys incorrect sequence

- tables/iRO/Restart/portals.txt
prt_maze corrected portals.
Comment "moc_fild11 377 197 moc_fild20 36 177". Doesnt exist, and dont permite openkore acess "moc_fild11 379 197 moc_fild15 38 105"
Comment moc_fild20-22 because doesnt exist.
> Correct prt_maze portals. And some fix.

- tables/bRO/portals.txt
this complements the pull request that was made an hour ago by @BottlerPB
> add second kafra teleports on bRO portals.txt

- tables/fRO/quests.txt
**Data** : 2017-12-5data_txt.gpf
Update only quests
> [fRO_tables_Update]

- src/Network/Receive/bRO.pm
> [bRO] Fix imports

- tables/servers.txt
> new ip for iRO_loki server

- src/Network/XKoreProxy.pm
update account_server_info in xkoreproxy to support year 2015+ private servers
> update account_server_info in xkoreproxy

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/bRO.pm
Move 09CB and 09E5 to Receive::ServerType0 (from Receive::bRO)
Rename shop_sold2 to shop_sold_long (0x9e5)
Add some more info to vending_item_sold hook
Add 'packetType' to vending_item_sold, so we can tell apart the hook called by shop_sold and by shop_sold_long
Change the item sold message a bit.
> Some network stuff

- src/Utils/DataStructures.pm
Removes all occurrences of an element in an array. Returns an array with all positions where it was found.
(used in an upcoming PR)
> Add binRemoveAllAndShift

- src/Misc.pm
- src/Network/Receive/ServerType0.pm
Change 'vending_item_sold' (long) so buyerCharID sends packed charID 
Add 'shop_closed' hook
> Shop related hooks

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/cRO.pm
- src/Poseidon/RagnarokServer.pm
- tables/servers.txt
* update in poseidon to cRO
* add support packet 082D
* removed old china server (died)
* updated account_server_info packet
>  Some updates in cRo related files

- src/Utils.pm
Just like getFormattedDate, but returns Year-Month-Day
(Used in an upcoming PR)
> Add getFormattedDateShort

- control/items_control.txt
- tables/bRO/control-br/items_control.txt
this PR changes this
is an important item to make Acid Bomb, great for farming
> Fabric shouldn't be sold on NPC

- src/Utils.pm
Jan was the 0th month, now it's the 1st, and so on.
> Fix month in getFormattedDateShort

- control/config.txt
- src/AI/CoreLogic.pm
- tables/bRO/control-br/config.txt
buyAuto and sellAuto already have standpoints, this adds the same functionality to storageAuto
> Add storageAuto_standpoint

- src/Network/Receive/cRO.pm
now openkore show the correct number of servers
> cRO update in parse_account_server_info unpack

- README.md
update servers table in readme.me
> update readme (servers)

- src/FileParsers.pm
- src/Misc.pm
Fix writeDataFileIntact2 taking away comments and empty lines (using the timeout command without this PR destroys timeouts.txt)
Support autoCreate and silent in setTimeout
Add hook setTimeout
> Timeouts file modify

- src/Utils.pm
0 -> Year-Month-Day
1 -> Hour:Minute:Second
2 -> \&getFormattedDate
Use sprintf in getFormattedDate instead of concatenation + ifs
Used in #1553
> Add modes to getFormattedDateShort

- control/items_control.txt
i made the pull request for him, authorized on #1571 
this closes #1571
> fix items ID's on items_control.txt (made by @TheDrakenZ)

- tables/bRO/itemsdescriptions.txt
Because @alisonrag is a trigger-happy havoc
> [2018-01-09] [bRO] Tables update

- src/Network/Send/kRO/RagexeRE_2014_01_15e.pm
- src/Network/Send/kRO/RagexeRE_2014_02_05b.pm
- src/Network/Send/kRO/RagexeRE_2015_05_13a.pm
- src/Network/Send/kRO/RagexeRE_2015_09_16.pm
- src/Network/Send/kRO/RagexeRE_2015_10_01b.pm
- src/Network/Send/kRO/RagexeRE_2015_11_04a.pm
- src/Network/Send/kRO/RagexeRE_2015_11_25d.pm
- src/Network/Send/kRO/RagexeRE_2015_12_02.pm
- src/Network/Send/kRO/RagexeRE_2016_01_06a.pm
- src/Network/Send/kRO/RagexeRE_2016_02_03a.pm
- src/Network/Send/kRO/RagexeRE_2016_07_06c.pm
- src/Network/Send/kRO/RagexeRE_2016_12_07e.pm
- src/Network/Send/kRO/RagexeRE_2016_12_28a.pm
- src/Network/Send/kRO/RagexeRE_2017_01_25a.pm
- src/Network/Send/kRO/RagexeRE_2017_04_12a.pm
- src/Network/Send/kRO/RagexeRE_2017_04_19b.pm
- src/Network/Send/kRO/RagexeRE_2017_04_26d.pm
- src/Network/Send/kRO/RagexeRE_2017_05_17a.pm
- src/Network/Send/kRO/RagexeRE_2017_06_07c.pm
- src/Network/Send/kRO/RagexeRE_2017_06_14b.pm
- src/Network/Send/kRO/RagexeRE_2017_07_26c.pm
- src/Network/Send/kRO/RagexeRE_2017_09_13b.pm
- src/Network/Send/kRO/RagexeRE_2017_09_20b.pm
- src/Network/Send/kRO/RagexeRE_2017_09_27b.pm
- src/Network/Send/kRO/RagexeRE_2017_10_02c.pm
- src/Network/Send/kRO/RagexeRE_2017_10_11b.pm
- src/Network/Send/kRO/RagexeRE_2017_10_18a.pm
- src/Network/Send/kRO/RagexeRE_2017_10_25b.pm
- src/Network/Send/kRO/RagexeRE_2017_11_01b.pm
item_list_res to item_list_window_selected
> fix pServer 

- src/Network/Receive.pm
This behavior can be observed by consuming items such as 14591 (Siege Map Teleport Scroll) and 14582 (Yellow Butterfly Wing)
> Create Task::TalkNPC if not active in npc_talk_responses

- control/config.txt
- src/AI/CoreLogic.pm
- src/Task/MapRoute.pm
- tables/bRO/control-br/config.txt
Title
Now users will be able to activate and de-activate these features using config keys
> add config settings for missing portals

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/Zero.pm
- src/Network/Send/Zero.pm
* DISCORD_ROOM : https://discord.gg/geDqWVb
* exp packet fix
* party packet fix
* eq party update
> kRO zero packets update

- src/AI/CoreLogic.pm
- src/AI/Slave.pm
- src/Misc.pm
in AI::CoreLogic and AI::Slave
> Missing nameID in mon_control call

- plugins/xConf/xConf.pl
Fix "set to" message
Prioritize already existing config
Use parseReload instead of running reload command
Support item ID (pconf)
priconf: respect !include
> xConf changes

- src/Network/Receive/kRO/Distfiles
- src/Network/Send/kRO/Distfiles
> miss Distfiles.

- tables/fRO/maps.txt
**DATA : 2018-1-25data_txt.gpf**
> fRO_UPDATE

- src/Actor/Item.pm
i spent almost have a hour analising e testing using the ID of item just for realize long after that only supports bindID or name of item
(just noticed because of lututui) haaha
> comment fix

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/Zero.pm
- src/Network/Send/Zero.pm
kRO Zero freeze character everytime when login in a map-server.
this pull remove this restriction
especial thanks to jun and asheraf
> [kRO Zero] fix freeze char when login/change map 

- plugins/needs-review/webMonitor/trunk/webMonitorServer.pm
> Fix Drop 1 in webMonitor for unusable, usable and unequipped items

- src/Network/Send/idRO.pm
> FIX Eq in idRO_RE

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/Zero.pm
- src/Network/Receive/cRO.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/Zero.pm
- src/Network/Send/cRO.pm
move kRO Zero and cRO packets and parsers to st0, Receive.pm and Send.pm
> Clean servertype kRO Zero and cRO

- src/AI/CoreLogic.pm
itemsMaxNum_sellOrStore would only trigger autosell
> Fix itemsMaxNum_sellOrStore

- src/Poseidon/servertypes.txt
add new kRO Zero st to poseidon
startRO param:
`1rag1 -t:OpenkoreToken account G RagnarokZero /account:openkore.xml`
> [kRO Zero] add new st to poseidon

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
update in hotkeys packet to support new packet and work with future xkore 2 update
07D9 packet:
0A00 packet:
> Hotkeys packet Update

- src/Network/Receive/Zero.pm
Update in kRO Zero handlers to work with new xkore 2 coming update
> [kRO Zero] handlers Update

- src/Base/Ragnarok/AccountServer.pm
- src/Base/Ragnarok/CharServer.pm
update in Account Server to allow login based in token [kRO Zero]
startRO param:
`Ragexe.exe 1rag1 -t:OpenkoreToken accountName G RagnarokZero /account:openkore.xml`
where 
OpenkoreToken need to be equal to config adminPassword
and
accountName need to be equal to config username
> [Base] AccountServer

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
add account server info packet and move with sync to Receive.pm
> [Receive] account server info and sync update

- src/Poseidon/RagnarokServer.pm
poseidon to work with latest kRO Zero Client
> some update in poseidon

- src/Network/Receive.pm
reconstruct update necessary to xkore 2
> [Receive] Reconstruct Account Server Update

- src/Network/Receive/Zero.pm
update zero handlers to xkore 2
> [kRO Zero] update handlers to xkore 2

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
add len to chat_info to send when reconstruct this packet (xkore2)
> [Packet] chat_info update len

- src/Network/Receive.pm
add len to actor to use when reconstruct
> [Receive] actor length

- src/Network/DirectConnection.pm
- src/Network/Receive.pm
- src/Task/TalkNPC.pm
Reverts OpenKore/openkore#1772
Caused problems to some plugins, will re-implement later without messing with those plugins
> Revert "[TalkNPC] fix getting stuck when disconnected"

- tables/portals.txt
Issues #143
code from @hendra814
> Fix issues 143

- tables/bRO/portals.txt
- tables/iRO/maps-custom.txt
- tables/portals.txt
> Portal dewata & lasagna

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
move some identical functions related to actor from st0/sakexe0 to Receive.pm
actor_muted is already implemented in stat_info in st0 and sakexe_0
> [Receive.pm] move some identical  actor functions

- src/Network/Send/Zero.pm
> kRo:Zero public chat

- src/Network/Send/Zero.pm
Reverts OpenKore/openkore#1852
i request revert for this pull, all you need is add the packet to handle:
```
my %handlers = qw(
item_use 0439
token_login 0825
send_equip 0998
master_login 0ACF
public_chat 00F3
);
```
> Revert "kRo:Zero public chat"

- src/Network/Receive/kRO/Sakexe_0.pm
> add sendBanCheck after 099D

- src/Network/Receive/fRO.pm
> fix issues #1840

- tables/portals.txt
> Portal [izlude to lasagna, lasagna to izlude ,lasagna to malangdo  ]

- src/Settings.pm
Implementing: setMonControlFilename and setShopFilename
> Implementing:setMonControlFilename,setShopFilename

- src/Network/MessageTokenizer.pm
fix bug https://github.com/OpenKore/openkore/issues/1923#issuecomment-379801881
> fix MessageTokenizer.pm

- tables/packetlist.txt
added the packet list into tables folder, to help people looking to know what each packet does.
> [tables] packet list

- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
based on lututui suggestion and branch
> [ Send ] hotkey_change 02BA

- src/Network/Send/ServerType0.pm
> [ Send ] fix send entering vending

- src/Commands.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
- tables/servers.txt
Issues #1970
*Support TitleID
*New packet send / Recv on TitleID
TEST
> Support TitleID / New packet = 0A2E,0A2F

- plugins/eventMacro/eventMacro/Utilities.pm
simple fix to make an eventMacro i am doing to work correctly
> [eventMacro]change &monster() keyword to work properly

- control/mon_control.txt
- src/Network/Receive.pm
- src/Network/Receive/kRO/RagexeRE_2014_01_15e.pm
- tables/bRO/control-br/mon_control.txt
Issues : #1890
**OLD**
**FIXED**
```
merc status
-------------------------------- Slave Status --------------------------------
Name: Mimic                       HP: 6120/6120 (100.00%)
Type: Unknown                     SP:   187/187 (100.00%)
Job:
Level: 51                                   Kills: 0
Atk:  1047     Matk:      204     Hunger:        N/A
Hit:   276     Critical:   37     Faith:           0
Def:    10     Mdef:       40     Accessory:     N/A
Flee:  272     Aspd:      150     Summons:         0
Range:   2     Skill pt:  N/A     Contract End:  May 19 20:2
Statuses:  
------------------------------------------------------------------------------
```
**Test**
> Support NPC_MERSOL_TYPE

- src/AI/CoreLogic.pm
Slave move to calculated coordinate even when master is found on its way; resulting slave to going back and forth. This PR fix this. #1953
> Fix Bug Follow Master

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
PR : https://github.com/HerculesWS/Hercules/pull/2063
Thanks to **Hercules Dev Team**.
> PetEvoPacket ! 

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/XKoreProxy.pm
0AC4, 0AC5 and 0AC7 support
cRO handlers
cRO xKore 3 test:
iRO xKore 3 test:
bRO xKore 3 test:
cRO xKore 0 test:
iRO xKore 0 test:
bRO xKore 0 test:
> [Network] xKore 3 new packets support

- src/Network/Receive/kRO.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> fix import bug caused by code clean

- plugins/eventMacro/eventMacro/Runner.pm
Sorry about that, when i pasted i forgot this little part :worried:
> forgot to define var on sub

- src/Network/XKoreProxy.pm
Fix ip resolution in private servers
> [XKore 3] fix ip resolution

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/XKoreProxy.pm
HercPR : https://github.com/HerculesWS/Hercules/pull/2095
* Add 0A4C to XkoreProxy
* Add 0A4C/0A4b to sakexe_0 / Servertype0
ty to HercDev
> Newpacket!  0A4C/0A4B

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/cRO.pm
fix freeze char when change map.
merge map_change and map_changed
> [cRO] fix freeze char

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> Packet of PetEvo is wrong . 

- plugins/eventMacro/eventMacro/Runner.pm
now, you are able to return hashs and arrays from any sub on eventMacro.
the better way is to return a reference to the hash or array, but supports too if you return on normal way.
Additionally, you can set an array of any macro keywork command, in test i've used `&inventoryType` and were created an array with all indexes that keyword returns
also works if there is only one value, no problem
```perl
exclusive 1
run-once 1
BaseLevel > 0
priority -5555
macro_delay .5
call {
log calling sub getHash
%infos = getHash()
log lenght of \%infos: %infos
log calling sub getArray
@fruits = getArray()
log lenght of \@fruits: @fruits
log calling sub getScalar
$var = getScalar()
log value of scalar \$var : $var
log creating array of inventoryType etc
@itens = &InventoryType(etc)
do eval …
```
> [eventMacro] return array or hash from sub of eventMacro

- src/Network/Receive.pm
> [Receive] Fix party_chat

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2013_03_20.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Receive/rRO.pm
iden**fiti**ed -> iden**tifi**ed
> Typo in item parsing

- src/Network/Receive.pm
This caused 'online' info never to be updated
> Fix typo in party_join

- src/Network/Receive/kRO/Distfiles
- src/Network/Receive/kRO/RagexeRE_2017_11_15a.pm
- src/Network/Receive/kRO/RagexeRE_2017_11_22b.pm
- src/Network/Receive/kRO/RagexeRE_2017_11_29a.pm
- src/Network/Receive/kRO/RagexeRE_2017_12_06a.pm
- src/Network/Receive/kRO/RagexeRE_2017_12_13b.pm
- src/Network/Receive/kRO/RagexeRE_2017_12_20a.pm
- src/Network/Receive/kRO/RagexeRE_2017_12_27a.pm
- src/Network/Send/kRO/Distfiles
- src/Network/Send/kRO/RagexeRE_2017_11_15a.pm
- src/Network/Send/kRO/RagexeRE_2017_11_22b.pm
- src/Network/Send/kRO/RagexeRE_2017_11_29a.pm
- src/Network/Send/kRO/RagexeRE_2017_12_06a.pm
- src/Network/Send/kRO/RagexeRE_2017_12_13b.pm
- src/Network/Send/kRO/RagexeRE_2017_12_20a.pm
- src/Network/Send/kRO/RagexeRE_2017_12_27a.pm
RagexeRE_2017_11_15a,RagexeRE_2017_11_22b,RagexeRE_2017_11_29a,RagexeRE_2017_12_06a,RagexeRE_2017_12_13b,RagexeRE_2017_12_20a,RagexeRE_2017_12_27a
> New sT 20171115 - 20171206

- plugins/eventMacro/eventMacro/Core.pm
> [eventMacro] Forbid the use of spaces in macro and automacro names

- tables/bRO/control-br/buyer_shop.txt
- tables/bRO/control-br/config.txt
- tables/bRO/control-br/timeouts.txt
> add buyer to config bRO

- src/Misc.pm
as reported by @lehotf in 
https://github.com/OpenKore/openkore/pull/2119#issuecomment-403325784
> fix total items

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/iRO/Renewal.pm
- src/Network/Send/iRO.pm
- src/Network/Send/iRO/Renewal.pm
- tables/servers.txt
> [iRO] Unfreeze char after map loaded

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Skill message rework.
updated to work with private server
Based in #95
> [Receive] Skill message rework

- src/Commands.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
Fix #1725
* Happy Break (Pausa Feliz) triggering:
> Send Novice Dori Dori on cmdDoriDori

- src/Network/Receive/ServerType0.pm
> [0x02CE] Debug-squelch instance_window_leave update

- tables/idRO/itemsdescriptions.txt
before:
https://media.discordapp.net/attachments/295016653320880128/471437577023651881/unknown.png
after:
> [Tables] Fix itemdescription encoding

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
All merged methods are **identical**
> [Receive] Merge some identical methods from Sakexe0 and ServerType0

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
Herc PR : https://github.com/HerculesWS/Hercules/pull/1998
rA PR : https://github.com/rathena/rathena/pull/3354
* Add new packet of Private airship [0A4A (ZC) /0A49 (CZ)]
* Add to sakexe_0 for test ! 
**Thanks to rA dev / Herc dev** ♥
> Private airship [ Packet ]

- README.md
Let users know more on how to use the method mentioned.
> Added git clone command for guidance

- src/AI/CoreLogic.pm
Example: 
```
getAuto 501 {
minAmount 0
maxAmount 50
}
```
> [getAuto] Support nameID

- plugins/needs-review/webMonitor/trunk/webMonitorServer.pm
After perl 5.14.4 defined @array was depriciated as it was a bug in perl. This should work on 5.14.4+
> fixed defined array depriciated

- plugins/eventMacro/eventMacro/Core.pm
- plugins/eventMacro/eventMacro/FileParser.pm
this simply check if exist a macro or automacro that have the same name and ignores it
> [eventMacro] check duplicated macro and automacro names

- plugins/eventMacro/eventMacro/Runner.pm
sublines unfortunaly doesn't work quite well, and almost no one use this function
so, it is better to kill this function, then it will be possible to do for loop on eventMacro
tested and worked with no erros
tested with a giant eventMacro and worked without erros
> [eventMacro] removing everything about sublines

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
rA PR : rathena/rathena#3365
ty to @Lemongrass3110, @sctnightcore 
follow up #2208
> [Network] Guild storage log Packet

- plugins/eventMacro/eventMacro/Core.pm
```perl
$.inlockmap # if you are in your lockmap, then value is 1, otherwise is 0
$.inventoryitems # value the how many items you have on inventory, otherwise is 0
$.shopopen #if shop is opened, value is 1, otherwise is 0
```
tested and workink perfectly
> [eventMacro]trhee new read-only variables

- src/Network/XKoreProxy.pm
this pull fixes #2232 
cRO test:
bRO test:
> [Network] fix xkore proxy ip connection

- src/Network/Receive.pm
> Add hook 'invalid_password'

- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/bRO.pm
- src/Network/Send/cRO.pm
- src/Network/Send/iRO.pm
- src/Network/Send/kRO/Sakexe_0.pm
- src/Network/Send/kRO/Sakexe_2004_11_09a.pm
- src/Network/Send/kRO/Sakexe_2005_03_28a.pm
- src/Network/Send/kRO/Sakexe_2005_05_30a.pm
- src/Network/Send/kRO/Sakexe_2005_06_08a.pm
- tables/servers.txt
Flags a server that uses rank_general instead of rank_killer, rank_taekwon, rank_alchemist, rank_blacksmith
> Create a rankingSystemType in servers.txt

- src/Base/Ragnarok/CharServer.pm
- src/Misc.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/cRO.pm
- src/Network/Receive/iRO.pm
- src/Network/Receive/idRO.pm
- src/Network/Receive/idRO/Renewal.pm
- src/Network/Receive/kRO/RagexeRE_2008_12_17b.pm
- src/Network/Receive/kRO/RagexeRE_2011_08_16a.pm
- src/Network/Receive/kRO/RagexeRE_2013_03_20.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Receive/pRO.pm
- src/Network/Receive/tRO.pm
- src/Network/Receive/twRO.pm
Rework in received_characters subs, now is more dinamic, use less code and will be easy to update
This will affect received_characters, charBlockSize, character_creation_successfull and xKore 2 map-server
Tested in bRO, iRO ReStart and kRO_RagexeRE_2017_06_14b
bRO:
iRO:
this fixes #2296
> [Network] received_characters rework

- src/Commands.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
> Network cleaning

- src/Network/XKoreProxy.pm
As reported here:
http://openkorebrasil.org/index.php?/topic/4840-dúvida-eventmacros-em-modo-xkore-3/?p=39164
> [Network] Fix missing ip conversion from bytes to string in xKoreProxy

- src/Network/Receive.pm
- src/Network/Receive/iRO/Renewal.pm
- tables/servers.txt
update received_characters_info to work with iRO Renewall
tested in bRO, iRO (Re:Start, Renewall, Classic)
> [Network] update received_characters_info

- src/Network/Receive/idRO.pm
> Update Packet !

- tables/packetlist.txt
update packet list, names and dates
used script:
https://github.com/alisonrag/Openkore-Plugins-Scripts/tree/master/%5BSCRIPT%5D%20Create%20Packet%20List%20Openkore-Hercules
> [tables] Update packet list

- src/Network/Receive.pm
I'm returning this sub to the original, cause the current dont work as we expect
Tested in bRO, cRO, iRO (re:start, classic and renewall), FuryRO.
reported here:
https://github.com/OpenKore/openkore/issues/2300#issuecomment-416984418
> [Network] rollback received_characters_info to original

- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
add missing len to chat_room_create
this fixes #2313
> [Network] add missing len to chat_room

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2008_08_27a.pm
- src/Network/Receive/kRO/RagexeRE_2008_09_10a.pm
- src/Network/Receive/kRO/RagexeRE_2008_11_12a.pm
- src/Network/Receive/kRO/RagexeRE_2008_12_17a.pm
- src/Network/Receive/kRO/RagexeRE_2008_12_17b.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Network / Receive] Clean 2008 ragexeRE files

- plugins/eventMacro/eventMacro/Condition/ConfigKey.pm
- plugins/eventMacro/eventMacro/Condition/ConfigKeyNot.pm
those two conditions somentimes were not evaluating key and value correctly, resulting in being true at wrong times, this PR change that
> [eventMacro] change ConfigKey and ConfigKeyNot Conditions

- src/Network/Receive/fRO.pm
- tables/servers.txt
> [Network] update fRO to work with new received_characters

- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
> Fix chat room change

- src/Misc.pm
- src/Network/Receive.pm
> Use map desc name in selection screen (up to 16 chars)

- src/Network/Receive.pm
> Fix incorrect unpack string in area_spell_multiple2 and area_spell_multiple_3

- src/Network/Receive/kRO/RagexeRE_2011_08_16a.pm
Add base for RagexeRE_2010_12_28a and a proper closing for sub new.
> Fix missing base

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2013_03_20.pm
- src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
- src/Network/Receive/kRO/RagexeRE_2016_12_07e.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Fix inventory and vending item parse.
As reported here:
http://openkorebrasil.org/index.php?/topic/4997-assertion-failed/
Before:
After:
Entering in vending
> [Network] Fix related items error (inventory and vending)

- src/Commands.pm
Command was unusable when search without price or cards
> Fix searchstore command

- src/AI/CoreLogic.pm
As proposed by Mr. Burns [here](http://openkorebrasil.org/index.php?/topic/5034-pet-feed-sugest%C3%A3o-modo-manualdesligado-alimentando-pet/)
> Keep autofeeding on when ai manual

- plugins/eventMacro/eventMacro/Automacro.pm
on my last pull request i've cleaned a lot of imports, and this shoud NOT be deleted
Sorry for my mistake
```
Error message:
Undefined subroutine &eventMacro::Automacro::timeOut called at plugins/eventMacro/eventMacro/Automacro.pm line 271.
```
> fix missing import

- plugins/eventMacro/eventMacro/Condition/BaseActorNotNear.pm
- plugins/eventMacro/eventMacro/Condition/BaseInInventory.pm
- plugins/eventMacro/eventMacro/Condition/GuildMsgName.pm
- plugins/eventMacro/eventMacro/Condition/InCartID.pm
- plugins/eventMacro/eventMacro/Condition/InInventoryID.pm
- plugins/eventMacro/eventMacro/Condition/InStorageID.pm
- plugins/eventMacro/eventMacro/Condition/MobNear.pm
- plugins/eventMacro/eventMacro/Condition/MobNearDist.pm
- plugins/eventMacro/eventMacro/Condition/NpcNear.pm
- plugins/eventMacro/eventMacro/Condition/NpcNearDist.pm
- plugins/eventMacro/eventMacro/Condition/PartyMsgDist.pm
- plugins/eventMacro/eventMacro/Condition/PlayerNear.pm
- plugins/eventMacro/eventMacro/Condition/PlayerNearDist.pm
This will be the last one, i promise
> add a few imports that i've forgot

- tables/servers.txt
Openkore is sending sync received char before then receive char, this make openkore cant select character on 4th slot or more
now openkore wait for a while before send sync
this fixes:
#2431
> add pauseCharLogin to idRO

- src/Network/Receive/ServerType0.pm
`idRO_Renewal` also need `sendRequestCashItemsList` on `map_loaded` or it will crash on `cash list` command
> Fixed Cash Shop items aren't listed

- tables/servers.txt
We have moved to a better host provider.
Include improved ddos protection.
> Server IP update

- src/Network/Receive/ServerType0.pm
Wrong usage of `qw` for comparing server type
> Follow up 239c6ecc38515ec83f826cd5ca73504eee95ec5b

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
check Herc PR : https://github.com/HerculesWS/Hercules/pull/2310
Thanks Herc dev ♥
Need to be test.
> add packet 0AFD

- src/Network/Receive.pm
Just matched string by regex can be used using special variable
> system_chat regex

- src/Network/Receive/idRO/Renewal.pm
idRO_Renewal not using packet with options yet
> Fixed vender list crash

- src/Commands.pm
- src/Network/Receive.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
> [bugfix] Fix send buy bulk buyer

- tables/servers.txt
* Set rankingSystemType to 1 for idRO_Renewal
* new line for EOL
> Set rankingSystemType to 1

- tables/idRO/items.txt
- tables/idRO/itemsdescriptions.txt
- tables/idRO/quests.txt
* idRO_Renewal for MT 2018-11-27
>  Updates idRO tables

- tables/idRO/items.txt
- tables/idRO/itemsdescriptions.txt
- tables/idRO/quests.txt
* idRO_Renewal for MT 2018-12-05
> Updates idRO Tables

- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
HERC PR : https://github.com/HerculesWS/Hercules/pull/2324
ty to @4144 / Herc dev 
**Allow edits from maintainers**
> PACKET 0B10/0B11

- src/FileParsers.pm
> fix pickupitems parse

- src/Network/Receive/kRO/RagexeRE_2015_11_04a.pm
https://github.com/OpenKore/openkore/blob/503fb03df7b99d5697f08e8af707ab4cd205280c/src/Network/Receive.pm#L6229-L6268
> del sub in RagexeRE_2015_11_04a

- src/Log.pm
> Make "console" domain squelch-able

- src/Network/XKoreProxy.pm
> [xKoreProxy] fix typo

- src/Network/Receive/kRO/RagexeRE_2018_02_21a.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> fix issues 2579

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Crash on being a target of a damaging skill, due to broken Sakexe0 skill_delete handler
> Fix issue #2612

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
PR name. Updated it based on RMS-renewal and bRO-Thor testing
> move vender_buy_fail to receive.pm and updated it

- src/Network/Send/cRO.pm
> [cRO] update char_create packet ID

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> Follow up to #2621

- src/Network/Receive.pm
- src/Network/Send.pm
> Follow up to #2610

- src/Network/Receive/cRO.pm
> [cRO] fix vender items list

- plugins/eventMacro/eventMacro.pl
replaced `override_ai` with `overrideAI`
> fix overrideAI in eventMacro

- tables/idRO/items.txt
- tables/idRO/itemsdescriptions.txt
- tables/idRO/quests.txt
> idRO Updates

- control/items_control.txt
- src/FileParsers.pm
> Fix parsing on enchanted items in items_control.txt

- tables/servers.txt
> Update iRO: Sakray

- src/Network/Receive/kRO/Sakexe_0.pm
> Packet 20180627

- control/config.txt
- src/Network/Receive.pm
- tables/servers.txt
I think use it in all server .
> Move pauseCharLogin to config

- src/Network/XKore.pm
> Allow packet mangle-ing in XKore 1

- src/Actor.pm
- src/ActorList.pm
- src/Base/Ragnarok/SessionStore.pm
- src/InventoryList.pm
- src/Misc.pm
- src/Network/MessageTokenizer.pm
- src/Network/Receive.pm
- src/Settings.pm
- src/Skill.pm
- src/Task/Route.pm
- src/Task/WithSubtask.pm
- src/TaskManager.pm
- src/Utils/CallbackList.pm
- src/Utils/ObjectList.pm
Add descriptions to all assert calls
Switch some assert calls for assertClass and should calls
Closes #426
> Review all Carp::Assert::assert calls

- README.md
Tried to make it simple for anyone to understand.
> [README] FAQ Added.

- src/Utils/Assert.pm
https://stackoverflow.com/questions/204316/why-shouldnt-i-use-universalisa
> Make assertClass stricter

- src/Utils/Assert.pm
> Remove blessed requirement

- src/Actor.pm
- src/Commands.pm
- src/Interface/Wx/StatView/You.pm
Those commands incorrectly show brown hair color on most servers
> Properly show hair color in st and pl commands

- plugins/eventMacro/eventMacro/Condition/ActorNearCount.pm
as discussed earlier, this elsif was missing in this condition, making it not have proper support for variables
> [eventMacro] fix ActorNearCount

- src/Task/TalkNPC.pm
> [talknpc] added error handler

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
♥ @4144 
Herc PR : https://github.com/HerculesWS/Hercules/pull/2468/
> Herc pr/2468

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
Special thanks to https://github.com/idathena/trunk/commit/4bdd552e65a710d0347247aa7c6affe76fc1159a
> Add Packet 0A47 / 0A46

- src/Network/Receive/fRO.pm
This reverts commit 2d24540a6c24266b4f012ae9d5d0a33870698eab.
tested: irc: Botten
> Revert "Update fRO.pm (#2758)"

- control/config.txt
Just added the missing timeout setting in useSelf_item at config.txt
> Added missing timeout in useSelf_item

- src/Commands.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Send/ServerType0.pm
**Packet base IRO:RE**
rA PR : https://github.com/rathena/rathena/pull/3548
ty to rA dev ♥
**Allow edits from maintainers. If you are interested in developing **
```
[Send]
'0A97' => 'equipswitch_add'
'0A99' => 'equipswitch_remove'
'0A9C' => 'equipswitch_run'
'0ACE' => 'equipswitch_single'
```
```
[Recv]
'0A98' => 'equip_item_switch',
'0A9A' => 'unequip_item_switch'
'0A9D' => 'equipswitch_run_res'
'0A9B' => 'equipswitch_log'
```
> EquipSwitch Packet

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Fixes a typo in the packet switch caused by #2785
> Fix typo in quest system cleaning

- src/Network/Receive.pm
This fixes a bug introduced in the recent quest system cleaning where a quest would not be added correctly because quest id was not being set
> Fix quest add

- src/Network/Receive.pm
quest all mission was erasing the quest set by quest all list in bRO, this fixes it.
> Fix quest all mission in bRO

- src/AI/CoreLogic.pm
- src/Commands.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
1) If a Novice (1-3 job lvl) uses the default setting `sitAuto_hp_lower 40` and its HP is reduced to 40%, then the bot just stops and does nothing.
2) If a Novice (1-3 job lvl) uses `sit`command then the bot just stops and does nothing.
I added _NV_BASIC_ check.
> fix 'sitAuto_hp_lower' and 'sit' command for Novice 1-3 job lvl

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
title.
This makes it easier to make plugins that interact with such spells.
> Added more info to areaSpell hook

- src/Network/Receive.pm
> Add Time::HiRes import in receive.pm

- src/Network/Receive.pm
- tables/servers.txt
> [Receive] Charblocksize 146

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
added 08FE, 0AFE, 0AFF, 0B0C packets
> [Receive] Quest list update

- plugins/eventMacro/eventMacro/Condition/ShopOpened.pm
> [eventMacro] Add condition ShopOpened

- control/timeouts.txt
- src/AI/CoreLogic.pm
- src/Globals.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
while using xkore 1,3 sometimes kore send ignoreall too early, so sometimes not work.
so im moving this to AI, to wait some seconds before send the command
Now works in xkore 0,1,2,3
> [AI] move ignoreAll to AI

- plugins/alertSound/README.txt
- plugins/alertSound/alertSound.pl
- src/Network/Receive.pm
Small plugin update:
- add new hooks: "item_appeared" and "item_exists"
- add new events: item *<part item name>*
- fixed a bug where the condition "item cards" did not work when using the old package '009E'. Now use the condition: item *Card*, or item *карта*, or item *Carta*, etc.
- add universal "Self Conditions"
> alertSound update

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/bRO.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/bRO.pm
- src/Network/Send/kRO/Sakexe_0.pm
Rodex updated and tested to current version, compatibility with old packets was keeped
result:
> [Feature] Update rodex to current version

- src/Network/Send/idRO/Renewal.pm
- tables/servers.txt
Do not ask more, it's EAC blocked. All you can use is login, see the user online, create a new char :rofl: 
Maybe later will update only the table files which can be extracted from grf and itemInfo.lub
> servers.txt update

- src/Misc.pm
Added the following conditions to checkSelfCondition
```
whenNotIdle
homunculus_onAction
homunculus_notOnAction
homunculus_whenIdle
homunculus_whenNotIdle
mercenary_onAction
mercenary_notOnAction
mercenary_whenIdle
mercenary_whenNotIdle
```
> add checkSelfCondition conditions

- tables/iRO/official/portals.txt
- tables/portals.txt
as @bookbk said [in here](https://github.com/OpenKore/openkore/commit/5b1af26e78475486a9ff37eec9bba6d5631528cb#commitcomment-35385470) , there is some errors on portals.txt from iRO.
Credit goes to him
> fix wrong portals on iRO

- src/Misc.pm
I think this will fix most problems with teleporting with wings/items when inventory is still not loaded.
> [Misc.pm - useTeleport] Inventory state cheking.

- src/Misc.pm
> fix `timeout` in `partySkill` block

- src/Interface/Wx/StatView/You.pm
> [Interface] Wx add Zeny in Status page

- src/AI/CoreLogic.pm
added hooks:
AI_storage_item_out_of_stock
AI_storage_item_full
AI_storage_full
when merged i will update:
http://openkore.com/index.php/Hook
> [coreLogic] add hooks for storage full and item out of stock

- src/InventoryList/Cart.pm
- src/InventoryList/Inventory.pm
- src/InventoryList/Storage.pm
- src/Misc.pm
- src/Network/Receive/ServerType0.pm
- src/functions.pl
> [InventoryList] itemList more support

- src/AI/CoreLogic.pm
- src/Network/Receive.pm
this avoid kore try to buy, sell or storage while buying itens, also closes buying shop after finish the buying
> small-fixes-buyer-shop

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Implemented and updated the offline vending / buying system [ system based in player clone ]
OBS: Only working check, enter and buy/sell system. i not checked/updated the create clone vending / buying system.
> [Feature] Offline System ( Vending / Buying )

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
fix missing unpackstring into buying_store_items_list caused in: #3026
> [Parser] Fix missing unpack string into buying_store_items_list

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
This packet is used when you want to know who created/forged the item
> [Receive] Add 0AF7 (character_name)

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
move party_dead to Receive.pm and update it.
> [Receive] Update party_dead packet (0AB2)

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
"Remake" the guild system
merged duplicated packets
added support to new packets
updated some stuffs
before:
after:
> [Guild] Update functions and add new packets

- src/Network/Receive/ServerType0.pm
remove character_equip not used not used since #789
> [Cleaning] remove character_equip

- src/Network/Receive/tRO.pm
character unpack string is based in charblocksize since #2291
> [tRO] remove character_creation_successful

- tables/servers.txt
Hi. just add euRO server info(not working yet).
> Add euRo server info

- src/test/ShopTest.pm
> test: Fix ShopTest

- src/test/TaskTalkNPCTest.pm
> test: Fix TaskTalkNPCTest

- src/Commands.pm
- src/Globals.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
- src/functions.pl
Implemented Bank System in openkore.
New Commands:
`bank <open|deposit|withdraw>`
New Hooks:
```
banking_opened
banking_deposit_success
banking_deposit_failed
banking_withdraw_success
banking_withdraw_failed
```
thanks @sctnightcore for previous implementation
> [Feature] Bank System

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Receive] Add navigate_to packet

- src/Commands.pm
> [FIX] update check in cmdSit to work with doram class

- src/Network/Receive.pm
> [FIX] Change rodex body print

- src/test/NetworkTest.pm
Hi there, fix NetworkTest, or disable testcases due to obsolete or broken #2785 #3029
> test: Fix or Disable NetworkTest

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Receive] Add packet load_confirm

- .github/workflows/test.yml
Hi there, this is the proposal OpenKore's CI using GitHub Actions. yet another #2790 but GitHub Actions's auth would be easier since it's all in GitHub.
For now the CI make sure to pass  just `make test`.
samples
ok: https://github.com/koooge/openkore/pull/1
ng: https://github.com/koooge/openkore/pull/2
> feat: Add github actions

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Receive] Add a warning to servers with EAC

- plugins/alertSound/README.txt
- plugins/alertSound/alertSound.pl
- add new conditions "isNotParty" - only works with eventList: player ***,  public ***
- add new conditions "notPlayers" - only works with eventList: player ***,  private ***, public ***
> update alertSound plugin

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Previosly: did not work.
Now: it works
> Fix autoResponseOnHeal config

- src/Network/Receive.pm
In some cases a map change can cause the mercenary object to bug and become an Actor::Slave, the same way it happened to homunculus before #2907.
Fixed it and also added a fix for a possible future bug in which servers don't send the mercenary info after a map change, the same way as #3117 did, in case the server sends it nothing changes.
> Fixed mercenary map change

- src/Network/Receive/kRO/Sakexe_0.pm
update inventory_items_nonstackable in Sakexe_0
this pull fixes: #803
result:
> [Fix] Wrong item parse

- src/Network/Send.pm
config:
```lua
debugPacket_include_dumpMethod 2
debugPacket_include 0437
```
with these settings, sent packets are not displayed in the console:
```lua
move 155 96
Calculating route to: Morocc Town(morocc): 155, 96
```
this PR corrects this behavior:
```lua
move 155 96
Calculating route to: Morocc Town(morocc): 155, 96
Encrypted MID : [0437]->[2F6D] / KEY : [0x1769]->[0x2B5A]
================================================
>> Sent packet: 0437  [Character Move] [5 bytes]   Jun 06 01:58:34 2020
0>  6D 2F 26 C6 00                                        m/&..
Encrypted MID : [0437]->[3936] / KEY : [0x2B5A]->[0x3D01]
================================================
>> Sent packet: 0437  [Character Move] [5 bytes]   Jun 06 01:58:34 2020
0>  36 39 26 C6 00 …
```
> fix debugPacket_include_dumpMethod for sent packets

- src/Misc.pm
avoid.txt:
```css
[Players]
ya4ept			0 0 0
```
config.txt:
```css
avoidList 1
```
under these conditions, if the bot sees the player "ya4ept", then an empty message begins to spam on the console:
```
[Jun 06 22:26:32 2020.20] Config 'avoidList' set to 1 (was 0)
[Jun 06 22:26:32 2020.41] 
[Jun 06 22:26:32 2020.94] 
[Jun 06 22:26:33 2020.47] 
[Jun 06 22:26:34 2020.31] 
[Jun 06 22:26:34 2020.52] 
[Jun 06 22:26:35 2020.48] 
[Jun 06 22:26:35 2020.57] 
[Jun 06 22:26:36 2020.10] 
[Jun 06 22:26:36 2020.62] 
[Jun 06 22:26:37 2020.16] 
[Jun 06 22:26:37 2020.68] 
[Jun 06 22:26:38 2020.21] 
[Jun 06 22:26:38 2020.74] 
[Jun 06 22:26:39 2020.28] 
```
> fix avoidList_near

- README.md
> update tRO readme status

- src/Misc.pm
- src/Network/Send.pm
delete small in-game chat control:
https://sourceforge.net/p/openkore/code/8518/
fix of the issue  #1143
> fix sendPrivateMsg

- src/Network/XKoreProxy.pm
> [fix] update xKoreProxy server list

- src/Network/Receive.pm
- src/Task/TalkNPC.pm
clear some variables left after NPCTALK task is destroyed and avoid autovivification
> fix talknpc variables left

- src/AI.pm
- src/AI/CoreLogic.pm
- src/Commands.pm
> [fix] add check to skill lvl in skill use

- src/Task/TalkNPC.pm
this fixes #3208 
after buy/sell AI auto undef the "npc_talk"
> [fix] Avoid delete NPC ai_v while in store or sell

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
this pull fixes: #3198
this pull fixes: #2788
* update the received_characters function to save correct character information
* fix exp function 
EXP in character selection screen:
client:
openkore:
exp gain:
------
zeny before relog:
zeny lost in client:
zeny after relog:
> [fix] update character data

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Update] Packet Message String

- src/Misc.pm
- src/Network/Receive.pm
> [fix] solveMessage itemLink

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
PR #3212 contains a mistake.
we forgot to change '0291' package
> fix '0291' package

- control/config.txt
- src/Network/Receive.pm
this fixes #3036
added config key to log quest progress:
`questDisplayStyle`
quest added:
quest list after login:
quest log progress:
> [fix] quest packets

- src/Commands.pm
fix error: "Argument "\x{63}\x{6c}..." isn't numeric in array element at src/Commands.pm line 6248"
before:
after:
> fix vender commands

- src/Commands.pm
> added "quest" command description:

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/iRO/Transcendence.pm
- src/Network/Send/iRO/Transcendence.pm
fix issue https://github.com/OpenKore/openkore/issues/3278
1. removed unnecessary packages (hese packages are described in ServerType0.pm)
2. add rodex_open_mailbox packet 
3. added a new packet "0A6F". Use this macro for tests:
```
macro chech {
do rodex open
do rodex write Your_name
do rodex settarget YOUR_NAME_IN_CAPITAL_LETTERS
do rodex send
}
```
> fix iRO rodex

- src/Commands.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
- added description to "help achieve" command
- rewrote the cmdAchieve function like cmdQuest
- replaced "ach_id" with "achievementID" for better code search
> revision of the console command "achieve"

- control/config.txt
- src/Network/XKore.pm
This pull add a option so user can choose if he want to inject the dll in xkore 1 mode, usefull for users that use their own method to inject dll
Default is 1 (inject DLL)
> [Connection] xKore add option to inject Dll or not

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- follow up to #3292 
- update default charBlockSize to 155
> [Receive] charBlockSize 175

- src/Misc.pm
- src/Network/Receive.pm
added a function to solve MSG tag at rodex system
before:
after:
> [Receive] rodex solve <MSG>

- control/config.txt
- src/Network/Receive.pm
- now it shows the correct number of days
- added a new config parameter: "attendanceAuto":
https://openkore.com/wiki/AttendanceAuto
https://openkore.com/wiki/Attendance
before:
after:
> fixed attendance_ui function

- src/Network/Receive/Zero.pm
- src/Network/Receive/cRO.pm
fix errors found in "make test"
this will fix some errors in #3138
> [FIX] update incorrect packets

- src/Network/Receive/cRO.pm
nameID changed from 2 bytes to 4 bytes
should fix this: https://github.com/OpenKore/openkore/commit/10b225b64508ab0a7771fa4b37bc048d6ba703ab#commitcomment-47254947
> fix item_appeared

- src/Utils.pm
It was:
`Month Day Hour:Minute:Second Year.microseconds`
```
[Mar 13 01:42:48 2021.11] Loading tables\cities.txt...
```
it became so:
`Year.Month.Day Hour:Minute:Second.microseconds`
```
[2021.03.13 01:42:48 .11] Loading tables\cities.txt...
```
> fixed time format

- src/AI/Attack.pm
- src/AI/Slave.pm
- src/Misc.pm
Title
Before I made 2 subs as I was too lazy to make one sub for both cases, now I merged them together and added a few comments.
Tested for char, homunculus and mercenary, seems to be working fine.
> Merge meetingPosition for char and slaves

- src/Misc.pm
Fixed a typo ($actor -> $target) in meeting position that would make slaves use the character config keys instead. Also added portal avoiding to both slaves and char.
> Fixed slave meetingPosition and added portal avoiding to it

- src/Settings.pm
- src/functions.pl
this partially fixes #3379 
Todo:
load files:
reload control:
reload tables:
reload all:
> [Feature] (re)load files using path

- src/Network/Receive.pm
- src/Network/Receive/RMS.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/RagexeRE_2008_09_10a.pm
- src/Network/Send/kRO/RagexeRE_2010_04_20a.pm
- src/Network/Send/kRO/RagexeRE_2010_11_24a.pm
- src/Network/Send/kRO/RagexeRE_2011_10_05a.pm
- src/Network/Send/kRO/RagexeRE_2013_05_22.pm
- src/Network/Send/kRO/RagexeRE_2014_09_17c.pm
- src/Network/Send/kRO/RagexeRE_2014_10_22b.pm
- src/Network/Send/kRO/RagexeRE_2015_11_18a.pm
- src/Network/Send/kRO/RagexeRE_2015_12_02.pm
- src/Network/Send/kRO/RagexeRE_2017_05_17a.pm
- src/Network/Send/kRO/RagexeRE_2017_07_26c.pm
- src/Network/Send/kRO/RagexeRE_2017_10_02c.pm
- src/Network/Send/kRO/RagexeRE_2017_10_18a.pm
- src/Network/Send/kRO/RagexeRE_2018_04_04b.pm
- src/Network/Send/kRO/RagexeRE_2020_03_04a.pm
- src/Network/Send/kRO/Sakexe_0.pm
- src/Network/Send/kRO/Sakexe_2005_04_25a.pm
- src/Network/Send/kRO/Sakexe_2005_06_08a.pm
- src/Network/Send/kRO/Sakexe_2008_09_10a.pm
```
#if PACKETVER_MAIN_NUM >= 20190227 || PACKETVER_RE_NUM >= 20190220 || PACKETVER_ZERO_NUM >= 20190220
struct PACKET_CZ_PING {
int16 packetType;
} __attribute__((packed));
DEFINE_PACKET_HEADER(CZ_PING, 0x0b1c);
#endif
#if PACKETVER_MAIN_NUM >= 20190227 || PACKETVER_RE_NUM >= 20190220 || PACKETVER_ZERO_NUM >= 20190220
struct PACKET_ZC_PING {
int16 packetType;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_PING, 0x0b1d);
#endif
```
> Add ping packet [0x0b1c] [0x0b1d]

- plugins/profiles/profiles.pl
Remake of #3285
Default:
Plugin Profile:
Choices:
Connecting:
Connected:
> [Update] Added Profile Name to Openkore Title

- control/config.txt
- src/Network/Receive.pm
- src/Network/Receive/pRO.pm
- src/Network/Receive/tRO.pm
allow user ignore anti cheat warning
disabled by default
> [Misc] add ignoreAntiCheatWarning to config

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [Network] Add refine_status packet

- src/Network/Receive/pRO.pm
- tables/servers.txt
pRO/MSP Network Update
this fixes #3400
> [Network] 2021-04-17 pRO (MSP) Update

- control/config.txt
- src/Network/Send.pm
https://github.com/OpenKore/openkore/blob/3657e3ccb79d61c4f7a379a70437bf182b0cb45d/src/Network/Send/ServerType0.pm#L199
> [Network] Add support to mac encryption in packet game_login

- src/Network/Send/iRO/Renewal.pm
should remove %packets loop if %packets have been cleaned.
> [Network / Send] Cleaning Packets part 2 (OpenKore#3382)

- control/config.txt
- src/Network/DirectConnection.pm
- src/functions.pl
adminPassword "xxxxxxxxxx" no longer topical
> code cleanup

- control/config.txt
- src/Network/Receive.pm
- tables/servers.txt
https://openkore.com/wiki/ignoreAntiCheatWarning
https://openkore.com/wiki/Connectivity_Guide
> [misc] move ignoreAntiCheatWarning to servers.txt

- src/AI/CoreLogic.pm
- tables/bRO/control-br/config.txt
- tables/twRO/chinese/control/config.txt
now openkore always check the LOS
follow up to #3363
> remove followCheckLOS

- control/config.txt
add missing keys added at #1662
whenPartyMembersNear
whenPartyMembersNearDist
> add missing partySkill keys

- src/Network/Receive.pm
- src/Network/Send.pm
- tables/servers.txt
[OTP - One Time Password](https://github.com/HerculesWS/Hercules/commit/fde5dcbc12a2b6b5c423a5b96fa384dfee60e670)
> replaced OTT with OTP

- src/Network/Receive.pm
a working plugin using the following hooks:
```
rodex_unread_mail
rodex_mail_list
rodex_mail
rodex_mail_deleted
```
> [Network / Hook] Add more Hooks to Rodex

- control/config.txt
- src/AI/CoreLogic.pm
- tables/servers.txt
1) removed parameters "sellAuto_minDistance" and "storageAuto_minDistance", instead we can use "sellAuto_distance" and "storageAuto_distance"
2) added missing "sellAuto_maxDistance" and "storageAuto_maxDistance" parameters
> fixed autosell and autostorage distance

- control/config.txt
Removed "secureLogin_requestCode" from config.txt.
We already removed this parameter here: #3412
But in #3414 he came back
> code cleanup 2

- src/Network/Send/vRO.pm
don't forget to add vRO_auth plugin to sys.txt
https://openkore.com/wiki/loadPlugins_list
> added check for plugin usage

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/vRO.pm
- src/Network/Send/vRO.pm
- tables/servers.txt
- fixed autosell
- fixed character creation
- add `storage_item_added`
> vRO support

- plugins/vRO_auth/vRO_auth.pl
- changed the hook to get new data every time I reconnect
- added auto logout if serverType is not "vRO"
> vRO_auth plugin update

- control/poseidon.txt
- src/Poseidon/RagnarokServer.pm
- src/Poseidon/servertypes.txt
Add vRO servertype for Poseidon
Modify master and map login for Poseidon vRO
> Poseidon for vRO support

- tables/bRO/elements.txt
- tables/bRO/itemtypes.txt
translate elements.txt
translate itemtypes.txt
> [bRO] translate table files

- src/Network/Receive/Sakray.pm
- src/test/NetworkTest.pm
Added the remaining official servers, also fixed a mismatch in Sakray packets
> [Test] update Network test

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> [fix] update vender_found unpack string

- src/Network/Receive.pm
- src/Network/Receive/kRO/RagexeRE_2020_03_04a.pm
- src/Network/Send/kRO/RagexeRE_2018_04_04b.pm
- src/Network/Send/kRO/RagexeRE_2020_03_04a.pm
- tables/servers.txt
- added new FreeRO server
- fixed "storage_item_remove"
- fixed "vender_items_list_item_pack"
> RagexeRE_2020_03_04a support

- src/Network/Receive/cRO.pm
- added support for items that are 4 bytes long
fix issue #3520
> fix package "special_item_obtain" for cRO

- src/Network/Receive/vRO.pm
> fix buying_store_items_list_pack vRO

- tables/bRO/portals.txt
- tables/iRO/Renewal/portals.txt
- tables/iRO/Transcendence/portals.txt
- tables/iRO/official/portals.txt
- tables/portals.txt
- tables/tRO/portals.txt
- tables/vRO/portals.txt
> updated portals in Lasagna

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
add 0B39, 0B41, 0B44 and 0B45 packets
this pull fixes #3577
this pull closes #3586
> feat: add new item list packet

- .github/workflows/build_XSTools.yml
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
- updated ubuntu-18.04 to ubuntu-20.04
- updated ubuntu-20.04 to ubuntu-22.04
> updating ubuntu versions

- src/Commands.pm
- src/Plugins.pm
New functions:
- getPluginsFiles
- getCondition
- unloadByRegexp
- unloadPlugins
- loadByRegexp
- loadPlugins
- reloadByRegexp
- reloadAll
- reloadPlugins
Also changed Commands.pm accordingly
> Changes to plugin loading functions

- src/Actor/Item.pm
> Fix equipAuto trying to equip non identified items

- control/config.txt
- src/AI/CoreLogic.pm
Fixes #3619 
Also adds 3 conf keys
attackAuto_notWhile_storageAuto 1
attackAuto_notWhile_buyAuto 1
attackAuto_notWhile_sellAuto 1
Which define if attackauto will trigger while in the respective action
> Fix attackAuto_inLockOnly

- src/AI.pm
- src/Misc.pm
This makes it possible to call this sub for other reasons than ai_getAggressives and add a callhook to be used with plugins such as this: https://www.youtube.com/watch?v=gv7tBjE4nJ0
> Move ai aggressiveness check to a single sub in Misc

- control/config.txt
- src/Misc.pm
currently runFromTarget_maxPathDistance is not working.
> fix runFromTarget_maxPathDistance

- src/AI/Attack.pm
What this check does:
If bot has started attacking a target, but the mob is not yet considered aggressive towards the bot and there is another monster in the monsterlist who is considered aggressive then switch aggro to that mob.
Video showcase
https://www.youtube.com/watch?v=qOsMopyblc0
> add attackChangeTarget check

- src/AI/Attack.pm
> Don't change target to attack while in a conversation

- src/AI/Slave/Homunculus.pm
- src/AI/SlaveManager.pm
- src/Actor.pm
- src/Actor/You.pm
- src/Commands.pm
- src/Misc.pm
- src/Network/Receive.pm
- src/Task/Move.pm
- src/Task/Route.pm
> Fix homunculus dead state

- control/config.txt
- src/AI/CoreLogic.pm
> Recompile portals after new record

- src/AI/Attack.pm
Title
These lines became useless after meetingposition usage
> Remove unused follow code from Attack.pm

- src/AI/CoreLogic.pm
To be used with plugins such as https://github.com/Henrybk/Plugins/blob/master/randItemsTakeTimeout/randItemsTakeTimeout.pl
That randomizes ai_items_take_delay timeout to +-50% after every item taken to appear more human
> add ai_items_take callhook

- src/Interface/Wx/MapViewer.pm
New style for wx_map_route, prints every single step in the route
> Add wx_map_route 2

- src/AI/CoreLogic.pm
> Fix standing up before saveMap_warpToBuyOrSell

- control/config.txt
- src/AI/CoreLogic.pm
- src/Actor/Item.pm
- src/InventoryList.pm
With this key buyauto will only sum identified items.
equipAuto will now properly equip identified items when there are non identified varients in inventory
> Add onlyIdentified to buyauto and equipAuto

- src/AI/CoreLogic.pm
To be used with plugins such as https://github.com/Henrybk/Plugins/tree/master/BetterWalkPlan
> Add ai_processRandomWalk hook

- src/Commands.pm
- src/Network/Send.pm
- src/Network/Send/kRO/RagexeRE_2020_04_01b.pm
In 2020 04 01b sendBuyBulkBuyer did not work because of len missing.
Command was also not working.
> Fix sendBuyBulkBuyer

- plugins/eventMacro/eventMacro/Runner.pm
Core is not respecting submacros/subcalls macro block, this makes it respect it.
> Fix macro_block subcall

- src/AI.pm
- src/AI/Attack.pm
- src/AI/CoreLogic.pm
- src/AI/SlaveAttack.pm
- src/Actor.pm
- src/Task/MapRoute.pm
- src/Task/Route.pm
Adds many missing routing parameters, fix allowed parameters list, fix target dropping after kill in attack and slave ai, fix dequeuing in attack ai.
> Fix routing parameters and Attack dropping

- src/Task/MapRoute.pm
Sometimes when routing to a warp npc the pos_to check is a fail but the pos check is a sucess, making an infinite loop.
This fixes that and adds a bit of leeway of 2 cells in the check
> Fix mapRoute pos_to npc bug

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> add missing time_move, time_move_calc and pos declaration

- src/Network/Receive.pm
See https://github.com/HerculesWS/Hercules/issues/3154
> Workaround for move packet bug

- src/Commands.pm
Before this patch character will not attack aggresively while routing using move command
> move command attack behavior follows attackAuto setting

- src/AI.pm
- src/AI/Attack.pm
- src/AI/CoreLogic.pm
- src/AI/SlaveAttack.pm
- src/Actor/Item.pm
- src/Commands.pm
- src/FileParsers.pm
- src/Interface/Console/Curses.pm
- src/Misc.pm
- src/Network/DirectConnection.pm
- src/Network/PacketParser.pm
- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
- src/Network/XKore.pm
- src/Settings.pm
- src/Task/MapRoute.pm
- src/Task/Route.pm
- src/Utils/PathFinding.pm
- src/functions.pl
- src/test/PluginsHookTest.pm
The [documentation](https://openkore.com/wiki/hooks) has a command to get all hooks:
`find src -type f \( -name "*.pl" -or -name "*.pm" -not -name "Plugins.pm" -not -name "PluginsHookTest.pm" \) -exec grep -Hn "^[^#]*callHook" {} \; | sed -E s/\\t+/\\t/ | sed s/\\sif.*//`
Some lines do not contain hook names.
This pull request fixes it.
> small fix callHooks

- src/Commands.pm
- src/Network/Receive.pm
> fix: move sold item message to network receive

- src/Network/Receive.pm
- src/Task/TalkNPC.pm
> fix: add id check in npc talk close

- plugins/needs-review/avoidSkill/avoidSkill.pl
- plugins/needs-review/exchange/tags/kali/exchange.pl
- plugins/needs-review/exchange/trunk/exchange.pl
- plugins/needs-review/tele-search v2/trunk/tele-search v2.pl
- plugins/teleToDest/teleToDest.pl
- src/AI.pm
- src/AI/Attack.pm
- src/AI/CoreLogic.pm
- src/AI/SlaveAttack.pm
- src/Actor.pm
- src/ChatQueue.pm
- src/Commands.pm
- src/Misc.pm
- src/Task/MapRoute.pm
- src/Task/Route.pm
- src/Task/Teleport.pm
- src/Task/Teleport/Random.pm
- src/Task/Teleport/Respawn.pm
Convert all calls to teleport into a single task
All bugs exploits was removed, since dont work on privates and seems to not work in most of official servers (from my friends experience this kind of use stuck openkore after some time)
This closes #388
fixes #3341 
close #3711
TODO:
when merge: #3701 add check for continuos skill / craft list
add post delay check?
> feat: implement teleport task

- src/Network/Receive.pm
Tested working nicely with xkore2
> Enable portal record for all xkore mode

- src/Network/XKoreProxy.pm
before:
https://github.com/OpenKore/openkore/assets/10372732/3a736406-671a-4f29-bfdf-04e527498042
after:
https://github.com/OpenKore/openkore/assets/10372732/dd038130-c292-45cd-9d53-d7ade76f3ae3
> fix: avoid hash ref error when login twice

- src/Actor.pm
- src/ActorList.pm
- src/Commands.pm
add support to:
talk "NPC Name"
> feat: implement actor getbyname

- src/Actor.pm
- src/Commands.pm
- src/Misc.pm
statuses command display all character status and time left
> feat: implement statuses command

- .github/workflows/build_XSTools.yml
- openkore.pl
- renamed artifacts
- added new OpenKore startup check
> updated github actions

- src/Misc.pm
> hotfix: avoid infinity loop in processNameRequestQueue

- control/timeouts.txt
- src/AI/Attack.pm
- src/AI/CoreLogic.pm
- src/AI/Slave.pm
- src/AI/SlaveAttack.pm
- src/Actor.pm
both check was stucking openkore for 1.2 ~ 3 sec after kill monster
fix #3797
> fix: remove checkMonsters and improve items_take

- .github/workflows/build_XSTools.yml
Build was failing due to g++ being moved, causing XSTools.dll build to fail
> Fix GitHub actions for windows

- plugins/eventMacro/eventMacro/Condition/QuestHuntOngoing.pm
Same as https://github.com/OpenKore/openkore/pull/3825
> Fix map change invalidate QuestHuntOngoing

- src/Commands.pm
"uneq all" unequips all equipped equipment
> Added "all" option to "uneq" command

- src/Commands.pm
- src/Network/Send.pm
- src/Network/Send/ServerType0.pm
- src/Network/Send/kRO/Sakexe_0.pm
fix: https://github.com/OpenKore/openkore/issues/3894
Added new command: "memorial destroy"
thanks @alisonrag
> add memorial_dungeon_command

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
Add packets 0B76 and 0BA4. 
Struct copied from [rathena packet struct](https://github.com/rathena/rathena/blob/0a68e9889ee4867874d459548b0981f8519e29f6/src/map/packets_struct.hpp#L2738)
Tested lightly.
Before:
After:
> Add new homunculus packets

- src/Network/Receive.pm
- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/Sakexe_0.pm
> Fix skill failed packet

- plugins/eventMacro/eventMacro/Condition/QuestActive.pm
- plugins/eventMacro/eventMacro/Condition/QuestHuntCompleted.pm
- plugins/eventMacro/eventMacro/Condition/QuestHuntOngoing.pm
- plugins/eventMacro/eventMacro/Condition/QuestInactive.pm
- plugins/eventMacro/eventMacro/Condition/QuestOnTime.pm
- plugins/eventMacro/eventMacro/Condition/QuestTimeOverdue.pm
- src/Network/Receive.pm
All eventMacro quest conditions relied on packet_mapChange and inventory_ready which either don't work always in xkore 3 (packet_mapChange) or don't work at all in new clientes (inventory_ready), this should fix them all.
Fixes #3934
> Fix eventMacro quests

- plugins/eventMacro/eventMacro/Condition/Base/InInventory.pm
- plugins/eventMacro/eventMacro/Condition/InventoryCurrentSize.pm
- plugins/eventMacro/eventMacro/Condition/IsEquippedID.pm
- plugins/eventMacro/eventMacro/Condition/IsNotEquippedID.pm
- src/InventoryList/Inventory.pm
Inventory conditions were permanently in stand by since the new inventory list ready packets.
> Fix eventmacro inventory

- plugins/eventMacro/eventMacro/Condition/BaseLevel.pm
- plugins/eventMacro/eventMacro/Condition/CurrentHP.pm
- plugins/eventMacro/eventMacro/Condition/CurrentSP.pm
- plugins/eventMacro/eventMacro/Condition/JobLevel.pm
- plugins/eventMacro/eventMacro/Condition/MaxHP.pm
- plugins/eventMacro/eventMacro/Condition/MaxSP.pm
eventMacro lvl and hp/sp conditions are not working in xkore3 since they hook in sendMapLoaded which is not present in xkore3
> Fix eventmacro lvl hp sp conditions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Now when creating a problem we have a choice:
1) Create "Bug Report"
2) Create "Feature Request"
3) Follow the link to "OpenKore forums"
4) Follow the link to "OpenKore Discord"
> Updated Issue templates

- src/Network/Receive/ServerType0.pm
- src/Network/Receive/kRO/RagexeRE_2010_04_13a.pm
- src/Network/Receive/kRO/Sakexe_2004_07_05a.pm
- src/Network/Receive/kRO/Sakexe_2007_11_06a.pm
> fix: old packet struct

- src/Actor.pm
- src/Network/Receive.pm
Some places were changing actor names without using the proper function, this PR fixes that and also adds a hook call to it.
> add callhook On SetName

- src/Network/ClientReceive.pm
- src/Network/PacketParser.pm
clienthandle was not importing packetparser, making mangling impossible.
This fixes it.
> Fix proxy clienthandle and mangle

- src/Network/Receive.pm
avoid client disconnect on character select
> fix: add check to switch character

- src/AI/CoreLogic.pm
- src/Commands.pm
- src/Network/Receive.pm
> Fix $ai_v{'npc_talk'} staying defined

- src/AI/CoreLogic.pm
- src/Commands.pm
- src/Interface/Wx/MapViewer.pm
- src/Misc.pm
it avoid openkore attack all monster on manual route and force it only to react to aggressive monsters
> fix: sets manual routes to only react aggressives

- src/Network/Send/ROla.pm
this is not the correct algo/code/place
> fix: remove wrong checksum code

- src/Task/TalkNPC.pm
> Fix talk npc hidden

- README.md
> fix: updates wiki control link

- src/Misc.pm
- src/Network/Receive.pm
- src/Network/Send.pm
- src/Task/TalkNPC.pm
- src/functions.pl
Removes old itemsIDlist which was not used anywhere, adds many cleaning spots for the temp vars and avoid vivification in some places
> Fix aiv npc vivification

- control/timeouts.txt
- src/Task/TalkNPC.pm
Adds a timeout before send NPC next conversation step this prevents some DCs in official servers
> Add npc timeout

- src/Commands.pm
- src/Misc.pm
> Add item id to inventory commands and storage logs

- control/timeouts.txt
- src/Misc.pm
> Add prohibited cells to meeting position and timeout

- plugins/eventMacro/eventMacro.pl
- plugins/eventMacro/eventMacro/Condition/ConfigKeyDefined.pm
- plugins/eventMacro/eventMacro/Condition/ConfigKeyDualDifferentDefinedValue.pm
- plugins/eventMacro/eventMacro/Condition/ConfigKeyDualSameDefinedValue.pm
- plugins/eventMacro/eventMacro/Condition/ConfigKeyUndefined.pm
- plugins/eventMacro/eventMacro/Condition/InventoryReady.pm
- plugins/eventMacro/eventMacro/Condition/QuestInactive.pm
- src/AI/Attack.pm
- src/AI/CoreLogic.pm
- src/FileParsers.pm
- src/Misc.pm
- src/Network/Receive.pm
- src/Task/CalcMapRoute.pm
- src/Task/MapRoute.pm
- tables/ROla/portals_airship.txt
[Add achieve hook to fix questInactive on empty list](https://github.com/OpenKore/openkore/commit/e2028b0fb77e3c96f13c03e33f2cf1cb3018a47d)
[Add a hook to check if there is any ready to fire automacro](https://github.com/OpenKore/openkore/commit/f51b738097add3982dab90c0917fecc729d84115)
[many emacro conditions](https://github.com/OpenKore/openkore/commit/f6444402859d33eacc4334936ca3d06ca3ac9e00)
[improvement on attackchangetarget in attack process](https://github.com/OpenKore/openkore/commit/ee98ef4232c1801fddb2926ae40bc73a1e1ce649)
[Remove looter and skillCancel traget dropping, add getBestTarget hook](https://github.com/OpenKore/openkore/commit/039c526e452d8beec64d2b06bd461e96e3a6f60b)
[add support for Rola Airship](https://github.com/OpenKore/openkore/commit/7b8b0cc4d6f5863793b61383e8c2 …
> Callection of many small upgrades 

- src/Network/Receive/ROla.pm
Fixed disconnection error when connecting with a character who is a member of a guild.
> fix: rola guild disconnect

- control/config.txt
- control/poseidon.txt
- src/Network/Receive/ROla.pm
- src/Poseidon/Client.pm
- src/Poseidon/Config.pm
- src/Poseidon/RagnarokServer.pm
- src/Poseidon/poseidon.pl
- src/Poseidon/servertypes.txt
- ROla servertype
- Checksum support
- Gameguard query timeout
- Fake IP (for nating porpouse)
> Poseidon: support to ROla and few improvements

- openkore.pl
- src/Base/Server.pm
- src/Base/Server/Client.pm
- src/Bus/Client.pm
- src/Bus/Query.pm
- src/Bus/Server/AbstractServer.pm
- src/Bus/Server/MainServer.pm
- src/Bus/SimpleClient.pm
- src/Bus/bus-server.pl
- src/ErrorHandler.pm
- src/Utils.pm
Adds a lot of error handling, reconnecting, debug messages and shutdown fixes.
> Bus system update

- src/Task/Teleport/Random.pm
- src/Task/Teleport/Respawn.pm
> fix: adds check for useskill config key when teleport
